[로그인] API 변경사항 적용, 에러 처리
BCSDLab/KOIN_OWNER_WEB pull request #11
Opened 2023-06-02 14:22 UTC by hanagertrudekim

## [#1] request

## 로그인 API 변경사항 적용/ 자동 로그인 구현
- 기존 로그인 API에 refresh 토큰이 추가되어, 로직을 변경했습니다.
- refresh 토큰은 `localStorage`에서 관리되며, access 토큰은 `sessionStorage`로 관리됩니다.
- 자동로그인 여부에 따라 refresh 토큰을 관리하며, 자동로그인 상태를 넘겨주기 위해 `useMutation`의 `variables`를 이용했습니다.
- 인증정보가 헤더에 없으면 refresh 토큰을 storage에서 꺼내와 `/refresh`요청을 진행합니다.
- refresh 토큰이 없거나 만료될시 다시 로그인 페이지로 리다이렉트됩니다.
- 페이지 새로고침시 `defaultLayout`에서 사용자 정보를 불러와 전역 store에 저장해줍니다.
- zod에러의 동기적 처리를 위해 `useErrorBoundary` hook을 정의해주었습니다.
- [react strict mode](https://legacy.reactjs.org/docs/strict-mode.html)로 중복 렌더링이 발생되어 `/refresh`재요청으로 에러가 발생하기에 이를 없애주었습니다.

## react hook form
- [react-hook-form](https://react-hook-form.com) 을 적용했습니다.
- zod 전용 스키마로 타입을 검증하는 `zodResolver`를 추가했습니다.
- 로그인 버튼을 눌렀을때만 검증하기 위해 `onSubmit`과 `onError`를 분리시켰습니다.
- 로그인 에러 UI를 추가했습니다. 

## ErrorBoundary UI 추가
- `ErrorBoundary` UI 추가했습니다.
- 에러 상태에 따른 에러 메시지를 props로 받습니다.

## env 타입 정의 추가
- env 자동완성 기능을 위한 `process.env` 타입을 선언해주었습니다.

### Screenshot
- 로그인 에러
<img width="520" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101982606/d19745d2-bd67-4522-9fbb-21641970a3cb">

- zod 에러
<img width="659" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101982606/3489c27f-cb92-4b74-9404-4b33c0edf7a4">

## Please check if the PR fulfills these requirements

- [o] It's submitted to `develop` branch, __not__ the `main` branch
- [o] The commit message follows our guidelines
- [o] Did you merge recent `deveop` branch?

### Precautions (main files for this PR ...)

2023-06-03 16:19 UTC, ChoiWonBeen requested changes
생각했던 기능들보다 훨씬 많은 구조 수정에 유틸 함수들까지 추가됐네요.. 고생하셨어요 😅 
수정이 필요하거나 고민해볼만한 점들을 꽤 많이 작성해뒀으니 확인해주세요!
만들어두고나니 Zod + ErrorBoundary가 잘 적용된 것 같아 너무 보기좋네요

2023-06-03 16:19 UTC, ChoiWonBeen commented on src/layout/AuthLayout/index.tsx
> +import Copyright from 'component/common/Copyright/Copyright';
그러고보니 `ErrorBoundary` 컴포넌트는 `index.tsx`로 작성되지 않았어요!
바로 아래 `Copyright`도 마찬가지네요 ㅋㅋㅋ

2023-06-03 16:19 UTC, ChoiWonBeen commented on src/query/auth.ts
>        navigate('/');
`DefaultLayout`에서 진행하는 `setUser` 함수와 겹쳐 user가 비동기적으로 set되기 전, 두 번의 API call이 진행되고 있어요!
이 부분은 인계해도 괜찮을 것 같아요 ㅋㅋ

<img width="533" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/50780281/89b52527-60c8-4599-b212-5a3453b96a84">

2023-06-06 11:36 UTC, hanagertrudekim commented on src/model/auth/index.ts
> +}
`LoginForm`으로 이름을 변경하는게 훨씬 파악하기 쉬운것같네요ㅎㅎ 
또한, omit 보다는 form 입력을 위해 원초적인 login params를 확장했다는 방향성을 주기 위해 extends를 쓰는게 더 알맞다고 생각했습니다! ( api model을 기준으로 확장한 느낌이 client model에 들어가야 맞다는 생각도 들었고요)

2023-06-06 11:52 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
>    };
`react-hook-form` 에러의 활용이 아직은 없어서, 추후에 활용해도될것같아요
지금 목적은 서버에 제출하기 전 form의 검증 목적이니, `boolean`으로 목적을 맞추고 네이밍을 변경하는것이 확실히 좋을것같습니다 2fad96d677477de96524c8e46f6d5454ac2a0451

2023-06-06 11:58 UTC, hanagertrudekim commented on src/api/auth/model.ts
> +  email: z.string().email(),
zod에 다양한 타입으로 validation할수있는것들이 많더라구요 (max, min 등등..) 
필요성이 있다면 활용하면 좋을것같아요!

2023-06-06 14:25 UTC, ChoiWonBeen commented on src/page/Auth/Login/index.tsx
>    };
불린형으로 타입을 수정했으니 불린형 변환(`!!isFormError`)이 불필요해보이고, 
`isError`를 두가지 에러여부를 기반으로 만들었으니 아래 중복되는 부분을 줄일 수 있을 것 같아요!
```tsx
const isError = isServerError || isFormError;

// before
[styles['form__input--error']]: isServerError || !!isFormError,

// after
[styles['form__input--error']]: isError,
```

2023-06-07 00:48 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
>    };
47e0589b778fb4de6c832360c1512cb8cf35dc31 추가 수정해주었습니다

2023-06-07 05:05 UTC, hanagertrudekim commented on src/layout/AuthLayout/index.tsx
> +import Copyright from 'component/common/Copyright/Copyright';
변경해주었습니다 6b6057a3705b45ab83d6c8779bd97ff3aba30965

2023-06-08 05:15 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +  const { mutate, isError } = useLogin();
오히려 저는 `mutate`가 `react-query`의 메서드라는걸 구분지어주어 좋다고 생각했는데,
혹시 `react-query`를 썼다는걸 알리지않는게 좋다고 생각하신 이유가 있을까요??

2023-06-08 05:20 UTC, hanagertrudekim commented on src/api/auth/index.ts
> +export const postLogin = async (param: LoginParams) => {
아하.. restful api라서 생기는 타입의 중복성까지 고려하지 못했네요
방향을 한곳에 맞추긴해야할것같은데, 어떤 메서드인지 따라 구분짓는것도 방법일것같아요
로그인도 마찬가지로 `PostLoginParams`로 맞추는건 어떨까요?

2023-06-08 05:37 UTC, hanagertrudekim commented on src/utils/hooks/user.ts
> +  };
스토어에서 상태 업데이트를 관리하는것은 좋은 아이디어 같은데, 토큰을 관리하는 로직까지 관심사가 맞을까 조금 애매해지는것같네요.. 이에 대해서는 어떻게 생각하시나요?
차라리 스토어에는 set하고 remove하는 action만 분리하는것도 좋다고 생각합니다

2023-06-08 06:14 UTC, hanagertrudekim commented on src/query/auth.ts
>        navigate('/');
어디서 중복 요청이 일어났는지 몰랐는데 찾아주셔서 감사합니다ㅎㅎ
defaultLayout쪽으로 인계하도록 수정했습니다 b0f3206729b531487d3c9091e58e5ea7e397379a

2023-06-08 08:04 UTC, ChoiWonBeen commented on src/page/Auth/Login/index.tsx
> +  const { mutate, isError } = useLogin();
간단하게 `useLogin`을 쓰는 컴포넌트의 입장으로 봤을때, 로그인 기능을 사용하는 것이 목표니깐 로그인이라는 이름으로 만들어야겠다고 생각했아요.
어떤 로직으로 구현되었는지가 페이지의 관심이 아니라는 점도? 생각이 들었던 것 같아요. 로그인 로직이 `useMutation` 이 아닌 다른 것을 써서 바꾼다 했을때 페이지도 수정해야한다면 **로그인페이지가 useMutation에 결합성을 띈다고** 생각했어요.

2023-06-08 08:11 UTC, ChoiWonBeen commented on src/api/auth/index.ts
> +export const postLogin = async (param: LoginParams) => {
오 좋은거같아요
API도 이름 통일하는것도 깔끔하고 좋을것같아요~

2023-06-08 08:14 UTC, ChoiWonBeen commented on src/query/auth.ts
>        navigate('/');
브라우저 네이티브를 쓰지 않고 **리다이렉팅 될 때 경로를 상태로 저장**하고,
해당 상태가 있는가 여부를 통해 홈으로 갈 지, 해당 경로로 갈 지 정하는건 어떨까요?

2023-06-12 11:06 UTC, HAEROOL approved these changes
수고하셨습니다! `zod`와 `react-hook-form`을 활용하는 부분에 있어서 참고할 부분이 많이 있네요

2023-06-13 10:39 UTC, hanagertrudekim commented on src/utils/hooks/user.ts
> +  };
userStore안에 `setUser`와 `removeUser`를 추가해줬습니다. `getMe()`의 중복이 필수적이기 때문에, 그 부분도 추가해 수정해주었습니다  22e7089bf51b552d6793d1ee4df790796e6e8732

2023-06-13 10:50 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +  const { mutate, isError } = useLogin();
아 로직을 캡슐화해서 사용하는 측에서는 알수없게, 통일해서 내보내려는 목적이군요..! 그런 측면에서도 충분히 고려할만하네요. 추가적으로 수정하겠습니다ㅎㅎ 33a93d370fba1cfe58b7c78beae8dccfd7050774

2023-06-13 12:28 UTC, hanagertrudekim commented on src/react-app-env.d.ts
> +}
이와 관련해서 몇가지를 찾아보니, 
1. 환경변수는 type이 항상 `string` 입니다.
2. Node js 기반 프로젝트는 직접 타입을 변환해서 사용하기도합니다.

그래서 `checkEnv`함수를 조금 변형해서 type을 추가적으로 인자로 받은뒤, 해당 타입으로 변형해주는 로직을 추가해주었습니다. 
1. 인자의 type과 환경변수의 type이 맞지 않아도 에러를 던지고
2. 환경변수가 아예 들어있지 않을때도 에러를 던져줍니다.

추가적으로, 기존 외의 타입인 환경변수가 추가된다면, 그에 맞는 타입 함수도 추가해줘야할것같습니다. ef45dabfb92120f4f5cb7865f1fa68f62467bedc

2023-06-13 14:46 UTC, hanagertrudekim commented on src/query/auth.ts
>        }
[17e1844](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/11/commits/17e1844809d5324207bc3ed7f3dabfb59b1de8a3)

2023-06-13 14:47 UTC, hanagertrudekim commented on src/layout/DefaultLayout/index.tsx
> +  const user = useUserStore((state) => state.user);
pathname을 관리하는 store를 추가해, 이전 path로 갈수있는 로직도 추가했습니다521cacc50c348ce8843af94a4c5b12dfbadf191b , 521cacc50c348ce8843af94a4c5b12dfbadf191b

2023-06-13 15:26 UTC, ChoiWonBeen approved these changes
고생했씁니다!! 👍 다 잘 동작하네요!

2023-06-13 15:26 UTC, merged