[가게 등록] 가게 등록 UI 구현
BCSDLab/KOIN_OWNER_WEB pull request #12
Opened 2023-06-05 02:20 UTC by kimeodml

## [#9] request

 - 모바일 디자인만 구현되어 있어서 모바일 부분만을 구현하였습니다.
 - 가게등록의 운영 시간 부분에서 UI가 완전히 달라 경로를 새로 추가하였습니다.
   - 경로 변경이 불필요하면 추후에 수정하겠습니다.
 - 회원가입 부분과 겹치는 부분이 있어 공통 컴포넌트로 구현하였습니다.
   - `Complete`, `PreviousStep`, `ProgressBar`, `SubTitle`
 - `useStepStore`에서 `step`의 상태관리를 하고 있습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/8dfbc1a9-6a92-423e-a69b-d38ecfacc2c9" width="30%" />
<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/0bf265a2-1bfe-4bf9-bcf5-593b5e02354c" width="30%" />
<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/41fce083-9832-442c-823b-91ae8de8a95d" width="30%" />
<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/0486aa0e-84dd-49c0-a724-380733c94380" width="30%" />

### Precautions (main files for this PR ...)

2023-06-06 11:15 UTC, ChoiWonBeen commented on src/App.tsx
> +        <Route path="/operate-time" element={<OperateTime />} />
`StoreReg`... 보다는 `StoreRegistration` 으로 풀네임을 쓰는걸 개인적으로 선호하는 편이예요.
시간 관리창은 단독 경로를 갖기에는,, 나중에 상점 수정할때도 이 페이지를 써야할텐데 **어떤 상태를 다루는 페이지인가** 를 정하기 힘들 수 있을 것 같아요. 꽉 채우는 모달실? 컴포넌트로 만드는게 나을지도..

2023-06-06 11:22 UTC, ChoiWonBeen commented on src/store/useStepStore.ts
> +  clickBackArrow: () => set((state) => ({ step: state.step - 1 })),
step을 한칸씩만 올리게 될 것 같은데, `increase, decrease` 같은 표현을 쓰는건 어땠을까요?

2023-06-06 11:23 UTC, ChoiWonBeen commented on src/static/storeCategory.ts
> +const STORE_CATEGORY:StoreCategory[] = [
추후에 `shops/categories` API를 써서 수정하면 될 것 같아요

2023-06-06 11:25 UTC, ChoiWonBeen commented on src/page/Auth/StoreReg/index.tsx
> +  const [isSelected, setIsSelected] = useState('');
`selectedCategory` 같은 이름은 어땠을까요?
`isSelected`라고 하니 뭔가 boolean타입일거라고 생각이 들었어요

2023-06-07 08:42 UTC, HAEROOL commented on src/component/common/Auth/PreviousStep/index.tsx
> +  clickBackArrow?: () => void;
`clickEvent`는 어떤지 제안해봅니다

2023-06-12 10:16 UTC, HAEROOL approved these changes
고생하셨습니다!  `StepStore`를 만드셨던데 저도 필요하면 활용해봐야겠네요

2023-06-13 05:49 UTC, haejinyun approved these changes
수고하셨습니다! zustand를 사용하신 걸 보면서 개념 이해에 도움이 많이 되었습니다!

2023-06-13 05:55 UTC, haejinyun commented on src/page/Auth/StoreReg/component/OperateTime/OperateTime.module.scss
> +    height: 25px;
height가 조금 적어보여서 35px 정도로 주는 것은 어떨 까요?

2023-06-18 04:31 UTC, kimeodml commented on src/component/common/Auth/PreviousStep/index.tsx
> +  clickBackArrow?: () => void;
추정하기 힘들 수 있을것 같아서 `clickEvent`로 변경했습니다. [876fc5b](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/876fc5b36217e8b98268d288c60658c6579e284c)

2023-06-18 04:32 UTC, kimeodml commented on src/page/Auth/StoreReg/index.tsx
> +                <SubTitle topTitle="가게 등록" bottomTitle="" topText="입력하신 정보가 맞습니까?" bottomText="" />
추가했습니다. [4379d66](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/4379d6633d70cb34b41bb652d83b3ddd9a69e3cd)

2023-06-18 04:33 UTC, kimeodml commented on src/component/common/Auth/ProgressBar/index.tsx
> +  const calculateWidth = () => ((step + 1) / total) * 100;
수정했습니다. [7f43c31](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/7f43c31f09a2485c1f34fc51a83187917fb33cea)

2023-06-18 04:34 UTC, kimeodml commented on src/component/common/Auth/Complete/index.tsx
> +  textBottom: string;
일관되게 수정했습니다. [2ff3ca5](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/2ff3ca510178f7747d6f63a35c1662108ec35f32)

2023-06-18 04:39 UTC, kimeodml commented on src/component/common/Auth/Complete/index.tsx
> +      <Link to={link} className={styles.content__button}>{buttonText}</Link>
수정했습니다. [2ff3ca5](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/2ff3ca510178f7747d6f63a35c1662108ec35f32)

2023-06-18 04:40 UTC, kimeodml commented on src/page/Auth/StoreReg/component/OperateTime/index.tsx
> +  const { step } = useStepStore();
확인했습니다. [2ef0bd6](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/2ef0bd690f0b953140a3de6353b5c40b083cbddc)

2023-06-18 04:41 UTC, kimeodml commented on src/page/Auth/StoreReg/component/OperateTime/index.tsx
> +                <button type="button" onClick={() => step + 1}>다음</button>
제거했습니다. [c7a2fcf](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/c7a2fcfd5bb41255a398e7970ebe122cb164533d)

2023-06-18 04:42 UTC, kimeodml commented on src/store/useStepStore.ts
> +  clickBackArrow: () => set((state) => ({ step: state.step - 1 })),
`decreaseStep`이라는 명칭으로 변경했습니다. [77199e8](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/77199e89b5d2d7a9467c7047c09a72c3e84a3de3)

2023-06-18 04:44 UTC, kimeodml commented on src/static/storeCategory.ts
> +const STORE_CATEGORY:StoreCategory[] = [
변경했습니다. 생각 외로 렌더링 시간이 오래걸리는데 음...이미지 때문일까요? [b03e22b](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/b03e22b166c90001bc4d7928c2424d97a342b855) [d8f1d34](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/d8f1d34fe8022c800d33f4a2c432ae8af5204e92)

2023-06-18 04:44 UTC, kimeodml commented on src/page/Auth/StoreReg/index.tsx
> +  const [isSelected, setIsSelected] = useState('');
수정했습니다. [f26c8cd](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/f26c8cd53d1b74ca4c58f81104fc0432a7a4d351)

2023-06-18 04:52 UTC, kimeodml commented on src/page/Auth/StoreReg/component/OperateTime/index.tsx
> +                  <td>11:00~21:00</td>
변경했습니다. [d66bb24](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/d66bb24a5d079c97aa963bbf70a0ad375e3ff845)

2023-06-18 05:01 UTC, kimeodml commented on src/component/common/Auth/SubTitle/index.tsx
> +}
기본값을 설정해 주었는데 옵셔널로 활용하는 게 일반적인 것 같아서 변경하였습니다. [63ef9fd](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/63ef9fd3b632f0d0ffc649d6676199eae8c64c2e)

2023-06-18 05:01 UTC, kimeodml commented on src/page/Auth/StoreReg/component/OperateTime/OperateTime.module.scss
> +    height: 25px;
수정했습니다. [38d6254](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/38d6254a6199c60cedb5a8af9747e6e30f687d9f)

2023-06-18 05:29 UTC, kimeodml commented on src/component/common/Auth/PreviousStep/index.tsx
> +      <button type="button" className={styles.previous__button} disabled={step === 0} onClick={clickBackArrow}>
꺼내쓰면 OperateTime 컴포넌트에 있는 PreviousStep의 onClick이 실행되어 step===1로 돌아가져 불가능할 것 같습니다.

2023-06-18 07:01 UTC, kimeodml commented on src/component/common/Auth/ProgressBar/index.tsx
> +      <div className={styles.progress__bar}>
`progress` 태그로 변경했습니다. [f5c3963](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/f5c3963995929a87a7ff012139b9e4fb90954e5d)

2023-06-18 23:52 UTC, ChoiWonBeen requested changes
몇가지 수정할만한 사항 더 확인해주세요! 거의 다 끝났네요 ㅋㅋㅋ

2023-06-19 06:40 UTC, hanagertrudekim requested changes
수고많으셨습니다! 간단한 코멘트 하나 확인해주세요ㅎㅎ

2023-06-19 06:40 UTC, hanagertrudekim commented on src/page/Auth/StoreRegistration/component/OperateTime/index.tsx
> +                  </td>
이부분을 따로 `map` 등.. 을 써서 반복적인 코드를 제거할수는없나요??

2023-06-20 06:04 UTC, kimeodml commented on src/component/common/Auth/PreviousStep/index.tsx
> +    </div>
변경했습니다. [1534f2b](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/1534f2b97a1756ece438ca4fd64e6e433ae793b7)

2023-06-20 06:11 UTC, kimeodml commented on src/api/index.ts
> +});
수정했습니다 [814d5a0](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/814d5a003c8f603fc5f4bbb2b90b3dc5a00918eb)

2023-06-20 06:20 UTC, kimeodml commented on src/App.tsx
>        </Route>
`DefaultLayout` 위치로 변경한 후에 store-registration` 경로에만 `Header` 표시가 안 되도록 변경했습니다. [7267346](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/72673462dccb720d95dc973b58deefd5c5d9c9c1) [53d7e9e](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/53d7e9ec51d80c5e8e4421255bb510294b6f64b1)

2023-06-20 07:29 UTC, kimeodml commented on src/App.tsx
>        </Route>
`DefaultLayout` 내부로 변경 후 '/store-registration`일 경우에만 헤더 표시를 제외했습니다. [3721072](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/12/commits/37210724a549fddbe8abeab484955d528592c384)

2023-06-28 09:36 UTC, kimeodml commented
위의 수정사항과, PC UI 디자인 및 api 연동은 다음 브랜치로 넘겨도 될까요?

2023-06-28 19:33 UTC, hanagertrudekim approved these changes

2023-06-29 04:00 UTC, ChoiWonBeen approved these changes
고생하셨습니다~

2023-06-29 04:00 UTC, merged