[가게 등록] 가게 정보 입력 제어 및 저장 실패 시 에러 표현
BCSDLab/KOIN_OWNER_WEB pull request #120
Opened 2024-01-29 11:50 UTC by dooohun

## [#103] request
- 가게 등록 시 배달금액을 `number`로 타입 고정
- 가게 등록 실패 시 `ConfirmPopup`에서 에러 메시지 출력하도록 추가
- 재사용성이 떨어지는 `Input Box` 컴포넌트 삭제
- 그 이외에 필요없는 Effect 수정

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `develop` branch?

### Screenshot
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/84f58518-facf-4fbc-8f07-a85eedfecfb9)

### Precautions (main files for this PR ...)

Close #103

2024-02-01 05:27 UTC, MinGu-Jeong requested changes
<img width="415" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/2e0a9b94-d94f-4686-8e00-6d5035cea106">

배달금액이 없는 경우를 가정하여 0원을 입력하면 
`value={deliveryPrice === 0 ? '' : deliveryPrice}` 에서 0이 `''`으로 바뀌면서 에러메시지가 나오는것으로 보입니다.

2024-02-01 11:23 UTC, dooohun commented
@MinGu-Jeong 처음 디폴트 값을 안보이게 작성하는 것만 신경쓰다가 0이 안써지는 에러를 초래한 것 같습니다...😢 
input 태그 `defaultValue` 속성을 사용해서 해당 에러를 수정하였습니다. a9e20fa082e591520ef9e896bf6cdac7d85b4abd

2024-02-01 15:52 UTC, MinGu-Jeong commented
@dooohun 
<img width="425" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/bf86b520-cd8e-4a25-9180-fce330fd234e">

이제 0은 들어가긴 하는데, 여전히 에러메시지가 뜨고 다음으로 진행이 불가능합니다...🥲
한 번만 확인 부탁드릴게요~

2024-02-02 05:32 UTC, hanagertrudekim approved these changes

2024-02-02 05:32 UTC, hanagertrudekim commented on src/page/ShopRegistration/view/PC/index.tsx
> +                    }}
`valueAsNumber`로 Number 타입 체크를 하는데, data를 set할떄 다시 Number타입으로 변환해야하는 이유는 타입 추론 때문인가요??

2024-02-02 09:54 UTC, dooohun commented on src/page/ShopRegistration/view/PC/index.tsx
> +                    }}
`valueAsNumber`는 React-Hook-Form에게 delivery_price에 해당하는 값을 Number타입으로 알려주기 위해 사용했습니다.
e.target.value는 여전히 string 타입이기 때문에 Number 타입으로 변환이 필요하다고 생각해서 Number를 추가했습니다!
(`deliveryPrice`의 타입은 `Number`타입 입니다.)

2024-02-02 09:56 UTC, dooohun commented
@MinGu-Jeong 
앗... 제가 또 놓쳤네요. 좋은 리뷰 감사합니다!!
`ref`를 사용해서 input의 값이 빈문자열 일 때 에러 문구를 출력하도록 수정했습니다! a31d43224e3ad6fd843706bba9eb09e3d2628322

2024-02-02 10:15 UTC, MinGu-Jeong approved these changes
수고하셨습니다!
로직들이 잘 동작하네요😀

2024-02-02 10:52 UTC, merged