[내상점] 내상점 로직 추가
BCSDLab/KOIN_OWNER_WEB pull request #13
Opened 2023-06-17 04:24 UTC by haejinyun

## [10] request

* api연동 및 반응형 작업 진행하였습니다.

* 현재 메인 사진 3장 띄우는 디자인 이라 인덱스 활용(0,1,2)으로 3장 띄웠습니다
* 메뉴 사진 또한 리스트로 값이 오기에 0번째 인덱스로 사용했습니다

* 모바일 웹 디자인이 나오지않아 안드로이드 디자인을 보고 비슷하게 제작해 보았습니다.
* 모바일 웹에서 메뉴를 표현하는 부분에서 슬라이드를 활용해보았습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img width="1305" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/86779590/ac132785-10ed-4d35-8662-c248d6176cc6">
<img width="1305" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/86779590/0e2c478b-243b-4ae0-8446-c6423084c3c9">
<img width="493" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/86779590/6cfcb9c4-4d54-428d-9c46-cbfa935af92c">
<img width="493" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/86779590/e51f479f-edc1-4cd3-9165-04510ec9d0c4">

### Precautions (main files for this PR ...)
* 모바일 버전에서 현재 가게 사진을 한개만 띄우고 있습니다.   
 이 부분은 추후에 캐러셀 작업을 통해서 넘기는 방향으로 추가 될 가능성도 있습니다.

2023-06-19 02:16 UTC, ChoiWonBeen reviewed
<img width="1746" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/50780281/2b8a0c0a-bf21-4f52-ba1c-991501714ecd">
shops가 없는 경우에는 아무 화면도 나오지 않는데, 실제 서비스할때는 shops가 없을 일은 없으니.. 테스트 계정을 알려주셔야 테스트를 할 수 있을 것 같아요!

2023-06-19 02:55 UTC, haejinyun commented
> <img alt="image" width="1746" src="https://user-images.githubusercontent.com/50780281/246708793-2b8a0c0a-bf21-4f52-ba1c-991501714ecd.png"> shops가 없는 경우에는 아무 화면도 나오지 않는데, 실제 서비스할때는 shops가 없을 일은 없으니.. 테스트 계정을 알려주셔야 테스트를 할 수 있을 것 같아요!

네 위에 첨부했습니다! 미처 생각을 못했네요 감사합니다!

2023-06-22 06:41 UTC, ChoiWonBeen requested changes
고생하셨습니다~ 몇가지 수정사항 확인해주세요!

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
> +                  )}
`MultiPriceMenu`와 `SinglePriceMenu`의 Union Type이기 때문에 두번째 조건이 없어도 충분히 `SinglePriceMenu`로 추론된다는 점을 활용해보는건 어떨까요??
그냥 적어만두면 쉽게 이해되지 않을 수 있으니 적절한 주석을 포함하는 것도 좋아보이네요
```suggestion
                  {menu.option_prices ? menu.option_prices.map((option) => (
                    <span className={styles['menu__price-unit']} key={option.option}>
                      {`${option.option}:${option.price.toLocaleString()}원`}
                    </span>
                  )) : (
                    <span className={styles['menu__price-unit']}>
                      {`${menu.single_price.toLocaleString()}원`}
                    </span>
                  )}
```

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
>            <EventMarkIcon className={styles['category__event-mark']} />) : null}
아마 이 조건은 추후에 category타입에 추가되겠죠? 제목에 대한 의존성을 갖는게 좋아보이진 않네요

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/index.tsx
> +              menus={category}
이 부분때문에 하위컴포넌트에서 `menus.menus.map` 같은 어색한 표현들이 나오는 것 같은데,
실질적으론 타입으로 정의해둔 `MenuCategory`를 넘기고, 해당 카테고리에 포함된 메뉴들이 포함되기에 props명칭을 정확하게 수정하는게 좋을 것 같아요.

그럼 `<CategoryMenuList />` 컴포넌트에서도 `menuCategory.menus.map` 처럼 적절하게 쓸 수 있겠죠??

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
> +            <div key={menu.name} className={styles.menu__item}>
`overflow-x: scroll` 을 포함한 슬라이더를 만들 때의 팁인데, 스크롤이 생길 위치에 패딩을 만들어주면 좋아요.
여기 부분에도 마진을 줄이고 어느 정도 패딩을 준다면 스크롤바가 들어갈 영역이 생겨 좋은 UI를 만들 수 있겠죠??
혹은 스크롤바를 없애는 것도 방법일 것 같구요.

![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/50780281/b5aafcce-7a7a-47eb-a415-ed41e7323f50)

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/components/StoreInfo/StoreInfo.module.scss
> +  &__small-keywords {
이런 클래스명은 엘리먼트보단 modifier로 표현하는 게 적절하다고 생각하는데 어떤가요?
```suggestion
  &__keywords--sm {
```
큰 키워드나 기본적인 사이즈가 있다면 중첩해서 사용하는게 좋아보이구요
```suggestion
  &__keywords {
    // ...
    &--sm {
```

2023-06-22 06:41 UTC, ChoiWonBeen commented on src/page/MyStorePage/components/StoreInfo/index.tsx
> +                </div>
null로 보이는데 적절한 처리를 해두는게 좋아보이네요 ㅋㅋ

2023-06-23 07:44 UTC, haejinyun commented on src/page/MyStorePage/index.tsx
> +              menus={category}
좋은 방향인 것 같습니다! 수정해보겠습니다.

2023-06-23 07:50 UTC, haejinyun commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
> +            <div key={menu.name} className={styles.menu__item}>
padding-bottom을 10px정도 주는 방향으로 개선해보았습니다.
좋은 팁 감사합니다!

2023-06-23 07:54 UTC, haejinyun commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
> +                  )}
간단한 주석으로 옵션 가격과 단일 가격을 구분해 두었습니다.
좀 더 똑똑한 방법으로 Union Type을 사용할 수 있었네요!

2023-06-23 10:54 UTC, hanagertrudekim requested changes
수고하셨습니다! (너무 늦게 리뷰했네요ㅠㅠ)

2023-06-23 10:54 UTC, hanagertrudekim commented on src/model/storeInfo/myStoreInfo.ts
>    id: number;
api쪽에서 쓰이는 model을 여기에 정의하신 이유가 있나요? 
api를 위한 param, response관련 타입들을 api쪽에 분리하고,
객체 정의, 스토어 등등 클라이언트에 필요한 타입을 여기에 분리하는것은 어떨까요? (기존의 통일성을 고려한 부분도 있을것같네요)

2023-06-23 10:54 UTC, hanagertrudekim commented on src/page/MyStorePage/components/StoreInfo/StoreInfo.module.scss
> +  &__small-keywords {
keyword의 small과 large의 차이가 `width`밖에 없는거같은데,
글자수에 따라  width를 조정할수있는 속성을 이용하면 하나의 css로 통일하는것도 가능할것같아요

2023-06-23 10:54 UTC, hanagertrudekim commented on src/api/store/index.ts
> +  const { data } = await accessClient.get<MyStoreInfoRes>(`/owner/shops/${param.id}`);
이름이 한쪽으로 통일되지못한 부분이 있는것같은데, store와 shop둘중 하나에 맞추는게 좋을것같아요
또한, 상점의 list를 응답받는 api인지, 상세 정보를 받는 api인지도 명확하게 구분해주는것은 어떨까요?

2023-06-23 15:53 UTC, haejinyun commented on src/page/MyStorePage/components/CatagoryMenuList/index.tsx
>            <EventMarkIcon className={styles['category__event-mark']} />) : null}
네 이전에 UI/UX 트랙에게 말씀 드렸는데 확실한 디자인 예시나 디자인이 나오지 않아 재문의 후 백엔드 트랙에게 메뉴 카테고리 api에 속성 추가 이야기를 진행하려고 합니다!

2023-06-23 18:10 UTC, haejinyun commented on src/api/store/index.ts
> +  const { data } = await accessClient.get<MyStoreInfoRes>(`/owner/shops/${param.id}`);
shop으로 통일 하였습니다! (store의 경우 저장소와 혼동이 있을 수 있을 것 같았습니다!)
list를 받는 api는 모두 뒤에 list를 붙여 구분하였습니다!

2023-06-23 18:50 UTC, haejinyun commented on src/model/storeInfo/menuCategory.ts
> +export const MenuBase = z.object({
singleprice / multiprice 메뉴를 union타입으로 가지는 것의 이름을 Menu라고 하였습니다.  
Menu라는 온전한 이름에 더 어울린다고 생각하였습니다.

MenuBase에서 확장해 singleprice / multiprice 중 하나를 가지면 Menu가 되는 방향으로 구상해보았습니다.

2023-06-23 19:04 UTC, haejinyun commented on src/page/MyStorePage/components/StoreInfo/StoreInfo.module.scss
> +  &__small-keywords {
width를 auto로 두고 padding을 주어 여백을 살렸습니다! 조언 감사합니다!

2023-06-24 06:45 UTC, haejinyun commented on src/model/storeInfo/myStoreInfo.ts
>    id: number;
가장 큰 이유로는 제가 진행하였던 내 상점 페이지에서 사용되는 api가 생각보다 세부적으로 나누어져 있어 이를 api 폴더 내의 model.ts라는 파일 하나에서 관리하는 것이 너무 무거워질뿐더러 보기에도 좋지 않을 것이라고 생각했습니다.
만약 이 부분을 api 폴더 내부에서 ~model.ts라고 명명하고 분리를 하게 된다면 이는 api 폴더가 아닌, model이라는 폴더 내부에서 위치하는 것이 더 적합해 보인다고 판단했습니다!

또한 타입이나 형식을 지정하는 부분은 model 폴더 내부에 진행하였던 기억이 있어 model 폴더에 지정을 하고 api 폴더에서 필요한 타입만 불러와 사용하는 방향을 선택했습니다.
이렇게 되었을 때 관련된 model 관리가 한 부분에서 가능하다는 점이 장점이라고 생각했었습니다..!

타입 위치는 진행하면서도 고민이 되었던 부분인지라 다른 분들은 어떤지 의견을 듣고 정하는건 어떨지 싶습니다..!

2023-06-26 07:32 UTC, ChoiWonBeen requested changes
몇가지만 더 확인해주세요~ 거의 끝나가는 것 같네요 ㅋㅋ

2023-06-26 11:23 UTC, haejinyun commented on src/query/shop.ts
> +  const { data: myShop } = useQuery(['myShop'], getMyShopList);
스토어에 저장되어 있는 user정보 중 사업자 번호를 쿼리키로 하여 수정하였습니다!

2023-06-26 11:36 UTC, haejinyun commented on src/page/MyShopPage/components/ShopInfo/index.tsx
> +                <img src={shopInfo.image_urls[2]} alt="main" className={styles['store__subimgs-bottom-pic']} />
관련 부분 공통된 것은 묶어 불필요한 중복 css 제거 하였습니다!

2023-06-26 13:02 UTC, haejinyun commented on src/page/MyShopPage/components/ShopInfo/index.tsx
> +              </div>
좋은 방법이 있었네요! 해당 방식으로 수정해보았습니다

2023-06-26 13:35 UTC, haejinyun commented on src/query/shop.ts
> +  });
response로 온 shops 배열(사장님이 등록한 가게)의 인덱스를 함수 인자로 통해 해당 shop의 id를 선택할 수 있는 함수  `selectedShopId` 를 추가하였습니다.

2023-06-27 01:48 UTC, hanagertrudekim commented on src/model/storeInfo/myStoreInfo.ts
>    id: number;
api 파라미터로 쓰이는 타입들은 api쪽에 정의해주면 관심사가 분리되지 않을까해서 다음과 같은 의견을 말한것같아요ㅎㅎ
모델을 한 파일에 몰아서 정의하기보다는, 좀더 세부적으로 관심사를 분리해서 하자는게 목적이였을것같네요!
(저도 이와 관련해서 저번 코멘트를 많이 받았던지라.....)
다만 한방향으로 통일성을 맞추는 것은 중요할것같아요!

2023-07-04 10:30 UTC, ChoiWonBeen approved these changes
고생하셨어요~ 모델 파일 위치 정도만 통일하고 머지하면 될 것 같아요.

`/api/model` 말고 `/model` 에서 정의한다면 기존에 api 경로에 있는 파일들도 같이 통일해서 이후 작업자들이 헷갈리지만 않게 작성해두면 좋을 것 같아요

2023-07-04 11:23 UTC, HAEROOL approved these changes
고생하셨습니다!

2023-07-09 16:41 UTC, haejinyun commented on src/model/storeInfo/myStoreInfo.ts
>    id: number;
/model 안에서 정의하는 방향으로 통일하였습니다!
혹여 한 파일 내부에서 다뤄야하는 타입이 많다면 이 안에서 폴더를 나눠 사용할 수 도 있을 것 같다고 생각되었습니다..!

2023-07-10 18:01 UTC, hanagertrudekim approved these changes

2023-07-11 04:56 UTC, merged