[회원가입] 회원가입 페이지 유저 데이터 입력 로직 구현 및 api 연동
BCSDLab/KOIN_OWNER_WEB pull request #15
Opened 2023-07-11 12:24 UTC by HAEROOL

## [#2] request

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
![스크린샷 2023-07-11 오후 9 02 45](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/19d062a3-7d84-4dfb-8aef-32941d50d6aa)

![스크린샷 2023-07-11 오후 9 03 30](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/b0715827-a9dc-4a6d-b3fc-800c40006086)

### Precautions (main files for this PR ...)
 - 에러 메시지 대응을 위한 ErrorMessage 컴포넌트를 만들었습니다.
 - 모바일/데스크톱의 회원가입 `step`을 통일하기 위해 `progressStep`과 `registerStep` 분리하여 구현했습니다.

2023-07-11 15:37 UTC, kimeodml requested changes
고생하셨습니다!

2023-07-11 15:37 UTC, kimeodml commented on src/page/Auth/Signup/index.tsx
> +  } = useRegisterStep();
바로 useStepStore 호출해도 되지 않나요...?

2023-07-12 12:44 UTC, HAEROOL commented on src/page/Auth/Signup/hooks/useRegisterStep.ts
> +  const goPrev = () => {
구조 크게 변경하지 않고, 컴포넌트 클릭 이벤트로 `goPrev` 할당했습니다!

2023-07-12 12:45 UTC, HAEROOL commented on src/page/Auth/Signup/index.tsx
> +  } = useRegisterStep();
이 부분에서 고민을 좀 했었는데, 모바일에서 이메일 중복확인 - 비밀번호 입력 - 이메일 인증을 하는 과정에서 플로우의 전체 `step`이  `progress-bar`와 차이가 나서 실제 회원가입하는 step을 통일하려면 따로 모바일용 화면을 만들어야 할 것 같아, `progress-bar`에서 사용하는 `step`과 실제 회원가입 을 담당하는 `step`을 따로 관리하는 게 나을 것이라 생각하여 해당 방식을 사용했습니다.

2023-07-17 14:30 UTC, kimeodml commented on src/page/Auth/Signup/index.tsx
> +  } = useRegisterStep();
저도 step 부분에 대해서 한 번 다시 고려해 봐야겠네요

2023-07-17 14:35 UTC, kimeodml approved these changes
고생하셨습니다~

2023-08-16 08:20 UTC, ChoiWonBeen requested changes
고생하셨어요~~ 쩝박만든다고 너무 오랜만에 리뷰해서 다시 확인할부분들이 생긴것 같아 죄송합니다..ㅎ
몇가지 생각해볼만한 점들과 바꿀 부분들 작성해두었으니, 시간나실때 확인부탁드려요~~

2023-08-16 08:20 UTC, ChoiWonBeen commented on src/page/Auth/Signup/component/CustomButton/index.tsx
> +      type={submit ? 'submit' : 'button'}
submit이 아닌, type을 받아서 쓰는게 좋지 않나.. 라고 생각했는데, 이게 lint rule에 걸리네요? ㅋㅋㅋ

제가 생각했던 방식은, 아래처럼 button의 기본적인 props를 extends해 더욱 추상화된 버튼을 만들어야 한다고 생각했어요:
```ts
interface ButtonProps extends React.ComponentProps<'button'> { 
  type: 'submit' | 'reset' | button,
  // ...
```
다만 이렇게 만들 경우 `type` 이라는 프로퍼티에 한해 에러가 나오는데 세 가지 문자열에 대한 유니온으로 interface를 만들어도 린트는 에러로 처리하네요.
이와 관련된 [상당히 긴 이슈](https://github.com/jsx-eslint/eslint-plugin-react/issues/1555)를 읽어보니 lint rule을 무시하라는 결론으로 완료된 걸 보니, 아쉽지만서도 어쩔 수 없는 것 같네요 😓

2023-08-16 08:20 UTC, ChoiWonBeen commented on src/page/Auth/Signup/component/CustomButton/index.tsx
> +  buttonSize:string,
```suggestion
  buttonSize: 'small' | 'mobile' | 'large',
```
클래스에 맞게 작성해두는 게 좋아보이죠?!

2023-08-16 08:20 UTC, ChoiWonBeen commented on src/page/Auth/Signup/component/ErrorMessage/index.tsx
> +interface ErrorMEssageProps {
```suggestion
interface ErrorMessageProps {
```
오타발견했습니다~

2023-08-16 08:20 UTC, ChoiWonBeen commented on src/page/Auth/Signup/component/UserEmail/UserEmail.module.scss
> +  &__warn {
상태마다 다른 height을 갖게 되어 layout shift가 발생하는데 공통 높이를 갖는 조상을 만드는 방법은 어떠려나요??
<img width="899" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/50780281/a4c06e52-38a0-41e4-8790-275cc1bd4afb">

2023-08-16 08:20 UTC, ChoiWonBeen commented on src/page/Auth/Signup/component/UserPassword/index.tsx
> +          placeholder={isMobile ? '비밀번호' : '비밀번호 입력 (필수)'}
입력 도중에 정규표현식을 넘어가면 다음 입력으로 자동으로 넘어가지네요??
비밀번호가 `aaaa@1234` 라면, `aaaa@1` 에서 다음 input으로 포커스가 넘어가는 문제가 있어요!

2023-09-26 11:07 UTC, hanagertrudekim approved these changes

2023-09-27 08:30 UTC, MinGu-Jeong commented on src/page/Auth/Signup/component/UserPassword/index.tsx
수고하셨습니다!
궁금한 부분이 있어서 질문 한가지만 드리겠습니다.
현재 PC, 모바일 화면 모두 비밀번호 입력 후 비밀번호 확인으로 넘어갔을 때 비밀번호 확인```input```만 수정이 가능하고, 전에 입력했던 비밀번호```input```은 수정이 안되는데 의도하신 로직인지가 궁금합니다..!

2023-10-23 13:10 UTC, MinGu-Jeong approved these changes

2023-10-24 01:27 UTC, dooohun requested changes
수고하셨습니다!
다른 사람 코드를 보면서 배우는 게 많은 거 같습니다. 특히 zod를 사용하는 방법에 대해 많이 알아갑니다!!

코드 리뷰 많이 늦어서 죄송합니다... 다음에는 빠르게 코드리뷰 진행하도록 하겠습니다!

2023-10-24 01:27 UTC, dooohun commented on src/page/Auth/Signup/component/UserEmail/index.tsx
> +              <span className={styles['email-check__alert']}>* 제한시간 5 : 00</span>
이메일을 보내면 제한시간이 줄어드는 기능 구현이 필요해 보입니다!

2023-10-26 11:35 UTC, merged