Feature/#199
BCSDLab/KOIN_OWNER_WEB pull request #220
Opened 2024-03-29 12:23 UTC by junghaesung79

- Close #199 
  
## What is this PR? 🔍

- 기능 :
  1. userType에 따라 다른 url 이동
    * OWNER일 경우 / 로 이동
    * COOP일 경우 /coop 로 이동
  2. userType에 따라 정해진 url만 접근 가능
- issue : #199 

## Changes 📝

* 로그인 시 반환되는 userType을 전역 변수로 두었습니다.
* 예시 coop 페이지를 만들었습니다.(url 리다이렉트 확인 용도)

## ScreenShot 📷

<img width="611" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/96577250/bb2f2d0c-ff62-4e85-90f5-cbe54c1a3f88">

## Test CheckList ✅

- [x] ProtectedRoute에 따라 다른 url로 리다이렉트 확인

## Precaution

예시로 만들어낸 경로는 추후 페이지 담당자가 원하는 대로 수정하게 될 것입니다.
현재 백엔드의 stage 배포가 진행되지 않아서 coop 계정으로 테스트하는 것은 나중이 될 것입니다.

## ✔️ Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] Did you merge recent `develop` branch?

2024-03-30 07:15 UTC, ChoiWonBeen commented on src/layout/DefaultLayout/index.tsx
> +          setPrevPath('/shop-registration');
Route를 변수로 만들 필요가 있어보인다... 싶네요 ㅋㅋㅋ 쓰고있는 link쪽을 빼먹을 가능성이 있을듯

2024-03-30 07:16 UTC, ChoiWonBeen commented on src/App.tsx
> +  }
기존 사장님 로그인과 같은 API를 사용하기로 한건가여?

2024-03-30 07:17 UTC, MinGu-Jeong requested changes
수고하셨습니다!!
회원권한에 따른 예외처리 부분만 수정해주시면 될 것 같아요

2024-03-30 07:17 UTC, MinGu-Jeong commented on src/App.tsx
> +import CoopPage from 'page/\bCoopPage';
이 부분이 예시 경로인거죠?

2024-03-30 07:17 UTC, MinGu-Jeong commented on src/model/auth/index.ts
> +    z.literal('OWNER'),
오옹.. union 내부 문자열들은 string이 아니라 literal 타입인가 보네요?

2024-03-30 07:17 UTC, MinGu-Jeong commented on src/query/auth.ts
> +      } else;
유저타입이 `OWNER` `COOP`이 아닐 때 기존처럼 회원가입 페이지로 이동시킬 필요가 있어보여요

2024-03-30 07:20 UTC, ChoiWonBeen commented on src/App.tsx
> +    return <Navigate to="/login" replace />;
기존 사장님 페이지들도 자동로그인 하는 과정에서 userType store가 잘 들어가나요? (사장님 자동로그인에 문제가 없나요?)
전역으로 이 값을 set하는 과정이 있었는지 잘 모르겠네요

2024-03-30 07:20 UTC, junghaesung79 commented on src/App.tsx
> +  }
네 맞아요. /user/login POST 요청의 response에 있는 user_type에 COOP을 추가한 것을 이용해서 분기를 나눴어요.

2024-03-30 07:24 UTC, ChoiWonBeen commented on src/query/auth.ts
> +      setUserType(data.user_type);
로그인에서 주입되는군요. 자동로그인 잘 되나여?

2024-03-30 07:25 UTC, junghaesung79 commented on src/App.tsx
> +import CoopPage from 'page/\bCoopPage';
네 맞습니다. \b... 이상한 게 껴 있네요.. 수정하겠습니다.

2024-03-30 07:26 UTC, junghaesung79 commented on src/App.tsx
> +import CoopPage from 'page/\bCoopPage';
0135ea869a686a9222a40f1c02291d3553e2d3e0

2024-03-30 07:29 UTC, junghaesung79 commented on src/model/auth/index.ts
> +    z.literal('OWNER'),
z.~ 이런 식으로 쓰는 게 처음이여서 GPT의 도움을 받아 이렇게 작성하였습니다.😅

2024-03-30 07:30 UTC, junghaesung79 commented on src/App.tsx
> +    return <Navigate to="/login" replace />;
아 이 부분은 수정이 필요하네요. 감사합니다.
원래 DefaltLayout에서 자동 로그인을 하는데 그게 OWNER 안에 들어가 있네요. 수정하겠습니다.

2024-03-30 07:31 UTC, junghaesung79 commented on src/query/auth.ts
> +      setUserType(data.user_type);
수정하겠습니다!

2024-04-08 20:42 UTC, MinGu-Jeong commented
수정완료되면 Re-request review 부탁드려요🙏

2024-04-09 01:05 UTC, junghaesung79 commented on src/query/auth.ts
> +      } else;
넵 적용하였습니다!

2024-04-09 01:07 UTC, junghaesung79 commented on src/query/auth.ts
> +      setUserType(data.user_type);
기존에 DefaultLayout과 AuthLayout에 있던 리다이렉트 로직은 로그인 됨/안됨 두 가지 상태를 상정한 로직이여서 그 부분을 삭제하고 
루트와 리다이렉트 로직을 한 눈에 파악할 수 있도록 App 컴포넌트에서 모두 구현하였습니다.

2024-04-09 01:19 UTC, junghaesung79 commented on src/layout/DefaultLayout/index.tsx
> +          setPrevPath('/shop-registration');
확실히 경로들을 변수화하면 잘못된 경로로 navigate하는 것을 막을 수 있을 것 같아요..! 그런데 그렇게 바꾸고 나면 하나하나 정의를 찾아봐야 해서 다른 사람이 볼 때 이해하는 데 더 시간일 걸릴 것 같아요.(/owner/modify-menu/:menuId 이런 것도 표현하기 애매함) 그리고 경로를 변수화한다면 모든 경로들에 대해 적용할 텐데 한 두 번만 사용되는 경로도 필요이상으로 추상화하는 것이 아닌가 생각하게 되요. 만약에 이후에 변수화에 대한 필요성이 다시 또 나타나면 이슈화 고려해보겠습니다!

2024-04-09 01:38 UTC, junghaesung79 commented
지금 생협 계정으로 /coop 경로로 들어가면 로그아웃 버튼이 없어서 테스트에 번거로움이 있습니다. 그때 로그아웃하기 위해서는 로컬/세션스토리지의 리프레시, 액세스 토큰을 delete하시고 새로고침하시거나 /login 경로 쳐서 들어가면 됩니다!

2024-04-09 01:40 UTC, KimKyungYun reviewed
고생하셨습니다~ 궁금한점 간단하게 남겼습니다!

2024-04-09 01:40 UTC, KimKyungYun commented on src/layout/AuthLayout/index.tsx
> -import { Outlet, useNavigate } from 'react-router-dom';
해당 컴포넌트는 이제 AuthRoute로 부를만큼의 역할을 수행하지 않는 것 같은데, 추후 확장을 고려해서 남겨두신거로 보면 될까요??
그게 아니라면 다른 컴포넌트와 결합하거나 네이밍을 변경하면 좋지 않을까 싶습니다!

2024-04-09 01:40 UTC, KimKyungYun commented on src/query/auth.ts
> +  const { mutate, error, isError } = useMutation({
이부분은 단순히 제 궁금증인데, 로그아웃을 API를 통해 진행하는 이유가 뭐일까요??
클라이언트 측에서 로그인에 관한 정보를 모두 지운다면 로그아웃이 되는 것으로 생각하고있어서 이 부분은 어떤 API인가 궁금하네요!

2024-04-09 01:57 UTC, ChoiWonBeen commented on src/query/auth.ts
> +  const { mutate, error, isError } = useMutation({
서버에서 해당 refresh, accessToken을 invalid하게 변경하는 역할을 수행해요!

2024-04-09 01:59 UTC, ChoiWonBeen approved these changes
영양사, 사장님 각각 로그인과

서비스중인 url로 직접 진입시 자동로그인 후,원래 url로 리다이렉트만 잘 되는게 확인됐다면 늦지않게 병합해야할 것 같네여

2024-04-09 02:00 UTC, junghaesung79 commented on src/query/auth.ts
> +  const { mutate, error, isError } = useMutation({
오오 저는 단순히 함수 형태를 통일해서 다루기 편하도록하기 위해서 저렇게 만들었는데 서버에서는 그런 처리를 해주는 군요! 하나 알아갑니다👏

2024-04-09 02:02 UTC, junghaesung79 commented on src/layout/AuthLayout/index.tsx
> -import { Outlet, useNavigate } from 'react-router-dom';
App 컴포넌트 루트들에서 의미를 구분하는 데 도움이 되고 Copyright를 붙여주는 역할도 하고 있어서 그대로 두는 게 좋을 것 같아요. 말씀하신대로 확장의 가능성도 있구요.

2024-04-09 02:14 UTC, KimKyungYun approved these changes

2024-04-09 02:52 UTC, MinGu-Jeong approved these changes

2024-04-09 07:18 UTC, merged