[비밀번호 찾기] 비밀번호 찾기 UI 구현
BCSDLab/KOIN_OWNER_WEB pull request #24
Opened 2023-09-11 01:19 UTC by MinGu-Jeong

## [#22 ] request

* 비밀번호 찾기 페이지 UI를 구현했습니다.
* 아직 로직이 구현되지 않아 주소창에서 `find-password` `new-password` `complete-change-password` 로 직접 입력하여야 이동 가능합니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img alt="스크린샷 2023-09-11 오전 12 40 26" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/52fbf218-d199-40cf-8152-d40ee1ed938a" width="44%">
<img alt="스크린샷 2023-09-11 오전 12 40 33" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/8ba48e13-b9a7-489f-96e1-a60f4f78d6ef" width="50%">
<img alt="스크린샷 2023-09-11 오전 12 40 40" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/7b2d2510-244b-49c0-9440-ad3d29b89d78" width="50%">

### Precautions (main files for this PR ...)
* 추후 API가 구현되면 로직구현과 API연결 작업 진행하겠습니다.

2023-09-11 01:37 UTC, MinGu-Jeong commented
lint 에러 수정 후 다시 push하겠습니다.

2023-09-11 03:33 UTC, daepan requested changes
아무래도 혼자 일하다가 다른 사람들 코드 보니 뭔가 꼬치꼬치 캐묻는 것 같지만 답변 부탁드립니다 ^^

요번 프로젝트 보면서 클래스네임에서 ~~_~~ 요런 패턴은 코인 마이그레이션 하면서 거의 안썻었는데 많이 바뀌긴 했네요..
필요에 따라서는 직관적으로 보이기도 하지만,  __를 함께 활용하기에는 무리가 있는 부분들이 있으니 사용할 때 조심해야할 것 같습니다!

2023-09-11 03:33 UTC, daepan commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +            <div className={styles.send_container}>
send와 같은 동사가 클래스네이밍 앞에 있는건 조금.. 어쌕하긴 한데 요거는 auth나 다른 걸로 하면 어떨까요?
이렇게 하면 auth__~~ 식의 네이밍이 더 간편해질 것 같네요

2023-09-11 05:38 UTC, daepan commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +      <button type="button" className={styles.content__button}>로그인 화면 바로가기</button>
```suggestion
<div className={styles.content}>
      <div className={styles.content__title}>비밀번호 변경 완료</div>
      <div className={styles.content__description}>
        비밀번호가 변경되었습니다.
        <br />
        새로운 비밀번호로 로그인 부탁드립니다.
      </div>
      <button type="button" className={styles.content__button}>로그인 화면 바로가기</button>
      </div>
```

2023-09-11 07:04 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +// import { Outlet } from 'react-router-dom';
불필요한 주석이라서 제거했습니다. 26cb9e004c8e93541d7f86e37fce4ba4636d3e12

2023-09-11 07:35 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +            <div className={styles.send_container}>
다시 생각해보니 클래스가 보내다의 의미를 갖는것 보단 인증의 의미를 가지는게 더 나을거 같네요😀
다른 부분도 적절하게 수정했습니다! 6e4bd9e72cb9cda2363ac063ee972a6a0397db47

2023-09-11 10:32 UTC, hanagertrudekim requested changes
첫 ui 작업 수고많으셨습니다.
처음이라 bem 네이밍이 익숙하지 않으실텐데, 이 부분 유의해서 코멘트 달았으니 확인해주세요! 
(+block과 element 구분자인 언더바는 (__) 두개 입니다ㅎㅎ)

2023-09-11 10:32 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        <button type="button" className={styles.submit}>다음</button>
제출 버튼의 classname이`submit`이기보단  form 이라는 블럭 범주에 속하는 버튼이라는것을 명시하는것이 좋아보이는데 어떻게 생각하시나요?

2023-09-11 10:32 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              type="password"
css 코드를 살펴보니, `input`의 border을 아에 없애시고, div로 따로 감싸셨는데 이유가있나요?
충분히 `input`으로도 구현가능할것같아요. (+ label 과 input 사이에 `input__container`라는 블럭이 껴있어서 뭔가 구조상 어색하긴하네요... ㅎㅎ)

2023-09-11 10:32 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/NewPassword/NewPassword.module.scss
> +    cursor: pointer;
label에`cursor: pointer` 효과를 주신 이유가 있을까요??

2023-09-11 12:11 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        <span className={styles.password_tip}>* 특수문자 포함 영어와 숫자 조합 6~18자리</span>
다시 생각해보니깐 불필요한 분리였네요😅
form block의 하위요소로 수정했습니다! d1135701b5ecdc2795f6439c4ca55c1044296d3f

2023-09-11 12:27 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        <button type="button" className={styles.submit}>다음</button>
`submit` 역시 따로 분리하기보단 form 하위요소로 들어가는게 더욱 적절한 것 같습니다.
`form__submit` `form__button` `form__submit--button`중 `form__submit`이 가장 적절한 것 같아 해당 classname으로 수정했습니다. 0109b1227ca558f424e35049eb5f91fbc1b60761

2023-09-12 00:13 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              type="password"
`<Blind/>` 이름을 가진 svg 컴포넌트를 `input` 내부에 넣는 방법이 없어서 기존 `input`의 border를 없애고 `input_container`로 `input`과 `<Blind/>`를 감싸게 되었습니다.
혹시 더 좋은 방법이 있다면 알려주시면 감사하겠습니다!!

2023-09-12 00:18 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              type="password"
그리고 질문이 있습니다!
`input_container`의 원래 네이밍 의도는 `input-container` 였는데 `lint`룰 때문인지 정확히 모르겠지만 `-`가 뺄셈으로 인식되어 해당 네이밍을 사용할 수 없어 부득이 하게 `input_container`라는 이름으로 언더바를 한 개 사용하였습니다.
이 경우에도 BEM 네이밍컨벤션에 따라 언더바를 두 개 사용해야 할까요??

2023-09-12 00:26 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/NewPassword.module.scss
> +    cursor: pointer;
label에 효과를 주는게 적절하지 않았던 것 같습니다.
`<Blind/>` 컴포넌트에는 여전히 `cursor: pointer` 효과가 필요하기 때문에 별도의 `cursor_pointer`클래스를 만들어 적용시켜주었습니다! 5e2c46a1e35aacdad61d0a4fbbf580c45c29c178

2023-09-12 02:08 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              type="password"
1. 이건 제가 했던 방법인데, `input`안에 `padding-right`를 적절히 설정하고 `blind-icon`을  `position`속성의 `absolute` `relative`속성을 활용하여 고정하는 방법도 있습니다.
정답은 아닌지라 기존의 방법이랑 둘중에 선택하셔도 될것같아요.
(다만 지금 auto-complete 되었을때, 영역 선택이 조금 밀려서 그 부분은 수정이 필요할것같아요!)
2. 그런 경우엔 `styles['input-container']` 이런식으로 작성하면 해결할수있을거에요🙂

2023-09-12 04:37 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/NewPassword.module.scss
> +    cursor: pointer;
추가적으로 `cursor_pointer` 에서 `cursor-pointer`로 수정했습니다! d925c299ba4b42c31366e7529516830c50d7f10d

2023-09-12 11:22 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              type="password"
`form__input-container`로 클래스명 수정했습니다! d925c299ba4b42c31366e7529516830c50d7f10d

2023-09-12 14:07 UTC, daepan approved these changes
_ 패턴이 아니였군요 ㅎㅎ
앞으로 이런거 잡아내겠습니다.
고생하셨습니다

2023-09-13 02:07 UTC, dooohun approved these changes

2023-09-13 02:35 UTC, hanagertrudekim requested changes
수고하셨습니다ㅎㅎ
전체적인 수정사항들을 통일시키기만하면, 바로 머지해도 괜찮을것같아요 🙂

2023-09-13 02:35 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/SendAuthNumber/SendAuthNumber.module.scss
> +
```suggestion
    font-weight: 400;
    line-height: normal;
    box-sizing: border-box;

    &--auth{
    width: 255px;
    }
  }
```

`__input--auth`는 input안으로 넣어주셔도 될것같아요

2023-09-13 02:35 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +            <div className={styles.auth_container}>
모두 다 언급하지는 못하지만 😅   _ 로 className이 지어진것은 모두 수정이 필요할듯해요ㅎㅎ

2023-09-13 02:35 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +      </div>
`circle`만으로는 너무 추상적일수도있을것같아 `icon` 이라고 명시해주는것도 좋을것같아요!

2023-09-13 04:29 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +      </div>
`circle-icon`으로 수정했습니다! d53078449c147a20d04121549f1178e95bb1cbe2

2023-09-13 05:05 UTC, hanagertrudekim approved these changes
수고하셨습니다.

2023-09-13 05:41 UTC, merged