[가게 등록] 가게 등록 페이지 UI 구현
BCSDLab/KOIN_OWNER_WEB pull request #25
Opened 2023-09-12 14:13 UTC by dooohun

## [#9] request

* 가게 등록 페이지 UI 구현했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `deveop` branch?

### Screenshot
PC 버전
가게 등록 페이지 UI
![그림1](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/8c811664-7c7e-4997-8141-2f8833c014ac)
![그림2](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/22e8106d-2809-47f4-b2ac-b18d0cf109bc)
![그림3](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/c824c6bb-e4ec-440f-ba71-3f97a911362a)

가게 등록 페이지 모달
![그림4](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/397a95dc-7842-41b4-a5f7-18433d51de84)
![그림5](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/0436f7c8-5cda-4433-b261-52e2d7012c3e)
![그림6](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/0c425725-190e-4c7b-833e-6d3c55b32739)
![그림7](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/b178cc52-1b08-495e-a06a-75577f0b4c8b)

모바일 버전
![그림8](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/7b6cb4b3-50d7-40e1-a74d-552cd1963cf8)
![그림9](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/a1d0dd45-370e-468a-88c6-b0073e477661)

### Precautions (main files for this PR ...)

2023-09-14 05:58 UTC, MinGu-Jeong requested changes
수고하셨습니다!
다른 사람의 코드를 보는게 생각보다 쉽지 않아 리뷰 남기는데 시간이 좀 걸렸습니다😅
지금 남겨드린 코멘트와 별개로 지난번에 오프라인으로 말씀드린 부분도 수정해주시면 될 것 같습니다.
> PC화면과 모바일화면 전환시 STEP이 일치하지 않는 문제

2023-09-14 05:58 UTC, MinGu-Jeong commented on src/page/StoreRegistration/modal/SearchStore/index.tsx
> +          <div className={styles.storeList}>
class이름으로 `storeList`라는 `camel case`를 사용한 이유가 있나요?

2023-09-14 05:58 UTC, MinGu-Jeong commented on src/page/StoreRegistration/modal/Category/Category.module.scss
> +  &__nextbtn {
위의 다른 클래스명(`&__title-button`)과 일관성을 유지하기 위해 `&__next-button`이라는 이름이 더 좋을것 같습니다!

2023-09-14 07:44 UTC, dooohun commented on src/page/StoreRegistration/modal/SearchStore/SearchStore.module.scss
> +  height: 838px;
height를 vh로 수정하겠습니다!

2023-09-14 07:45 UTC, dooohun commented on src/page/StoreRegistration/modal/SearchStore/index.tsx
> +          <div className={styles.storeList}>
잘못 작성한 것 같습니다. 수정하도록 하겠습니다!

2023-09-14 07:47 UTC, dooohun commented on src/page/StoreRegistration/modal/Category/Category.module.scss
> +  &__nextbtn {
전체 코드의 클래스명에 대해 빠르게 수정하도록 하겠습니다!
일관성 유지에 대해 더욱 신경 쓰도록 하겠습니다

2023-09-14 07:57 UTC, hanagertrudekim requested changes
수고하셨습니다!
코드량이 굉장히 많네요... ㅎㅎ 리뷰한것들 한번씩 확인해주세요! 

일단 공통적으로 리뷰하고싶은 부분은

1. 비슷한 구조의 모달 컴포넌트들이 많이 추가되었는데, 공용적인 모달 컴포넌트를 하나 만들어서 재사용해도 될것같아요.  `common` 쪽에 추가해서 추가적으로 모달이 필요한 곳에도 사용할수있도록 하면 더 좋구요.
그리고, 다음 버튼을 눌렀을때 모달이 닫히지 않는데, 이부분은 아직 덜 구현된 기능인가요?

2. 클래스네임을 전체적으로 통일시켜주세요!

3. 어디서 찾아야하는지 모르겠어서 여기다가 코멘트하지만, <img width="367" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101982606/a9f27696-373f-4996-a07e-d352f5f678c8">
PM과 AM 글자가 다 안나오는데, 해당 문제를 해결할 방법이 있을까요?

2023-09-14 07:57 UTC, hanagertrudekim commented on src/page/StoreRegistration/modal/OperateTime/index.tsx
> +              </tr>
이런건 반복문으로 돌리면 더 깔끔해질것같아요!

2023-09-14 07:57 UTC, hanagertrudekim commented on src/page/StoreRegistration/modal/OperateTime/index.tsx
> +  onClose: (event: React.MouseEvent<HTMLButtonElement>) => void;
`onClose`는 무슨 함수인지 알수있을까요?

2023-09-14 07:57 UTC, hanagertrudekim commented on src/page/StoreRegistration/modal/SearchStore/index.tsx
> +            <Magnifier />
'cursor: pointer` 효과가 있음 좋을것같아요. 아래 store을 선택할때도 해당 효과가 필요할것같아요.

2023-09-14 09:58 UTC, dooohun commented on src/page/StoreRegistration/component/Complete/index.tsx
> +}: CompleteProps) {
기존에 작성했던 `Complete` 컴포넌트의 글씨가 원하는 모양대로 나오지 않아서 따로 재정의했습니다.
글자 수가 길어지면 글자가 넘어가서 이 부분에 대해 width를 수정했습니다.
필요하면 기존의 코드를 수정해도 괜찮나요?

2023-09-14 09:59 UTC, dooohun commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +
넵 알겠습니다!
궁금한 점이 있는데 그럼 import를 따로 구분 짓는 기준이 있나요?

2023-09-14 10:00 UTC, dooohun commented on src/page/StoreRegistration/modal/OperateTime/index.tsx
> +              </tr>
넵 알겠습니다!

2023-09-14 10:07 UTC, dooohun commented on src/page/StoreRegistration/modal/OperateTime/index.tsx
> +  onClose: (event: React.MouseEvent<HTMLButtonElement>) => void;
onClose는 `page/storeRegistration/view/StoreInfoRegistration` 에 있는 toggleModal 함수 입니다.
주요 기능으로는 여러 모달 중 클릭한 모달의 열고 닫힘을 관리합니다.

지금 보니까 onClose라는 변수명은 뜻 전달이 안되는 것 같아 보이네요... 다른 변수명으로 수정하겠습니다.

2023-09-14 10:07 UTC, dooohun commented on src/page/StoreRegistration/modal/SearchStore/index.tsx
> +            <Magnifier />
넵 알겠습니다! 해당 부분 수정하겠습니다.

2023-09-14 10:23 UTC, hanagertrudekim commented on src/page/StoreRegistration/component/Complete/index.tsx
> +}: CompleteProps) {
width만 제한된다면, 이부분에 대해서는 수정이 필요할것같아요. 공통으로 들어가는 컴포넌트면 좀 더 범용성있게 기존 코드를 수정하면 좋을것같습니다!

2023-09-14 10:26 UTC, hanagertrudekim commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +
따로 정해둔 기준은 없습니다 ㅎㅎ (딱히 필요성이 없어서 정하지않은것같아요)

2023-09-14 13:04 UTC, dooohun commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +
8ae771121867008ab8a1fb1be0aad8be665d49b9 icon import의 구분을 삭제했습니다!

2023-09-15 03:03 UTC, dooohun commented on src/page/StoreRegistration/component/Complete/index.tsx
> +}: CompleteProps) {
1c17b19577a6a0227dd853792163498ef51aaa90 `component/common/Auth`의  `Complete` 컴포넌트 width, height 수정했습니다. 
e4f45f2052bf80e44c3c5a56329930b81961c13b 기존에 작성했던 컴포넌트는 삭제했습니다!

2023-09-15 03:24 UTC, dooohun commented on src/page/StoreRegistration/modal/SearchStore/index.tsx
> +            <Magnifier />
cursor:pointer 효과 추가했습니다! 50351cf4495f5f900985b866ee2ad29b68e37815

2023-09-15 05:19 UTC, dooohun commented on src/page/StoreRegistration/modal/OperateTime/index.tsx
> +  onClose: (event: React.MouseEvent<HTMLButtonElement>) => void;
onClose 함수명을 modalHandler로 변경하였습니다! 47d79a34e27271a8ea7533485c093c3aa0fbd209

2023-09-16 14:06 UTC, dooohun commented
> 수고하셨습니다! 다른 사람의 코드를 보는게 생각보다 쉽지 않아 리뷰 남기는데 시간이 좀 걸렸습니다😅 지금 남겨드린 코멘트와 별개로 지난번에 오프라인으로 말씀드린 부분도 수정해주시면 될 것 같습니다.
> 
> > PC화면과 모바일화면 전환시 STEP이 일치하지 않는 문제

PC 화면과 모바일 화면 전환 시 STEP이 일치하지 않는 문제 해결 했습니다! 2e3f61d9555128758de83001e5a5bb3d752d5bfc
모바일의 메인 정보 입력, 세부 정보 입력은 로직 구현 후 구체적으로 구현하도록 하겠습니다.

2023-09-18 14:27 UTC, dooohun commented
> 수고하셨습니다! 코드량이 굉장히 많네요... ㅎㅎ 리뷰한것들 한번씩 확인해주세요!
> 
> 일단 공통적으로 리뷰하고싶은 부분은
> 
> 1. 비슷한 구조의 모달 컴포넌트들이 많이 추가되었는데, 공용적인 모달 컴포넌트를 하나 만들어서 재사용해도 될것같아요.  `common` 쪽에 추가해서 추가적으로 모달이 필요한 곳에도 사용할수있도록 하면 더 좋을것같습니다.
>    그리고 다음 버튼을 눌렀을때 모달이 닫히지 않는데, 이부분은 아직 덜 구현된 기능인가요?
> 2. 클래스네임을 전체적으로 통일시켜주세요!
> 3. 어디서 찾아야하는지 모르겠어서 여기다가 코멘트하지만,
> 
> <img alt="image" width="367" src="https://user-images.githubusercontent.com/101982606/267899356-a9f27696-373f-4996-a07e-d352f5f678c8.png">
> PM과 AM 글자가 다 안나오는데, 해당 문제를 해결할 방법이 있을까요?

1. `common`쪽으로 모달의 폴더 위치를 수정했습니다. 그리고 다음 버튼 눌렀을 때 모달이 닫히지 않는 기능 추가했습니다. 1f2ef8f5824c755fa95aca59f33aac399c65dc3e 

2. 클래스네임 수정 완료했습니다. 4ee10d22c613a59b624563b9b8c640f847977ac0
3. 해당 오류를 수정하려고 많이 찾아보았는데 `<input type="time" />` 의 숫자 혹은 문자 접근하는 방법에 대해 찾아보았지만 결국 찾지 못했습니다. 그래서 `<input type="time" />`을 대체하기 위해서 `TimePicker`라는 컴포넌트를 만들었습니다.
dc6e886dbf8a32a1fd429b45086a793e053fcc94

2023-09-18 15:51 UTC, kimeodml reviewed
남의 코드 이어서 하는 게 가장 어려운데 고생하셨습니다!

2023-09-18 15:51 UTC, kimeodml commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
eslint 예외 처리의 경우 가급적이면 최상위에 표시해 주세요!

2023-09-18 15:51 UTC, kimeodml commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +            <form className={styles.form}>
`form`태그나 `div`태그를 동시에 쓰고 있는데 보통 이 경우에는 `label`태그와 `input`을 함께 사용하는 것을 추천합니다! 또한 form을 중첩해서 사용해서 현재 오류가 생기고 있습니다.
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/2180acb6-4db1-410a-b8a9-57687ea0192e)

2023-09-18 15:51 UTC, kimeodml commented on src/component/common/Modal/Category/index.tsx
> +
`const { categoryList } = useStoreCategory();`를 활용해서 카테고리 이미지 추가 가능해 보여요.

2023-09-18 15:51 UTC, kimeodml commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +    <form className={styles.form}>
`form` 태그 대신 `label` 태그 추천 드립니다!

2023-09-18 15:51 UTC, kimeodml commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +              </div>
요 부분이 빠졌습니다.
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/88065770/ae92cfde-0a16-4221-aa3f-22bb54021f3e)

2023-09-18 15:51 UTC, kimeodml commented on src/page/StoreRegistration/component/TimePicker/TimePicker.module.scss
> +  left: 0;
요건 제 취향인데 left값 없이 그냥 중앙에 표시되는 것도 괜찮아 보여요..!ㅎㅎ

2023-09-19 10:45 UTC, daepan requested changes
학교 공부와 같이하면서 고생하셨네요
네이밍에 대한 하나 적어두었으니 참고가 되셨으면 좋겠습니다.
수고하셨습니다.

2023-09-19 10:45 UTC, daepan commented on src/component/common/Modal/OperateTime/index.tsx
> +
WEEK라는 상수 네이밍을 지켜주세요
static 폴더에 둬야할 것 같습니다.

2023-09-19 10:45 UTC, daepan commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +}
```suggestion
const hours: number[] = Array.from({ length: 24 }, (_, i) => i);
const minutes: number[] = Array.from({ length: 60 }, (_, i) => i);
```
쓸데없이 길어보이니 하나로 보는게 좋아보입니다.

2023-09-20 08:15 UTC, dooohun commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +            <form className={styles.form}>
`form`을 중첩 사용 에러는 `div` 태그로 수정하여 해결했습니다. 4e827bf2e9c8b890f3ec076b006e4a2a5820e1f8

2023-09-20 08:27 UTC, dooohun commented on src/component/common/Modal/Category/index.tsx
> +
기존에 있던 코드를 참고해서 기능 추가했습니다! cffc2377a9a0ba415aa300737e48289b3b3023a1

2023-09-20 08:42 UTC, dooohun commented on src/page/StoreRegistration/view/StoreInfoRegistrationPage/index.tsx
> +              </div>
앗 체크박스 구현하려고 했었는데 까먹고 있었네요... 감사합니다!
체크박스 UI 추가했습니다! 55ecb8ffdc6f4b240daa1fdb532c3692b8429309

2023-09-20 08:47 UTC, dooohun commented on src/page/StoreRegistration/component/TimePicker/TimePicker.module.scss
> +  left: 0;
비교해보니까 중앙에 표시되는게 더 좋은 거 같네요!! 수정했습니다 b0888eda52a7e13f3d80e46f612f750e985b7b97

2023-09-20 08:50 UTC, dooohun commented
> 남의 코드 이어서 하는 게 가장 어려운데 고생하셨습니다! 추가적으로 TimePicker의 분단위는 5분 단위로 구분하는 것은 어떨까요?

5분으로 수정하는게 사용자 입장에서 훨씬 보기 좋은 거 같습니다! TimePicker 분 단위를 5분 단위로 수정했습니다. 1dab71d6d74c25394f622b07351418a35a707810

2023-09-22 09:28 UTC, dooohun commented on src/component/common/Modal/Category/Category.module.scss
> +    height: calc(78px - 48px);
패딩 값을 설정하고 그 값을 빼주기 위해 calc 함수를 사용했습니다.
잘 모르고 사용했던 거 같습니다. 
a6f823000c1d06e1e99841492ea23073aef3b3bb (코드의 전체 구조를 바꾸다 보니 수정한 내용 중 일부분만 커밋 되어 있습니다... 정말 죄송합니다 ㅜㅜ)

2023-09-22 09:35 UTC, dooohun commented on src/component/common/Modal/ConfirmPopup/index.tsx
> +export default function ConfirmPopup({ isOpen, modalHandler }: ConfirmPopupProps) {
모달과 팝업 차이점에 대해 잘 몰랐었는데, 새로운 정보를 알아가네요
ConfirmPopup에 `modal`로 작성한 부분을 `popup`으로 일괄적으로 수정했습니다.
e931b985c67e81defda7ce708e6b455451fb0510 178551ecb8e657248cb994b51ec813caeec7d9dd

2023-09-22 09:35 UTC, dooohun commented on src/component/common/Modal/OperateTime/index.tsx
> +
패딩 값을 설정하고 그 값을 빼주기 위해 calc 함수를 사용했습니다.
잘 모르고 사용했던 거 같습니다. 
a6f823000c1d06e1e99841492ea23073aef3b3bb (코드의 전체 구조를 바꾸다 보니 수정한 내용 중 일부분만 커밋 되어 있습니다... 정말 죄송합니다 ㅜㅜ)

2023-09-22 09:39 UTC, dooohun commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +}
for 반복문을 버릇처럼 쓰다보니 위와 같이 작성한 거 같습니다.
좀 더 코드를 줄이기 위해 고민하고 작성하도록 하겠습니다! 좋은 리뷰 감사합니다 1dab71d6d74c25394f622b07351418a35a707810

2023-09-22 09:50 UTC, dooohun commented
@hanagertrudekim 

- 공용적인 모달 컴포넌트를 하나 만들어서 재사용하도록 만들었습니다. `common` 폴더에 `CommonModal` 이라는 폴더명으로 만들었습니다. bd7edbd5b1c8e5b8cb6461f6caaee0629c6967b9
- category, operateTime pc 버전을 구현했습니다. useBoolean 훅을 사용해 모달의 열고 닫힘을 구현하였습니다. 0cfac5c3fb739f8b546b0b2f327efb3fd88ac7a4
- 파일 구조를 수정하였습니다. 파일 구조는 `page/StoreRegistration/view`에 모바일과 PC 버전을 분리해 놓았습니다. 0cfac5c3fb739f8b546b0b2f327efb3fd88ac7a4

2023-09-23 10:07 UTC, hanagertrudekim commented
> * 공용적인 모달 컴포넌트를 하나 만들어서 재사용하도록 만들었습니다. `common` 폴더에 `CommonModal` 이라는 폴더명으로 만들었습니다. [bd7edbd](https://github.com/BCSDLab/KOIN_OWNER_WEB/commit/bd7edbd5b1c8e5b8cb6461f6caaee0629c6967b9)
> * category, operateTime pc 버전을 구현했습니다. useBoolean 훅을 사용해 모달의 열고 닫힘을 구현하였습니다. [0cfac5c](https://github.com/BCSDLab/KOIN_OWNER_WEB/commit/0cfac5c3fb739f8b546b0b2f327efb3fd88ac7a4)
> * 파일 구조를 수정하였습니다. 파일 구조는 `page/StoreRegistration/view`에 모바일과 PC 버전을 분리해 놓았습니다. [0cfac5c](https://github.com/BCSDLab/KOIN_OWNER_WEB/commit/0cfac5c3fb739f8b546b0b2f327efb3fd88ac7a4)

개인적으로 지금 분리한 공용 모달 컴포넌트만 봐서는 이점을 잘 못느끼는것같아요. 
모달 컴포넌트를 분리해서 그곳에서 또 공용모달 컴포넌트를 정의해야하는 구조보다는, 그냥 안의 content만 따로 분리하고 index쪽에서 합치는것도 좋아보입니다.
아래 예시처럼 `CustomModal`을 좀 더 상위에서 바로 조작할수있고, 그 안의 content를 따로 유지보수할수있는 구조가 적절할거같은데, 어떻게 생각하시나요?

```js
<CustomModal
          buttonText="생성"
          title="등록하기"
          width={900}
          footer={null}
          open={isModalOpen}
          onCancel={closeModal}
          onClick={openModal}
        >
          <ModalContent Props={...Props} />
        </CustomModal>
```

2023-09-25 10:40 UTC, daepan commented on src/component/common/Modal/OperateTime/index.tsx
> +
제가 말한 static은 루트폴더에 있는 static이긴 했습니다. 전역 상수 세팅을 하려고 생각을 했었는데, constant가 따로 있었군요.
요번 프로젝트에서 static이 사용되는 부분에 있어서 혼동이 있었나 봅니다.
정확히 말씀드리면 static은 클래스를 사용하는 자바에서 주로 사용하는 방법의 변수활용에 많이 사용되는 용어이고, 제가 지금까지 작성해본 프로젝트에서 static에는 변수보다는 파일을 담는 경우가 많습니다.
물론 이건 제가 경험한 것이고 팀에서의 컨벤션을 따르는게 원칙이라고 생각합니다.
그래서 루트 폴더의 static에 넣어두자는 의견이였습니다.
지금 프로젝트를 다시 읽어보니 static보다는 constant 폴더가 있었군요?
또한 루트 폴더에 있는 constants에 제가 보고 있던 브런치에서는 아무것도 없는데 이건 그냥 지워두는게 좋을 것 같고 utlils/constants를 두는게 저는 가독성이 더 높다고 생각합니다.

만약 폴더 내에서만 WEEK라는 상수를 사용할 것이라면 static이라는 네이밍 대신 constant가 어울릴 것 같네요.

여기서 제가 제시하고 싶은 행동은 아래와 같습니다.
1. 지금 생성한 static 폴더의 네이밍을 constant로 변경해서 사용한다.
2. static으로 사용 중인 내용을 constant로 일관적이게 통일한다.
3. 원래있던  constants를 제거하고 변경된 constant 파일을 utils에 넣는다.

컨벤션이 아직 지정되지 않았다면 위와 같은 방법을 추천드리고, 아닌 경우라면 1번만 하셔도 좋습니다.
나머지는 화요일날 회의때 추가적인 논의를 하면 좋을 것 같습니다.

2023-10-02 08:17 UTC, dooohun commented on src/component/common/Modal/OperateTime/index.tsx
> +
기존에 있던 static을 constant로 수정하고 `utils/constant`로 폴더 위치 이동하여 전역 상수 세팅을 완료했습니다. 
f526812f336f5bb5a1f9bb1b425d75a310d4c6c7 ac68eb8c26fe1c43227df800823acb1ff4351e28  e86309ebf99db7a6c017d10cdb919801c1b1a9d2

2023-10-02 08:20 UTC, dooohun commented
@hanagertrudekim 
`CustomModal`의 파라미터를 새로 추가하고, content만 따로 분리하고 index쪽에서 합치도록 구조를 변경했습니다. 909f5a00bbdacd4015f6a442030c152e4dbd23e0

2023-10-03 15:20 UTC, hanagertrudekim requested changes
수고 많으셨습니다ㅎㅎ

파일분리가 깔끔하게 정리되어 한눈에 알아보기 좋은것같아요 👍
`CustomModal` 도 여러가지로 고민하신부분이 잘 반영되어 앞으로 유용하게 활용할것같네요. 
 정말 마지막으로 간단한 수정사항들 확인해주세요! 해결되면 바로 머지시켜도 될것같아요ㅎㅎ

2023-10-04 16:59 UTC, ChoiWonBeen reviewed
@dooohun 에게 처음으로 다는 리뷰인만큼 정성을 드음뿍 담았으니 천천히는 말고 적당히 빠르게 확인해주세요 ㅎ
모든 리뷰를 전부 수락할 필요는 없고, 필요한 부분들은 다음 PR로 넘겨서 텐션이 떨어지는걸 방지하는 것도 능력이예요! (다른사람들도 리뷰 스크롤 내리느라 힘들듯 ㅋㅋㅋㅋ)

동시에 가르쳤던 분들(@MinGu-Jeong @hoooooony @LUNA-KK @allOfCoder)도 한번씩 읽어보면 좋을 내용들이 많으니 질문있으면 여기다라도 마구마구 달아줘여. 

레귤러된지 한 달 정도 넘은 것 같으니 화이팅들 하시고! 
제일 정신없을 시기는 지났지만, 아직은 컨벤션 지키기가 시간을 끄는 구간이니 가속을 붙인다는 생각으로 텐션 떨어지지 않게 유지해보세요 ㅋㅋ

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +import { ReactComponent as EmptyImgIcon } from 'assets/svg/storereg/mobile-empty-img.svg';
상위폴더명은 `StoreRegistration`, asset은 `storereg`인데, 통일되지 않을 이유는 없어보여요.
프론트엔드 도메인에서 reg << 는 보통 RegExp를 말하니 더 헷갈렸네요

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +  const [selectedCategory, setSelectedCategory] = useState('');
명확한 타입으로 쓰는 건 어떨까요?
`<Category | null>` 처럼 쓰면 좋을 것 같은 느낌이 오네요 👀

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
한 파일에서 추상화 단계가 맞지 않아 전체적인 코드 파악이 어렵게 느껴지는 것 같아요.
여기 [알맞은 강의](https://youtu.be/edWbHp_k_9Y?t=1052)가 있으니 참고해보시는것도?

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
categories를 길이 1로 slice를 했는데 map을 쓰는 문장이 이상하다 느껴져요

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +                  <img className={styles.category__image} src={value.image_url} alt="category_img" />
alt를 쓸 때는 해당 이미지가 그 자체로서의 의미가 있는지를 생각해야해요.
스크린리더로 해당 노드에 접근할때, 과연 "카테고리 이미지" 라는 문장이 어떤 의미를 가질 수 있을까요?
적절한 `aria-hidden` (혹은 `alt=""`)은 오히려 가독성에 도움을 준답니다

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +          <ProgressBar step={step - 1} total={TOTAL_STEP} progressTitle={PROGRESS_TITLE} />
`PROGRESS_TITLE`과`topTitle`은 많이 다른가요? 아래 title은 상수로 있는 이유가 무엇인가요?

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +  const { step, setStep, decreaseStep } = useStepStore();
마이너하지만, `decrease`가 있으니 `increase`를 쓰고 `onClick={increaseStep}` 처럼 깔끔할 것 같다는 생각도 드네여

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/index.tsx
> +  const { value: showConfirmPopup, setValue: setShowConfirmPopup } = useBooleanState(false);
state, setState만을 사용한다면 `useBooleanState`같은 훅으로 추상화해서 쓰는게 어떤 강점을 가질까요?

**boolean이니깐 써야한다**와 같은 생각보다는,`setTrue, setFalse, toggle`과 같은 반복되는 기능들을 선언적으로 사용하기 위해 써야 한다고 생각해요. 

`setShowConfirmPopup(!showConfirmPopup)` 을 써야한다면,
그냥 `toggleConfirmPopup()` 처럼 쓰는게 선언적이라는 것이 이 훅의 목적이라고 봐도 될 것 같아요

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/index.tsx
> +                footer={!null}
이것은 무슨 의미인가요? ㅋㅋㅋㅋㅌ

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/utils/constant/week.ts
> +const WEEK: string[] = ['월', '화', '수', '목', '금', '토', '일'];
타입스크립트를 조금 더 자세히 적용한다면 드릴만한 팁은,

1.`string[]` 로 타입을 정의하지 않았어도 알아서 추론되었을거라 불필요합니다.
2. 정의한다면 `WEEK[i]` 는 `string`이 아닌 `'월' | '화' | '수'...` 로 추론될 수 있도록 `as const`를 붙여주면 더욱 변수명에 맞는 타입을 가질 수 있어요
```suggestion
const WEEK = ['월', '화', '수', '목', '금', '토', '일'] as const;
```

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/Modal/OperateTimeMobile/index.tsx
> +                    <TimePicker />
마이너한 팁이예요 ㅎ
```suggestion
                    <TimePicker />
                    {' ~ '}
                    <TimePicker />
```

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/Modal/OperateTimePC/index.tsx
> +              <TimePicker />
근데 여기는 띄어쓰기가 없네요? UI가 다른감

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/component/common/CustomModal/index.tsx
> +        )}
의견을 좀 붙이자면, 
footer를 지금 쓰인 인터페이스대로 쓸 때는 - footer props로 React Element를 담고, 모달 내에서는 `{footer}` 처럼 쓰는 방법이 더 적절했을거예요(footer가 그만큼 자주 바뀐다면).
타입도 optional로 받아서 null을 초기값으로 추는 것도 가능하죠.
근데 쓴 코드만 봐서는 `hasFooter` 정도의 boolean props로만 고쳐도 괜찮을 것 같아요.

그럼 `footer={!null}`같은 의미심장한 부분도 같이 없어지겠죠? ㅋㅋㅋ

2023-10-04 16:59 UTC, ChoiWonBeen commented on src/component/common/CustomModal/index.tsx
> +  const buttonTexts = buttonText || ' ';
마이너한 팁입니다22 ㅎ
```suggestion
  buttonText = '', title, height, footer, open, onCancel, children,
}: CustomModalProps) {
```

2023-10-04 17:01 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +  const { step, setStep, decreaseStep } = useStepStore();
`TOTAL_STEP`이 `stepStore`가 아니라 여기서 관리되는 것도 어색해보이기도 하네요

2023-10-04 17:05 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/ConfirmPopup/index.tsx
> +  if (!isOpen) return null;
모달이 모달 내부에서 열렸는가를 알 필요가 없어보여요. (modal ui의 관심사와는 거리가 멀죠)
isOpen을 밖에서 관리하고 있으니 밖에서 조건문으로 간단하게 작성해두는게 어떨까요?

2023-10-04 17:10 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/ConfirmPopup/index.tsx
> +        <span className={styles['content__bottom-text']}>&apos;확인&apos;을 누르면 입력하신 내용으로 가게 정보가 등록됩니다.</span>
&apos;로 써야만 나오나요?
개인적으로는 {'확인'}을 누르면 처럼 쓰는게 가독성이 좋을 것 같아요 ㅋㅋ apos가 뭔지 보고왔네요

2023-10-04 17:11 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +export default function InputBox({ content, inputId }: InputProps) {
input의 props니 그냥 id라고만 작성해도 의미가 온전히 전달될 것 같아요.

2023-10-04 17:14 UTC, ChoiWonBeen commented on src/utils/constant/week.ts
> +const WEEK: string[] = ['월', '화', '수', '목', '금', '토', '일'];
그리고 이 프로젝트 zod를 쓰고있지 않았나요? `z.enum` 이나 `literal`같은 메소드들이 많으니 이런 쪽도 같이 확인해보면 좋을 것 같아요 ㅎ

2023-10-04 17:17 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/StoreRegistrationPC.module.scss
> +      background-image: url("../../../../assets/svg/storereg/mobile-checked.svg");
svg를 backgroundImg로 쓰면 svg로서의 가치가 없어진다고 생각해요!
svg를 왜 썼을까요?

2023-10-04 17:18 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/StoreRegistrationPC.module.scss
> +      background-image: url("../../../../assets/svg/storereg/mobile-checked.svg");
추가적으로 fill, stroke같은 css를 참고해보시면 더욱 이해될 것 같아요

2023-10-04 17:19 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +                  && createPortal(<OperateTime clickEvent={setShowOperateTime} />, document.body)}
다른애들은 이런 코드가 Modal로 따로 분리되어서 내부적으로 관리되었던것같은데 이것도 추상화 통일성이 다르다고 느껴지는 부분이예요

2023-10-04 17:20 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +                onClick={handleTimeChange}
click 이벤트에 change 핸들러를 달아놔서 타입 정의가 이상해졌을 것 같아요

2023-10-04 17:22 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +  function handleTimeChange(e: any) {
바로 위 리뷰를 달고 확인해봤는데 any라서 문제가 없었나보네요. any는 최~~대한 쓰지 말아주세요오
```suggestion
  function handleTimeChange(e: ChangeEvent<HTMLInputElement>) {
```

그런데 button의 click이벤트에 담은 핸들러인데 어떻게 `e.target.value` 를 갖는거죠?

2023-10-05 12:12 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
`shop_categories`의 첫 번째 값이 `전체보기` 카테고리인데 필요없는 값이라서 첫 번째 값을 제외한 배열이 필요해서 위와 같이 작성했습니다.
문장이 이상하다면 `전체보기`를 제외한 배열을 새로 만들어서 작성해야 하나요?

2023-10-05 13:38 UTC, dooohun commented on src/component/common/CustomModal/index.tsx
> +        )}
`hasFooter` boolean props로 수정했습니다! 71046fd566fd0d32cf8c4964d0c663b32c5ad544

2023-10-05 13:57 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
array.filter() 등의 메소드로 작성했다면 더욱 쉽게 이해할 수 있었겠죠?
"전체보기를 제외한 카테고리들을 반복한다"가 목적이었으니, 그렇게 읽히도록 작성하면 좋았을 것 같아요.

1번째가 전체보기로 통일되었다는 점은 아무래도 도메인에 대한 지식이다보니 코드를 보면서 파악하긴 힘들것같아용

2023-10-07 08:41 UTC, dooohun commented on src/page/StoreRegistration/component/ConfirmPopup/index.tsx
> +        <span className={styles['content__bottom-text']}>&apos;확인&apos;을 누르면 입력하신 내용으로 가게 정보가 등록됩니다.</span>
처음에 `{'확인'}` 으로 작성하려고 했는데 eslint에서 에러가 발생해서, 찾아보니 `&apos;`를 사용하면 된다고 써있어서 위와 같이 작성했습니다.

`{'확인'}`으로 작성하기 위해서는 eslint를 무시하도록 설정해야하는데, 이런 상황이 발생할 때마다 eslint를 매번 무시해도 괜찮은가요? 그리고 eslint 무시와 관련된 기준이 있는지 궁금합니다!

2023-10-07 14:00 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/ConfirmPopup/index.tsx
> +        <span className={styles['content__bottom-text']}>&apos;확인&apos;을 누르면 입력하신 내용으로 가게 정보가 등록됩니다.</span>
린트는 깔끔하게 하자는 규칙 정도니 지킨다거나 한번쯤 무시한다고해서 문제가 되진 않는데,
근데 그냥 `'확인'을 누르면 ..` 으로 안되나요? 이게 린트에 걸릴 것 같진 않는데
걸린다면 그냥 그대로 유지해도 괜찮을거예요 ㅋㅋ

2023-10-08 02:36 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +import { ReactComponent as EmptyImgIcon } from 'assets/svg/storereg/mobile-empty-img.svg';
폴더명 StoreRegistration으로 수정했습니다! b09719616e259f67edc4a7264a747884d029e412

2023-10-08 02:40 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
`SubTitle`, `ProgressBar`는 높은 추상화 단계이기 때문에, 높은 추상화 단계로 코드를 수정했습니다.
`page/StoreRegistration/view/mobile`에 step 별로 컴포넌트를 나누어서 코드를 작성했습니다. e3862028f5f9dfb1d8547251707b2aeb2726b758

2023-10-08 05:46 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +  const { step, setStep, decreaseStep } = useStepStore();
`increase`를 써서 다음 스텝으로 넘어가도록 수정하였습니다.
`increase`와 `TOTAL_STEP` stepStore에 추가하였습니다!
500c844058254316862de4a8ae17dd3f95961588

2023-10-08 05:52 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +  const { value: showConfirmPopup, setValue: setShowConfirmPopup } = useBooleanState(false);
`useBooleanState` 훅을 어떤 목적으로, 왜 사용해야 하는지를 생각하지 않고 코드를 작성했던 거 같습니다.
다음에는 코드의 목적과 사용 의도를 생각하며 코딩하도록 하겠습니다!!!
c6c9554af9b450c679e684637805ea08835c1519

2023-10-08 05:54 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +              </span>
처음에 `<br />` 태그를 사용하려고 했는데 글자 간격이 너무 좁아서 사용하지 않았습니다.
찾아보니 line-height를 통해 이 부분을 조절할 수 있었습니다.
c6c9554af9b450c679e684637805ea08835c1519

2023-10-08 05:56 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +                onCancel={() => setShowCategory(false)}
코드 수정했습니다! c6c9554af9b450c679e684637805ea08835c1519

2023-10-08 06:01 UTC, dooohun commented on src/page/StoreRegistration/view/PC/StoreRegistrationPC.module.scss
> +      background-image: url("../../../../assets/svg/storereg/mobile-checked.svg");
checked 되었을 때 모양을 구현하는게 어려워서 svg를 통해 구현했습니다.
구글링하다 보니 `background-clip`이라는 속성이 있어 `padding`과 함께 작성하여 원하는 모양의 체크박스를 만들었습니다.
b5823e8eec3a8a37dcd64b80b5c83d3fa3eaa854

2023-10-08 06:04 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/OperateTimePC/index.tsx
> +              <TimePicker />
띄어쓰기를 추가하지 않은 것 같습니다... 수정 완료했습니다!
d0a912baa3f238ec604f31c69f504135ca0e49a1

2023-10-08 06:06 UTC, dooohun commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +      [selectedId]: selectedValue < 10 ? `0${selectedValue}` : selectedValue.toString(),
이 부분에 대해서 많이 고민했었는데 `String.prototype.padStart()`라는 메소드가 있었군요...! 꿀팁 감사합니다! 5b958bccc234c8b8b6be9cef326c5c5c0ea5a692

2023-10-08 06:09 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +                >
value라는 변수명에 의미가 와닫지 않는 것 같아서 category라고 변수명을 수정했습니다!
e3862028f5f9dfb1d8547251707b2aeb2726b758 (커밋을 분리해서 했어야 했는데, 코드를 많이 바꾸다 보니 깜빡한 거 같습니다...)

2023-10-08 06:13 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +          <ProgressBar step={step - 1} total={TOTAL_STEP} progressTitle={PROGRESS_TITLE} />
`PROGRESS_TITLE`은 step과 title 두 개의 변수가 있고, `topTitle`은 title 하나만 있습니다. 둘의 title 내용도 다릅니다.
아래의 `ProgressBar`의 title은 두 개의 변수가 있고, `ProgressBar`의 경우 재사용성이 있다고 생각해서 상수로 사용했습니다.

2023-10-08 06:38 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +  const [selectedCategory, setSelectedCategory] = useState('');
`<Category | null> 로 수정했습니다! e3862028f5f9dfb1d8547251707b2aeb2726b758

2023-10-08 06:58 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +                footer={!null}
buttonText는 footer에 있는 버튼에 이름을 뜻하고, title은 모달의 제목을 나타냅니다.
height는 모달 크기를 나타내고, footer는 현재 `hasFooter`로 수정해서 footer의 유무를 판단합니다.

2023-10-08 06:59 UTC, dooohun commented on src/utils/constant/week.ts
> +const WEEK: string[] = ['월', '화', '수', '목', '금', '토', '일'];
타입스크립트를 사용하면서 조언해주신 부분에 대해서는 생각해보지 못한 것 같습니다! 꿀팁 감사합니다!!
해당 부분 수정했습니다. bf6b181fa41525c218f1060291b8d2353deea853

2023-10-08 07:00 UTC, dooohun commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +export default function InputBox({ content, inputId }: InputProps) {
넵 id로 수정했습니다! 5b958bccc234c8b8b6be9cef326c5c5c0ea5a692

2023-10-08 07:11 UTC, dooohun commented on src/page/StoreRegistration/component/TimePicker/index.tsx
> +  function handleTimeChange(e: any) {
button의 click이벤트에 `e.target.value`가 있는 줄 알았습니다.. 해당 부분은 MouseEvent로 수정하고 `e.currentTarget.value`로 수정했습니다. 0e64dffd02dbde058fffdbcc6830ecb2909665f0, 1e8ab8d9f58d8b4bfbfa0d5f07530f63994cbd2d

2023-10-08 07:26 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +              {categoryList?.shop_categories.slice(1).map((value) => (
도메인에 대한 지식을 코드를 보면서 파악하기 힘들다는 사실을 파악하지 못한거같습니다!
좀 더 읽히기 쉬운 코드를 만들도록 노력하겠습니다!! 해당 내용 수정했습니다 506dae22c4fa7a1ae09eedcad90d8373b9ff274b

2023-10-08 07:28 UTC, dooohun commented on src/page/StoreRegistration/view/Mobile/index.tsx
> +                  <img className={styles.category__image} src={value.image_url} alt="category_img" />
alt를 쓸 때 리뷰해주신 내용을 생각해본적이 없네요... 단지 alt는 이미지를 표현하는 것이라고만 알고 있었는데, 좀 더 디테일 한 부분에 대해 신경을 써야겠네요! 
alt=""로 수정했습니다! 357ea7086d5225a34b2494ca2f648e9eb0419c91

2023-10-10 11:44 UTC, daepan approved these changes

2023-10-11 16:59 UTC, MinGu-Jeong approved these changes

2023-10-12 02:47 UTC, hanagertrudekim approved these changes

2023-10-17 09:46 UTC, hoooooony approved these changes

2023-10-17 11:20 UTC, merged