Feature/add menu page
BCSDLab/KOIN_OWNER_WEB pull request #28
Opened 2023-10-25 11:44 UTC by hoooooony

## [#20] request

메뉴 추가 페이지 UI 구현하였습니다.
내 상점 페이지에서 메뉴 추가 버튼을 클릭하면 메뉴 추가 페이지로 넘어갈 수 있습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img width="1324" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/1089c626-34e8-44cd-8791-643f0555ee89">
<img width="1293" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/9f62b314-04ef-4e38-a3d9-8e5f6b74564e">
<img width="377" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/7efe52cf-33f9-45d9-bf44-5ca530c97170">
<img width="502" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/7f083cb7-b4ea-4f58-857b-5e986796aa3e">

### Precautions (main files for this PR ...)
이후 로직 구현, api 연결 진행하겠습니다.

2023-10-26 10:32 UTC, dooohun requested changes
수고하셨습니다!!

구현이 안 된 내용이 있어서 코멘트 남깁니다.
사용자가 작성을 완료하고 확인 버튼을 누르면, 작성한 내용을 간략하게 보여주는 페이지가 필요한데 그 부분이 구현이 안 됐습니다.
 PC 버전과 모바일 버전 둘 다 적용 해야 할 거 같습니다.
**PC**
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/b91884b8-975e-4175-b7eb-0865344169f7)
**Mobile**
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/a2db0f33-279a-4f6e-b7a9-8956bcf4d0e1)

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/components/MenuImage/index.tsx
> +          <div className={styles.mobile__newImg__container}>
이 코드에서 `newImg` 카멜케이스로 다 작성되어 있는데, `new-image`와 같이 작성하면 좋을 거 같습니다!

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/components/MenuImage/index.tsx
> +  };
저도 모달이나 팝업을 열고 닫을 때 많은 리뷰를 받았는데,
`utils/hooks/useBooleanState`를 사용하는 게 좋을 거 같습니다.

팝업을 열 때 `addMenuImg`, 닫을 때 `setAddMenuImgPopupOpen(false)`를 사용하고 있는데,
useBooleanState를 사용해서 선언적으로 사용하는 걸 추천합니다!
setTrue는 열 때, setFalse는 닫을 때 사용하면 가독성 향상에 도움이 됩니다😄

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <input className={styles['price-input']} placeholder="원" />
숫자를 입력했을 때 `placeholder`라서 "원" 문구가 사라집니다!

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/index.tsx
> +  const adddmenuCheck = () => {
```suggestion
  const addMenuCheck = () => {
```
오타났습니다.

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.tsx
> +        <span className={styles['content__sub-text']}>메뉴 관리에서 기존 메뉴의 정보 수정이 가능합니다.</span>
제가 피그마에서 본 문구하고 다릅니다! 
확인 부탁드립니다!
```suggestion
        <span className={styles['content__main-text']}>신규 메뉴 추가 완료 되었습니다.</span>
        <span className={styles['content__sub-text']}>메뉴 관리에서 기존 메뉴의 정보 수정이 가능합니다.</span>
```

2023-10-26 10:32 UTC, dooohun commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              </button>
여기도 마찬가지로 버튼을 클릭하면 배경색과 글자색 변경 기능이 필요합니다!
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/a358d1d9-cee7-45a4-84a2-a948bb160175)

2023-10-26 11:47 UTC, MinGu-Jeong commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.module.scss
> +  box-shadow: 0 2px 4px rgb(0 0 0 / 34%);
@dooohun 혹시 rgb 사용의 장점이 있나요??? 사용하고 싶어하시는 이유가 궁금합니다!

2023-10-26 12:06 UTC, dooohun commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.module.scss
> +  box-shadow: 0 2px 4px rgb(0 0 0 / 34%);
@MinGu-Jeong 좀 더 정확히 이야기 하면 rgba를 사용하고 싶었습니다.
팝업 혹은 모달의 배경의 투명도를 조절해야 할 때가 있는데 rgba를 사용하면 투명도를 조절하는 부분이 편한 거 같습니다.

예를 들어서 검정색 바탕에 30%의 투명도를 보이고 싶을 때 `rgba(0 0 0 0.30)` 이렇게 사용하면 보기에 편하고, 쓰기에 편하다는 장점이 있다고 생각합니다.

2023-10-27 07:54 UTC, hanagertrudekim reviewed
수고하셨습니다~ 코드량이 많네요ㅎㅎ
전체적으로 1. className camelCase 지양 2. 공통된 통일성 유지 .. 요정도 유의해주시면 리뷰 봐주시면 좋을것같아요!

2023-10-27 07:54 UTC, hanagertrudekim commented on src/page/AddMenu/AddMenu.module.scss
> +    display: flex;
여기는 일부로 중첩된 구조로 설정하신건가요?

2023-10-27 07:54 UTC, hanagertrudekim commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +            className={styles['content__from-camera-button']}
단순히 궁금한점인데, `from-camera-button`에서 `from`은 왜 붙은건가요?

2023-10-27 07:54 UTC, hanagertrudekim commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.module.scss
> +    line-height: normal;
`nomal`과 같은 기본 속성들은 생략해도 되지 않을까요?

2023-10-27 07:54 UTC, hanagertrudekim commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <div className={styles['mobile__add-price-button__text']}>가격 추가</div>
아래와 구조가 비슷하다면 차라리 mobile을 `modifier`로 취급하는것도? 좋아보여요ㅋㅋ

2023-10-27 07:54 UTC, hanagertrudekim commented on src/page/AddMenu/AddMenu.module.scss
> +      font-family: "Noto Sans CJK KR", sans-serif;
글꼴같은 경우는 이미 `index.scss`쪽에 지정되어있지않나요?

2023-10-27 10:05 UTC, MinGu-Jeong requested changes
수고하셨습니다!
전체적으로 클래스명을 일관성있게 변경 할 필요가 있어보여요🥲
또한, 변수명이나 클래스명을 지을 때 줄임말은 최대한 지양하는게 어떨까 싶습니다..!
모든 변수명을 특정하긴 어려워서 일부만 리뷰남겨놨으니, 참고하셔서 전체적으로 수정해주시면 될 것 같습니다!!💪

2023-10-27 10:05 UTC, MinGu-Jeong commented on src/page/AddMenu/components/MenuDetail/MenuDetail.module.scss
> +.menu-detail-input {
`input`같은 경우에는 BEM방식을 적용하는게 나을거 같아요..!
```suggestion
.menu-detail__input {
```

2023-10-30 12:30 UTC, kimeodml reviewed
고생하셨습니다!

2023-10-30 12:30 UTC, kimeodml commented on src/page/AddMenu/components/MenuName/index.tsx
> +
불필요한 빈 줄은 제거해 주세요.

2023-10-30 12:30 UTC, kimeodml commented on src/page/AddMenu/components/MenuName/MenuName.module.scss
> +  line-height: normal;
normal로 지정한 값들은 기본값이니까 제외해도 되지 않나요...?

2023-10-30 12:30 UTC, kimeodml commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +export default function AddMenuImgPopup({ isOpen, closePopup }: AddMenuImgPopupProps) {
요거 popup으로 네이밍하셨는데 저는 modal창 같은데 어떻게 생각하시나요?
이와 관련된 내용은 [대관이가 리뷰에](https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/25#discussion_r1329910640) 잘 설명해 놓아서 참고 부탁드립니다!

2023-10-30 12:30 UTC, kimeodml commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.tsx
> +export default function GoMyShopPopup({ isOpen }: CheckPopupProps) {
이 부분 네이밍도 한 번 고려해 주세요!
다른 데는 다 index.tsx인데 이 파일만 GoMyShopPopup.tsx 네요??

2023-10-30 12:30 UTC, kimeodml commented on src/page/AddMenu/index.tsx
> +          <GoMyShopPopup isOpen={isCheckPopupOpen} />
모달외의 부분을 클릭하면 모달창이 꺼졌으면 좋겠어요!

2023-11-06 00:01 UTC, hoooooony commented on src/component/common/Header/Header.module.scss
헤더 메가메뉴 css수정했습니다.! 감사합니다.

2023-11-06 00:27 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.module.scss
> +    color: var(--text-color, #252525);
이전에 만든 팝업을 참고해서 만들다가 그대로 사용하게 된 것 같습니다.
전역적으로 선언해서 사용해보겠습니다. 혹시 전역적으로 사용할 때 @use까지 사용해서 변수를 사용하는것이 더 효율적일까요?

2023-11-06 00:47 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              <button key={category.id} className={styles['mobile__category-button']} type="button">
클래스 네임 buttons 로 통일하였습니다.
글자 변경은 이번 로직변경 구현시에 구현하도록 하겠습니다.

2023-11-06 01:23 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +  ]);
톱니바퀴를 누르면 카테고리 순서가 변경가능해서 useState를 사용해서 구현하였습니다. 
메뉴관리 페이지에서도 이 순서가 변경가능한데 이를 위해서 전역 상태관리로 해야 할 것 같습니다.

2023-11-07 08:50 UTC, hanagertrudekim commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.module.scss
> +    color: var(--text-color, #252525);
`text-color`를 비롯한 여러 프로퍼티들이 다른 곳에서도 중복된다고 하면 고려해볼만한데,
만약 단순히 color 와 같은 단일 프로퍼티를 위해서라면 그냥 전역변수 처리만 해도 괜찮을것같아요ㅎㅎ

2023-11-08 05:58 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              </button>
로직 구현에서  구현하도록 하겠습니다.

2023-11-08 06:06 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <div className={styles['mobile__add-price-button__text']}>가격 추가</div>
어 전 괜찮게 보이는데 width를 줘서 디스플레이마다 다르게 보이는걸까요?

2023-11-09 11:31 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.module.scss
> +    color: var(--text-color, #252525);
아하 감사합니다.

2023-11-09 11:33 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/MenuCategory.module.scss
> +}
실수로 놓친 것 같습니다. 감사합니다.

2023-11-09 12:01 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              <button key={category.id} className={styles.categoryButton} type="button">
수정했습니다. b4f16cbadfe7e140184c2b5e6f595c8fc31c60e7

2023-11-10 07:41 UTC, hoooooony commented on src/page/AddMenu/components/MenuImage/index.tsx
> +          <div className={styles.mobile__newImg__container}>
수정했습니다. 6935068622a653da84504c771ecc5a1c86a9a4f5

2023-11-13 02:33 UTC, hoooooony commented on src/page/AddMenu/components/MenuImage/index.tsx
> +  };
수정했습니다. 가독성이 많이 향상된 것 같습니다. 👍  aef10a812c4135cf208cf348f49d17eea6272700

2023-11-13 02:58 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <input className={styles['price-input']} placeholder="원" />
이부분을 생각못했네요. inputbox를 감싸는 div를 만들고 p태그로 원을 출력하였습니다.3e000ad208e16ccb21f8241d7c4ff9defc917db9

2023-11-13 02:59 UTC, hoooooony commented on src/page/AddMenu/index.tsx
> +  const adddmenuCheck = () => {
`useBooleanState`를 사용하면서 지웠습니다!

2023-11-13 03:02 UTC, hoooooony commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.tsx
> +        <span className={styles['content__sub-text']}>메뉴 관리에서 기존 메뉴의 정보 수정이 가능합니다.</span>
수정완료했습니다. b84e60a2c4a4dffd82975339d2f64827149fbeef

2023-11-13 07:03 UTC, hoooooony commented on src/component/common/Header/index.tsx
> +        <div className={styles.addMenuHeader__caption}>메뉴추가</div>
add-menu-header로 통일해서 수정했습니다.! ff496e45c9bf644ce6f5b724b93657ded853f273

2023-11-13 07:06 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +  };
`useBooleanState`를 사용하면서 수정하였습니다.

2023-11-13 07:09 UTC, hoooooony commented on src/page/AddMenu/AddMenu.module.scss
> +    display: flex;
모바일과 구분지어서 보는게 편해보일까 해서, 중첩된 구조로 작성하였습니다. 다른 부분처럼

2023-11-13 07:12 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +            className={styles['content__from-camera-button']}
의미가 더 잘 와 닿을것 같아서 붙였는데, 지금보니 별로인것 같습니다. `album-button`, `camera-button`으로 수정하겠습니다.

2023-11-13 07:26 UTC, hoooooony commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.module.scss
> +    line-height: normal;
너무 피그마를 따라 갔던 것 같습니다. 다음부터는 상위 스타일에 영향을 받을 때만 사용하도록 하겠습니다. 66488b19ed97bd2a355e259ceb3fd84459f071f9

2023-11-13 07:31 UTC, hoooooony commented on src/page/AddMenu/AddMenu.module.scss
> +  &__btn-container {
많이 사용하는 이름이라 생각해서 btn으로 작성하였는데 button으로 작성하겠습니다.!
36c90e33588fdc746fc0a102c365f5793605b184

2023-11-13 07:37 UTC, hoooooony commented on src/page/AddMenu/AddMenu.module.scss
> +
40px정도로 해서 수정했습니다.56eb6c252903bd34d626b45e05b24a836a891043

2023-11-13 07:39 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +  const conClickFromCamera = () => {
오타 였던것 같습니다. `useBooleanState`를 사용하면서 해당 부분은 삭제 되었습니다.

2023-11-13 07:48 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/MenuCategory.module.scss
> +  &__category-button {
너무 길면 가독성이 오히려 떨어질것 같아서 btns로 작성하였는데 `category-button-container`가 읽을 때 더 이해가 쉬울것 같아서 수정하겠습니다. 376c1d5f18d9be5eb1db187cc97b625a81c3a103

2023-11-13 12:38 UTC, hanagertrudekim commented on src/page/AddMenu/AddMenu.module.scss
> +    display: flex;
별 차이는 없을것같은데, 굳이 중첩되지 않아도 될것같아요🙂

2023-11-14 02:02 UTC, hoooooony commented on src/page/AddMenu/components/MenuDetail/MenuDetail.module.scss
> +.menu-detail-input {
메뉴 상세정보를 넣는 Input여서 detail-input이라고 작성하였습니다!

2023-11-14 05:12 UTC, hoooooony commented on src/page/AddMenu/AddMenu.module.scss
> +    font-family: "Noto Sans CJK KR", sans-serif;
네 앞으로는 앞으로 필요한 스타일들은 전역적으로 선언해보도록 하겠습니다.
일단 font-family를 해당 부분에서는 적용하지 않도록 변경하였습니다. 66488b19ed97bd2a355e259ceb3fd84459f071f9

2023-11-14 05:15 UTC, hoooooony commented on src/page/AddMenu/components/MobileDivide/index.tsx
> +    <div className={styles['divide-line']}> </div>
<img width="409" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/112807899/277cb677-7614-4d99-bf33-171a61bf4539">
각 항목을 나누는 선을 그리기 위해서 사용하였습니다. 따로 만들어서 사용하는 것보다 각 항목 아래에 만드는 것이 효율적일까요?

2023-11-14 05:24 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
> +    line-height: normal;
AddMenu.module.scss에서 중첩으로 input태그 선택자를 사용해서 선언해서 사용하면 될까요? 
어떤 방식으로 해야할지 잘 모르겠습니다...

2023-11-14 05:25 UTC, hoooooony commented on src/page/AddMenu/components/MenuName/index.tsx
> +
넵!

2023-11-14 05:26 UTC, hoooooony commented on src/page/AddMenu/components/MenuName/MenuName.module.scss
> +  line-height: normal;
제외 완료 했습니다! 66488b19ed97bd2a355e259ceb3fd84459f071f9

2023-11-14 05:32 UTC, hoooooony commented on src/page/AddMenu/components/AddMenuImgPopup/AddMenuImgPopup.tsx
> +export default function AddMenuImgPopup({ isOpen, closePopup }: AddMenuImgPopupProps) {
모달과 팝업의 차이를 확실히 이해했습니다. 감사합니다.
모달로 수정했습니다.80abc072ebb4a6f111d0e6165d95cf0f13884036

2023-11-14 05:35 UTC, hoooooony commented on src/page/AddMenu/components/GoMyShop/GoMyShopPopup.tsx
> +export default function GoMyShopPopup({ isOpen }: CheckPopupProps) {
처음에 모달창을 만들때 다르다고 생각해서 이렇게 했던 것 같습니다. 
수정했습니다! 795c301fc3ac385b9a4e83c8d3fddf25117c58c0

2023-11-14 19:21 UTC, ChoiWonBeen commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              <button key={category.id} className={styles['mobile__category-button']} type="button">
요런건 주석으로 TODO를 달아두면 까먹지 않고 구현에 추가할 수 있을거예요

2023-11-14 19:22 UTC, ChoiWonBeen commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <input className={styles['price-input']} placeholder="원" />
마이너하지만 `<p/>` 가 적절한가는 의문이네용 span처럼 의미를 가지지 않는 태그가 더 어울릴듯??

2023-11-14 19:26 UTC, ChoiWonBeen commented on src/page/AddMenu/components/MobileDivide/index.tsx
> +    <div className={styles['divide-line']}> </div>
컴포넌트로 분리하는 건 좋지만, 클래스명이 추상적이지 않을 필요는 없다는 말인 것 같아요

2023-11-14 19:27 UTC, ChoiWonBeen commented on src/page/AddMenu/components/MenuPrice/MenuPrice.module.scss
> +    line-height: normal;
`@use` 같은걸 사용해서 가져다 쓰면 편할 것 같네여 급한 수정은 아닌듯?

2023-11-15 04:54 UTC, hoooooony commented on src/page/AddMenu/index.tsx
> +          <GoMyShopPopup isOpen={isCheckPopupOpen} />
완료했습니다! 2c1090a6d4cf6f76c274082c5927943821e78d42
일단 div에 onclick 속성을 주기위해서 role을 button으로 주었습니다. 
button으로 사용하려면 onKeyDown속성과 , tabIndex속성이 필요해서 해당 속성들을 주었는데 이런 방식이 옳은 방식일까요?

2023-11-15 08:26 UTC, hoooooony commented on src/component/common/Header/index.tsx
> +  }
다음 pr에서 해결하도록 하겠습니다!

2023-11-15 08:28 UTC, hoooooony commented on src/page/AddMenu/AddMenu.module.scss
> +      font-family: "Noto Sans CJK KR", sans-serif;
font-family부분 전반적으로 수정하였습니다. 66488b19ed97bd2a355e259ceb3fd84459f071f9

2023-11-21 05:25 UTC, hoooooony commented on src/page/AddMenu/components/MenuCategory/index.tsx
> +              <button key={category.id} className={styles['mobile__category-button']} type="button">
구현했습니다! 5ccff93643ae1a17be8caed3ed85b5884f67d546

2023-11-21 05:25 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <div className={styles['mobile__add-price-button__text']}>가격 추가</div>
다음 브렌치에서 수정하겠습니다!

2023-11-21 05:27 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <div className={styles['mobile__add-price-button__text']}>가격 추가</div>
고정 `width`는 지양하도록 하겠습니다

2023-11-21 11:12 UTC, daepan approved these changes
수고하셨습니다.

2023-11-24 08:30 UTC, hoooooony commented on src/page/AddMenu/components/MobileDivide/index.tsx
> +    <div className={styles['divide-line']}> </div>
이해했습니다!

2023-11-24 08:34 UTC, hoooooony commented on src/page/AddMenu/components/MenuPrice/index.tsx
> +            <input className={styles['price-input']} placeholder="원" />
p는 단락, 문단을 구분하는 용도라는 것을 몰라서 이렇게 사용했던 것같습니다. 수정했습니다. af310ef718218befc050dfe9042c723c04519038

2023-11-24 12:10 UTC, dooohun approved these changes

2023-11-26 06:18 UTC, MinGu-Jeong approved these changes

2023-11-26 06:21 UTC, merged