[비밀번호 찾기] 인증번호 발송 및 검증 로직 구현
BCSDLab/KOIN_OWNER_WEB pull request #29
Opened 2023-11-10 11:50 UTC by MinGu-Jeong

## [#18] request

- 테스트계정
 email: mingu830@gmail.com
 pw: mingu980!
- 토큰없음 에러가 발생하지 않아야 할 때도 발생하는 문제를 해결했습니다. feat @ChoiWonBeen 
 추후 setUser가 에러를 다루는 문제를 제거해야 한다고 합니다.
- 인증번호 발송 및 검증하여 새로운 비밀번호 변경 페이지까지 이동하도록 구현했습니다.
- 새 비밀번호 입력 페이지랑 분리하여 PR 올리도록 하겠습니다.
    - [x] 인증번호 보내기 및 검증
    - [ ] 새 비밀번호 변경
- 기존 figma디자인은 인증번호 보내기 `input` 옆에 인증번호 발송 `button`이 있었으나, 이메일 입력 `input` 옆에 있는것이 자연스러울 것 같아 수정했습니다.
- 인증번호 발송 눌렀을 때, 잘못된 인증번호를 입력했을 때 메시지가 필요해 보이는데 다음 PR때 반영하겠습니다.
## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img width="300" alt="스크린샷 2023-11-10 오후 8 45 52" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/88c57b95-39d1-4a41-bb75-07a40af89808">

### Precautions (main files for this PR ...)

2023-11-13 07:57 UTC, hanagertrudekim requested changes
수고하셨습니다~ (아무도 리뷰어가 없네요...ㅠ) 
간단한 코멘트 확인해주세요!

2023-11-13 07:57 UTC, hanagertrudekim commented on src/api/auth/index.ts
> +});
ui 단에선 `email` 인데 api 단에서는 `address` 라는 말을 써 혼동될수도있을것같아요. (백엔드에서 파라미터 값을 `address`로 지정한것같네요) 
혼동이 가지 않게 조정할수있는 방법은 없을까요?

2023-11-13 07:57 UTC, hanagertrudekim commented on src/layout/AuthLayout/index.tsx
> +    setUser().catch(() => {});
어떠한 경우에서 토큰없음 에러가 발생하게되나요?

2023-11-13 07:57 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  });
api 로직을 따로 파일 분리하면 좋을것같아요.

2023-11-13 07:57 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
> +export default useRouteCheck;
1. 일부로 반환되지않는 hook을 유도하신건가요? 아니라면 현재 구현된 hook에서 반환되지 않는 로직을 개선하는 것이 어떨까요? 

개인적인 생각으론 반환이 필요없는 hook 구조로 사용한다면 클라 측면에서 단순화된다는 장점이 있지만, 
반환되는 hook 구조의 경우 향후 `checkRoute` 외에 추가 기능이 필요할 경우, 로직 분리와 유지보수 측면에서도 유리할것같아요. 
사용하는 곳에서도 훨씬 파악하기도 편할것같구요. (제가 생각한 장단점은 여기까지입니다..)
ex. 
```js 
const {checkRoute : checkPasswordRoute} = useRouteCheck('authCheck', '/find-password');
```


2. `이전_상태를_가지고_넘어왔는가` 는 적당한 이름으로 대체할 필요가 있을것같아요ㅎㅎ

3. `prevState` 보다는 route 관련한 hook이니까 `prevRoute` 정도도 괜찮을것같아요

```suggestion
const useRouteCheck = (prevState: string, entryRoute: string) => {
  const location = useLocation();
  const navigate = useNavigate();

const checkRoute = () => {
  useEffect(() => {
    const 이전_상태를_가지고_넘어왔는가 = location.state && (prevState in location.state);
    if (!이전_상태를_가지고_넘어왔는가) {
      navigate(entryRoute, { replace: true });
    }
  }, [location.state, navigate, entryRoute, prevState]);
};
};

export default {checkRoute};
```

2023-11-13 11:51 UTC, HAEROOL approved these changes
수고하셨습니다!

2023-11-13 14:33 UTC, MinGu-Jeong commented on src/layout/AuthLayout/index.tsx
> +    setUser().catch(() => {});
현재 `develop` 브랜치에서 실행해보면 아시겠지만, 초기화면에서 user정보가 없는것이 정상인데 `setUser()`에서 `getMe()`를 시도하면서 토큰없음 에러를 return하는것 같습니다.
`setUser()`에서 에러가 발생했을 때 `()=>{}`를 수행함으로써 임시적으로 에러를 막아둔? 상태인 것 같은데, 추후 이러한 에러 핸들링 구조 자체를 바꿔야 한다고 들었습니다.

2023-11-13 15:01 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
> +export default useRouteCheck;
1. 현재 `useRouteCheck`가 한가지의 일만 하고 있는데, 미래의 확장성까지 고려해서 `useRouteCheck` 내부에 `checkRoute`기능으로 분리하고 추후 다른 기능이 추가할 수 있도록 하자는 의도로 해석되는데 맞을까요?
1-1. 만약 `useRouteCheck`에 다른 기능이 추가된다면 예를 들어서 어떤 기능이 추가될 수 있을까요?
1-2. 만약 다른 기능이 추가된다고 하면 `useRouteCheck`내부에 여러가지 기능을 만드는 것과 각 기능별로 hook을 분리하는 것 중 어떤게 더 나을지 궁금합니다!
2. 한글변수는 원빈이의 강력한 추천으로 사용해보았습니다만... 사실 이정도 변수는 `isPrevState`나 `hasPrevState`정도로도 사용할 수 있긴 하겠네요😅 앞으로도 한글변수를 적극적으로 사용해볼려고 하는데 네이밍컨벤션에 위배될까요? 조금 복잡한 변수명은 한글변수가 훨씬 가독성 있다고 느껴집니다..!
3. `prevRoute`가 더 적절해보이네요..! 수정했습니다! acc88a7576113b27b7d449eb3ada168a2e72f8b2

2023-11-14 07:43 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
`authCheck` 부분에 previous route path 가 문자열로 들어가야하는거 아닌가요? authCheck 는 무엇을 의미하나요?

2023-11-14 08:02 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
이전 라우트 path 코드입니다.
```
const submit = useMutation({
    mutationFn: () => findPassword({ address: emailInput, certificationCode: verifyInput }),
    onSuccess: () => {
      navigate('/new-password', { state: { authCheck: true }, replace: true });
    },
```
`navigate()`의 두 번째 인자로 state를 전달합니다. 이때 authCheck 상태를 true로 전달합니다.

다음 라우트 path 코드입니다.
```
 useRouteCheck('authCheck', '/find-password');
```
첫 번째 인자로 `authCheck`를 넘겨줍니다.

useRouteCheck 코드입니다.
```
const useRouteCheck = (prevRoute: string, entryRoute: string) => {
  const location = useLocation();
  const navigate = useNavigate();
```

지금 정리하면서 보니깐 현재 수정된 변수명인 `prevRoute`가 기존에`prevState`라고 네이밍을 지었던 이유가 있었습니다.
저는 경로가 아닌 상태를 넘겨주는 Hook이라고 생각하고 사용했던 것 같습니다.
`useRouteCheck` Hook에서 첫 번째 인자로 상태가 아닌 경로가 들어가는게 더욱 적절할까요?

2023-11-14 08:20 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
> +export default useRouteCheck;
1. 네 맞습니다. 
- 추가될 기능이라고 하면 페이지 유효성 체크(페이지가 존재하지않는다면 404페이지로 리다이렉트), 특정 권한 검사, 특정한 url에 대한 매개변수 처리 등이 있을것같아요. 사실 모든 기능이 지금 꼭 필요하진않으니,  만약 필요하다면 그때 적절히 조율하는것도 좋겠네요.
- 처음엔 `useRoute` hook정도로 더 추상화해서 route 와 관련된 모든 기능을 추가하는 방식을 생각했었는데,  너무 응집되면 복잡해질수도있을것같아서, 그냥 지금처럼 적당한 기능별로 나누는것도 괜찮을것같네요ㅎㅎ 

+함수(또는 hook)의 이름도 `validatePreviousRoute` 등으로 이전  route를 검사한다는 느낌을 주면 좋을것같아요.
또한 이전 경로를 가지고있지 않을때 적절한 에러를 반환해주는 에러 처리도 필요할것같아요.  

2. 조금 더 의미 전달을 위해 `이전_경로를_가지고_있는가` 정도도 괜찮을것같네요. 프로젝트에 한글변수를 적용한다면, 어디에 어떻게 적용할지 적절한 기준이 필요할거같아요.

2023-11-14 19:34 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
1. 어제 회의에서 오프라인 코드리뷰하면서 조금 더 이야기 한거로는 `useRouteCheck`를 조금 더 추상화해서 다른 페이지에서도 사용할 수 있는 공용 Hook으로 만들자는 결론이 나왔었는데, 그렇게 하면 여전히 navigate에 state조건을 추가해야하는 문제가 있겠네요.. 한 페이지로 렌더링 한 뒤 내부에서 state로 관리하는것에 단점이 있을까요??

2. `useFunnel` Hook을 사용하기 위해 토스 라이브러리 설치가 필요해보이는데 구성원들과 협의가 되어야할까요? 제 임의로 설치해서 사용해도 될까요?

2023-11-15 04:18 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
지금 해결하려는 문제들과 비교할 땐 단점은 없어보여요. 

라이브러리가 유틸을 전부 모아둔 게 아니라 딱 저 함수 하나만 구현한거라 용량 등은 고려하지 않아도 될 것 같아요.
직접 구현해도 괜찮겠..지만 타입정의가 너무 어렵겠네요

2023-11-15 19:09 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  });
api 로직을 `query/auth.ts`로 분리했습니다. 2557882a5a6cadc6ecaf93b66c9466ba95f6d6df

2023-11-17 09:13 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
`useFunnel` Hook을 이용해서 페이지 관리하는건 이슈 따로 생성해서 다음에 PR올리는식으로 작업해도 괜찮을까요?
비밀번호 찾기 기능 구현을 마무리하고 리팩토링하는 느낌으로 작업하도록 하겠습니다.

2023-11-18 06:11 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
아유 물론이죠

2023-11-18 06:20 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  const verifyEmail = useVerifyEmail(emailInput, setIsSendAuth);
state를 따로 만들면 useMutation의 활용성이 떨어져요~
`mutation.isSuccess` 를 이름만 바꿔서 쓰면 적절할 것 같네여

2023-11-18 06:21 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  const verifyEmail = useVerifyEmail(emailInput, setIsSendAuth);
해당 훅이 특정 state에 의존을 갖는 형태도 불편한 느낌이죠.
`verifyEmail(emailInput)` 처럼 쓸 수 있도록 mutation에 인자를 만들어주면 완전히 외부 상태에 대한 의존을 벗어날 수 있겠죠!?

2023-11-18 06:23 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  const submit = useSubmit(emailInput, verifyInput);
여기도, 훅이 상태에 의존하기보단, 쓰는 쪽에서 이를 활용해야한다고 생각해요.

2023-11-18 06:23 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +              submit.mutate();
위 리뷰를 적용하면 아래처럼 쓸 수 있겠죠? 훨씬 직관적이라고 생각해요!
```suggestion
              submit(emailInput, verifyInput);
```

2023-11-18 06:24 UTC, ChoiWonBeen commented on src/query/auth.ts
> +    mutationFn: () => findPassword({ address: emailInput, certificationCode: verifyInput }),
위 구현은 간단히 이렇게 할 수 있어여
```suggestion
export const useSubmit = () => {
  const navigate = useNavigate();
  const { mutate } = useMutation({
    mutationFn: (emailInput: string, verifyInput:string) => findPassword({ address: emailInput, certificationCode: verifyInput }),
```

2023-11-20 00:24 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
> +  const verifyEmail = useVerifyEmail(emailInput, setIsSendAuth);
`isSendAuth` 상태 없이 `useMutation()`의 `isSuccess` 반환값을 이용하도록 수정했습니다. caab496e2749340e4ce169baf9426f5195f44dd1

2023-11-20 04:38 UTC, MinGu-Jeong commented on src/query/auth.ts
> +    mutationFn: () => findPassword({ address: emailInput, certificationCode: verifyInput }),
Hook이 상태에 의존하지 않도록 수정했습니다. 2e7495dd8f36faf7a2b17b8d981d11a41fd916a7

2023-11-20 04:40 UTC, MinGu-Jeong commented
현재 수정된 부분까지 merge하고
퍼널을 이용한 페이지 관리는 비밀번호 찾기 구현이 완료 된 이후 진행하도록 하겠습니다!

2023-11-21 11:32 UTC, hanagertrudekim approved these changes

2023-11-21 12:00 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +  useRouteCheck('authCheck', '/find-password');
`useFunnel`사용에 대해서 회의시간에 얘기 해봤는데 `useFunnel` 훅이 next환경에서만 동작한다고 해서 `useFunnel`사용은 보류하기로 했습니다.🥲

2023-11-24 04:40 UTC, merged

2023-11-28 11:09 UTC, daepan reviewed
고생하셨습니다. 코멘트 달아둔것만 확인해주시고 Rerequest 부탁드립니다~

2023-11-28 11:09 UTC, daepan commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
> +};
요고 한글 컨벤션인가요?

2023-11-28 11:13 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
> +};
저번 회의때 한글변수는 사용을 자제하자는 결론이 나오기도 했고, `useRouteCheck`를 전체적으로 리팩토링해야되기 때문에 추후 리팩토링하면서 다시 영어변수로 수정할 예정입니다.