[이벤트 수정] 이벤트 수정 페이지 추가
BCSDLab/KOIN_OWNER_WEB pull request #298
Opened 2024-04-20 04:13 UTC by chaeseungyun

- Close #259 
  
## What is this PR? 🔍

- 기능 : 이벤트 수정 기능 구현
- issue : #259 

## Changes 📝

이벤트 수정 기능을 추가했습니다.

## ScreenShot 📷

![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101871802/730f56b1-39a4-44cb-9937-093e2c2b411c)

## Test CheckList ✅

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] Did you merge recent `develop` branch?

2024-04-22 09:20 UTC, daepan requested changes
API 추가 및 UI 부분 확인했습니다.
반복되는 코드가 너무 많군요! 해당 부분은 수정부탁드립니다.

2024-04-22 09:20 UTC, daepan commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +  };
너무 반복적인 부분이 있군요. 본인 스스로를 반복하는 코드는 코드를 지저분하게 합니다.
정규표현식이나 함수호출이랑 setError도 동일하게 반환도 하니 어렵지 않게 뺄 수 있는 작업이 될 것 같습니다.

2024-04-22 09:20 UTC, daepan commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +    ) {
뭔가 이것도 옆으로 빼면 참 좋을 것 같긴한데 뭔가 이런 날짜 검증과 관련되어서는 많이 사용될 것도 같네요
```suggestion
   const dateValidationCheck = (date: Date) => {
      return date.year.length === 0 || date.month.length === 0 || date.date.length === 0;
   }  
```
대충 이런식으로 공용함수로 빼놓고 나중에 재사용하면 좋을 것 같습니다.

2024-04-22 10:16 UTC, Gwak-Seungju reviewed
페이지 추가하시는데 고생하셨습니다!!! 리뷰가 늦은 점 죄송합니다!!!!!

2024-04-22 10:16 UTC, Gwak-Seungju commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +  const changeEndYear = (e: React.ChangeEvent<HTMLInputElement>) => {
혹시 종료일이 시작일보다 앞서는 경우(시작일: 2024.04.21, 종료일: 2024.04.20 등)에 대한 제한 조건이 따로 있나요? 만약 없다면 추가해도 좋지 않을까 생각합니다!

2024-04-22 10:16 UTC, Gwak-Seungju commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +              placeholder="2999"
placeholder에 기존 이벤트 시작/종료일을 불러와도 좋을 것 같아요!

2024-04-23 08:32 UTC, chaeseungyun commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +  };
fa4fc74e6d6c29548cec863b9b3d6528529e602b

좋은 조언 감사합니다! 사실 인지하고 있었는데 비즈니스팀 2차 QA 전까지 만드려고 시간이 부족해서 신경을 못썻습니다
이번 기회의 리펙토링하게 돼서 좋습니다
그런데 두 개의 컴포넌트에 동일한 코드가 있긴 한데, set함수와 error 객체도 파라미터로 받기 과한거 같아서 제외했습니다
부족한 부분 있으면 알려주세용

2024-04-23 08:48 UTC, chaeseungyun commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +    ) {
91ebd43f0c87ea40dc87e9c003b6728404e15849

마찬가지로 적용했습니다

2024-04-23 08:48 UTC, chaeseungyun commented on src/page/ManageEvent/ModifyEvent/index.tsx
> +              placeholder="2999"
오 디자이너분과 상의해서 적용해보겠습니다

2024-04-23 16:12 UTC, daepan approved these changes
수고하셨습니다

2024-04-24 12:13 UTC, merged