[가게 등록] 가게 등록 페이지 PC 버전 로직 구현 및 API 구현
BCSDLab/KOIN_OWNER_WEB pull request #30
Opened 2023-11-12 14:20 UTC by dooohun

## [27] request
- 가게 등록 페이지 PC 버전 로직 구현 및 API 구현했습니다.  

**[주요 구현사항]**
- 이미지 클릭 시 미리보기
- `SearchStore` 가게 검색 기능
- 운영 시간 기능 구현
- 사장님 상점 생성 기능 구현

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `deveop` branch?

### Screenshot
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/11beea90-6394-43be-9242-bb63d467ded3)
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/b2554ebd-8101-4f37-b9dc-9e1717c2fdad)
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/84a75fa4-3b5f-4e3f-9003-184c7bd62a91)

### Precautions (main files for this PR ...)
- 이후에 PC 버전 (`page/StoreRegistration/view/PC)는 스텝별로 파일 분리 예정입니다. (코드가 길어 읽기 불편합니다... 양해 부탁드립니다 😢😢 )
- PC 버전 UI에는 대표자명이 있지만, 모바일 UI에는 대표자명이 없습니다. 그리고 [사장님 swagger](https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_Owner_Shop/createShopUsingPOST_1)의 상점 생성에도 대표자명이 없어서 이 부분은 문의해보겠습니다.

2023-11-12 17:00 UTC, MinGu-Jeong requested changes
수고하셨습니다!!! 굉장히 노력이 많이 들어간 코드처럼 보이네요😀
리뷰와 별개로 몇가지 이슈가 있습니다.
- 기타정보 미입력 시 422에러가 발생해서(기타정보는 1자 이상이어야합니다) 다음페이지로 넘어갈 수 없는데, 요건 API가 그렇기 때문에 어쩔 수 없는거 같지만, 사실 기타정보가 필수적으로 입력되어져야하나..? 라고 생각하면 아닌거 같아서 이건 다음 회의때 얘기해봐야 할 것 같아요. 만약 API 수정없이 진행한다고 하면 기타정보나 다른 정보를 입력안해서 다음페이지로 넘어가지 않을 때 적절한 UI를 보여줘야 할 것 같아요! 지금 상태로는 다음 페이지로 넘어가지 못하는 이유를 알기 힘들어요.
<img width="1664" alt="스크린샷 2023-11-12 오후 11 41 47" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/d015d400-5f4f-495d-be00-d2c8411552ac">

- 가게를 등록하는 페이지인데 가게검색 기능이 있는게 좀 이상하죠..? 어떤 의도로 가게등록 페이지에 가게검색 기능이 있는지 회의시간에 한 번 얘기 해봐야할 것 같습니다.
- 코드리뷰하면서 느낀건데 저희 프로젝트 전체적으로 store과 shop이 혼용되는 느낌인데 통일해야 할 필요성이 있어보여요..! 이것도 회의때 얘기 해보면 좋을 것 같습니다.

수고하셨어요😀

2023-11-13 04:30 UTC, dooohun commented on src/model/shopInfo/allShopInfo.ts
> +  close_time: z.string().nullable(),
네 [사장님 swagger](https://api.stage.koreatech.in/swagger-ui.html#!/(Normal)_Owner_Shop/createShopUsingPOST_1)에 자세히 나와있는데, closed가 true인 경우 close_time, close_time은 어떤 값이 요청되던 null로 저장되어야 합니다. 😄

2023-11-13 07:34 UTC, MinGu-Jeong commented on src/page/StoreRegistration/view/PC/index.tsx
> +                          <div>
제가 쓴 한글 변수부분을 살펴보니깐 저도 `!긍정형 변수`처럼 부정형으로 작성했네요🤣
클린코드 측면에서는 if문 내부에 긍정형으로 작성하는걸 추천한다고 하니깐 참고만 해주세요!!

2023-11-13 11:48 UTC, HAEROOL approved these changes
고생하셨습니다! 뷰를 그리는 파일에서 비즈니스 로직이 너무 길어지거나 복잡해지면 커스텀 훅으로 분리하는 쪽으로도 생각해보면 좋을 것 같습니다. 현재 상점 검색 컴포넌트를 회원가입 로직에서도 사용할 예정이라 차후 필요한 부분이나 수정사항 있으면 연락드리겠습니다!

2023-11-13 11:48 UTC, HAEROOL commented on src/component/common/CustomModal/index.tsx
> +  buttonText = '', title, height, hasFooter, isOpen, hasOverflow, onCancel, children,
여기 `hasOverflow`는 어떤 역할을 하나요??

2023-11-13 11:48 UTC, HAEROOL commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  function handleClickStore(e: React.MouseEvent<HTMLButtonElement>) {
`shop`과 `store`의 사용에 혹시 차이가 있나요? 없다면 둘 중에 하나로 종류를 통일 시키는 것도 좋아보입니다!

2023-11-13 11:48 UTC, HAEROOL commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  let filteredShopList;
`let`의 사용은 지양하고 `useState`를 통해 `fillteredShopList`의 상태를 관리하는 것은 어떨까요?

2023-11-13 11:48 UTC, HAEROOL commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
>          <Magnifier type="button" className={styles['info__search-button']} />
혹시 돋보기 모양 클릭했을 때, 상점 리스트가 필터링 되는 기능을 추가하는 것은 어떻게 생각하시나요? 혹은 엔터를 눌렀을 경우에도 필터링이 된 다면 좋을 것 같아요!

2023-11-13 11:48 UTC, HAEROOL commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  const { shopList } = useAllShops();
만약 `shopList`를 못 불러왔을 경우의 에러 핸들링도 있으면 좋을 것 같아요!

2023-11-13 12:33 UTC, hanagertrudekim requested changes
수고하셨습니다🙂
자잘한 네이밍 관련 코멘트들이 좀 있는데, 적용할것들만 잘 분별해주셔서 수정해주세요!

2023-11-13 12:33 UTC, hanagertrudekim commented on src/component/common/CustomModal/index.tsx
> +          [styles['container--selected']]: !!hasOverflow,
`hasOverflow`가 어떤 상태를 나타내는지 유추하기 힘든것같아요

2023-11-13 12:33 UTC, hanagertrudekim commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +      />
input type이 `number`, `text` 외의 다른 타입으로 지정될 경우는 없을까요?

2023-11-13 12:33 UTC, hanagertrudekim commented on src/store/modalStore.ts
> +};
```suggestion
const daysOfWeek = ['월', '화', '수', '목', '금', '토', '일'];

const initialOperatingTime = {};
const initialStoreClosed = {};

daysOfWeek.forEach(day => {
  initialOperatingTime[day] = '00:00';
  initialStoreClosed[day] = false;
});
```

이런식으로 같은 속성의 중복성을 줄일수도 있을것같아요. 

(+ 상수명은 대문자로 맞춰주세요)

2023-11-13 12:33 UTC, hanagertrudekim commented on src/store/modalStore.ts
> +export default useModalStore;
Store가 뒤에 있어서 store(저장) 기능을 가진다는 느낌을 줘 혼동되는것같아요.
`useStoreModal` 처럼 modal의 기능의 집중할수있도록 모두 뒤로 옮겨주는것은 어떨까요?

2023-11-13 12:33 UTC, hanagertrudekim commented on src/query/shops.ts
> +export default useAllShops;
반환값에 맞추어 `useShopList` 정도의 네이밍도 괜찮을것같아요

2023-11-13 12:33 UTC, hanagertrudekim commented on src/page/StoreRegistration/view/PC/index.tsx
> +  };
이미지 파일 변환하는 로직이 앞으로도 많이 쓰일텐데 hook 으로 따로 빼내는건 어떨까요?

2023-11-14 19:41 UTC, ChoiWonBeen commented on src/store/modalStore.ts
> +};
어아 이부분은 저는 조금 보수적인게, store의 initialValue로 들어가는부분이다보니 export되지 않은 전역변수 부분에서 값을 핸들링하는건 위험하다고 느낄 수 있다고 봐요. (단순한 유틸 파일이 아니다보니 더욱 그런 감이 있네요)

차라리 이 변수들을 사용하는 측면에서 명확한 값을 갖게끔 만들어주는건 어떨까 의견을 내봅니다

```ts
const useModalStore = create<ModalStore>((set) => ({
  categoryState: ['', 0],
  searchStoreState: '',
  openTimeState: daysOfWeek.reduce((acc, cur) => { return cur[acc] = '00:00' }, {}),
  // ...
}))
```

2023-11-14 19:43 UTC, ChoiWonBeen commented on src/store/modalStore.ts
> +export default useModalStore;
이 훅은 Store의 기능에 집중하는게 맞는 것 같아요. store를 다루는 훅이니?

2023-11-14 19:47 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/index.tsx
> +  const [operateTimeState, setOperateTimeState] = useState<OperateTimeProps>({});
`Record<>` 타입이 딱 적절할 것 같아요.
컴포넌트 내에서 타입이 정의되는건 흔하지 않은 것 같네요 ㅋㅋ

2023-11-14 19:48 UTC, ChoiWonBeen commented on src/page/StoreRegistration/view/PC/index.tsx
> +  const 휴일이_있는_날이_있는가 = storeClosedArray.some((closed) => closed);
minor) 
```suggestion
  const 휴일인_날이_있는가 = storeClosedArray.some((closed) => closed);
```

2023-11-14 19:51 UTC, ChoiWonBeen commented on src/store/modalStore.ts
> +  categoryState: [string, number];
카테고리 id인 number만 가지고 있어도 되지 않을까요?
특이한 구조같아서 언급해봤어요

2023-11-14 19:51 UTC, ChoiWonBeen commented on src/store/modalStore.ts
> +  setCloseTimeState: (state: { [key in typeof WEEK[number]]: string | null }) => void,
너무 복잡해지는 것 같은데... `[key in typeof WEEK[number...` 이런 부분을 타입으로 정의해두는건 어떨까영

2023-11-14 19:52 UTC, ChoiWonBeen commented on .eslintrc.json
> +		"import/prefer-default-export": "off",
너무좋아요
default export는 처단해야한다고 생각합니다 개인적으로
장점이없는듯?

2023-11-15 08:21 UTC, hoooooony commented on .eslintrc.json
> +		"import/prefer-default-export": "off",
제가 이번에 작성한 코드에서 메뉴이름, 가격 등 각 컴포넌트를 export default 함수로 내보냈었는데 이처럼 그냥 한 요소만 반환되는 컴포넌트들도 default를 안 하는것이 좋은 것인가요?

2023-11-15 09:00 UTC, hoooooony commented
전화번호 입력할 때 하이픈 없이 입력하면 422에러 발생하는데 정규식 사용해서 해당 에러 방지해야 할 것 같아요!

2023-11-15 09:41 UTC, ChoiWonBeen commented on src/store/modalStore.ts
> +};
다시 보니 구조가 명확히 눈에 보인다는 점에서 기존 구조를 유지하는것도 상당한 장점을 가지는 것 같네요.
reduce나 forEach로 보니 가독성이 떨어지는듯. (이 값이 뭐지...하고)

2023-11-16 10:30 UTC, dooohun commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +  isNumber?: boolean;
`isNumber`를 작성하면 number 타입, 작성하지 않으면 text 타입을 나타내려고 선택적 속성을 사용했습니다.
제가 의도한 내용과 조금 다른 것 같아서 `isNumber`을 `inputType: HTMLInputTypeAttribute`으로 수정하여 inputType에 type을 작성하도록 했습니다.

2023-11-16 10:34 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/Category/index.tsx
>            <img className={styles.category__image} src={category.image_url} alt="" />
https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/25#discussion_r1346151632
저번 PR에서 달아주신 코멘트 참고하면 좋을 거 같아요!

2023-11-16 10:38 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +    const { name, phone } = JSON.parse(value);
헉! 너무 생각없이 코드를 짰네요...

2023-11-16 10:52 UTC, dooohun commented on src/component/common/CustomModal/index.tsx
> +  buttonText = '', title, height, hasFooter, isOpen, hasOverflow, onCancel, children,
모달을 사용하다 보면 모달 내에서 사용하는 값이 모달 경계를 넘을 때가 있는데 넘는 경우 `hasOverflow`를 작성하면 그 값이 보이게 하는 역할을 합니다.
`hasOverflow`는 제가 의도한 바가 제대로 전달이 안되는 것 같아서 `isOverflowVisible`로 수정했습니다.

2023-11-16 14:54 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  function handleClickStore(e: React.MouseEvent<HTMLButtonElement>) {
회의 때 이야기가 나왔었는데, **가게** 의미를 가진 단어는 `shop`으로 통일하기로 했습니다!
`store`를 전부 `shop`으로 수정했습니다. fcaabb0c179be34c5ca839d43a79fe0f0bbc7438

2023-11-16 15:11 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  let filteredShopList;
`filteredShopList`를 `useState`로 상태 관리하도록 수정했습니다. 23a605b7468c07a3ba30fbe63bc149fc16059b5d

궁금한 점이 있는데, `let의 사용은 지양한다`는 뜻이 **리액트**에서 let의 사용을 지양한다는 뜻인가요? 아니면 **위의 코드와 같은 상황**에서 let의 사용을 지양한다는 뜻인가요?

2023-11-17 02:12 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
>          <Magnifier type="button" className={styles['info__search-button']} />
엔터를 눌렀을 때, 돋보기 모양을 클릭했을 때 필터링 되는 기능을 추가했습니다!! 4437b7677dd6578c9f37020c061e4c28184ad924

2023-11-17 02:13 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/SearchStore/index.tsx
> +  const { shopList } = useAllShops();
`shopList`를 불러오지 못했을 때, 아래와 같이 `에러가 발생했습니다.` 라는 문구를 출력하도록 추가했습니다. 80e49fc832fc15ce0d42cf731dfdaf734e0f2770
``` javascript
{isError && <div>에러가 발생했습니다.</div>}
```

2023-11-17 05:32 UTC, junghaesung79 reviewed
우테코랑 pr 둘 다 고생하셨습니다ㅠㅠ
궁금한 부분 조금 적어두고 갑니다!

2023-11-17 05:32 UTC, junghaesung79 commented on src/component/common/CustomModal/index.tsx
> +        style={{ height }}
스타일을 인라인으로 적용할 경우에 대한 장점이 어떻게 될까요? 반응형처럼 값을 동적으로 넣을 수 있는 것이 제가 알고 있는 장점이에요. 그런데 이 컴포넌트를 사용한 부분에서는 그런 식으로 활용하고 있지 않는데 이 방법을 사용한 이유가 있다면 알고 싶습니다!😀

2023-11-18 06:14 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/Modal/Category/index.tsx
> +          }}
이펙트를 지 않는 전자가 좋아보이네여

2023-11-18 06:15 UTC, ChoiWonBeen commented on src/page/StoreRegistration/component/Modal/OperateTimePC/index.tsx
> +  };
마이너하지만 `handleStoreClosedChange` 처럼 쓰는건 어떨까요
`handleButtonClick` 이라고 하지 `handleClickButton`이라고는 잘 안쓰니..? (이건 팀 컨벤션 슬쩍 보고 정하면 좋을 것 같아요)

2023-11-20 14:13 UTC, haejinyun commented
안녕하세요! 코드 리뷰를 처음 남겨보는 것 같네요...!

먼저 한글 변수명을 쓰는 것도 새로웠고 많은 부분을 배웠던 것 같습니다!
구현하신 부분 중에서 모달창 부분과 관련해서 추가되면 좋을 것 같은 요소가 있어 코멘트 달아봅니다 😀

현재 모달창이 열린 상태에서 뒷배경에서 스크롤이 되고 있습니다.
모달창이 열려 있을 경우에는 뒷배경에 대한 스크롤은 방지가 되는 것이 좋지 않을까라는 생각입니다!
overflow에 제약을 두거나 eventListener를 활용해도 좋을 것 같습니다!

2023-11-20 14:27 UTC, haejinyun commented on src/page/ShopRegistration/view/PC/index.tsx
> +              <CustomModal
isOverflowVisible

2023-11-20 14:28 UTC, haejinyun reviewed
안녕하세요! 코드 리뷰를 처음 남겨보는 것 같네요...!

먼저 한글 변수명을 쓰는 것도 새로웠고 많은 부분을 배웠던 것 같습니다!
구현하신 부분 중에서 모달창 부분과 관련해서 추가되면 좋을 것 같은 요소가 있어 코멘트 달아봅니다 😀

현재 모달창이 열린 상태에서 뒷배경에서 스크롤이 되고 있습니다.
모달창이 열려 있을 경우에는 뒷배경에 대한 스크롤은 방지가 되는 것이 좋지 않을까라는 생각입니다!
overflow에 제약을 두거나 eventListener를 활용해도 좋을 것 같습니다!

2023-11-23 06:45 UTC, dooohun commented on src/api/shop/index.ts
> +export const getAllShopList = async () => {
변수명을 통일성 있게 수정했습니다! f3a5d3eea6f75c42e5e1a6aa33d88cc6c326a84b 85f1b2ea5f947083020db34e883e9b5afa37ef5d

2023-11-23 06:46 UTC, dooohun commented on src/api/shop/index.ts
> +export const postRegisterShop = (data: OwnerShop) => accessClient.post('/owner/shops', data);
말씀하신 내용대로 `postShop`으로 수정했습니다. f3a5d3eea6f75c42e5e1a6aa33d88cc6c326a84b

2023-11-23 06:48 UTC, dooohun commented on src/component/common/CustomModal/index.tsx
> +          [styles['container--selected']]: !!hasOverflow,
원래 의도는 모달의 overflow가 `visible`일 때와 아닐 때를 구분하기 위해서 `hasOverflow`라고 작성했는데, 이 부분이 의도대로 전달이 안된 것 같습니다. 그래서 `isOverflowVisible`로 수정했습니다. 19cc4657183edc062b8569abb7220429b41a01d6

2023-11-23 06:49 UTC, dooohun commented on src/page/StoreRegistration/component/InputBox/index.tsx
> +      />
다른 타입으로 지정될 경우를 고려하지 않은 것 같습니다... `number`, `text` 이외에 다른 Input 타입을 추가했습니다. c30e6df261db75fb7b95b84f9f4842b30ea4d950

2023-11-23 06:54 UTC, dooohun commented on src/store/modalStore.ts
> +export default useModalStore;
모달에서 사용하는 값(카테고리 값, 가게 검색 값, 운영 시간 값)을 저장하는 의미로 `useModalStore`라고 지었습니다.

2023-11-23 06:54 UTC, dooohun commented on src/store/modalStore.ts
> +export default useModalStore;
> 이 훅은 Store의 기능에 집중하는게 맞는 것 같아요. store를 다루는 훅이니?

모달에서 사용하는 값(카테고리 값, 가게 검색 값, 운영 시간 값)을 저장하는 의미로 `useModalStore`라고 지었습니다.

2023-11-23 06:57 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +  };
이미지 파일 변환 로직은 따로 `utils/hooks` 에 `useImageUpload`라는 이름으로 분리했습니다.

2023-11-23 06:58 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +  };
이미지 파일 변환 로직은 따로 `utils/hooks` 에 `useImageUpload`라는 이름으로 분리했습니다. 9b5ff4f4e18c3cb3f1675b3026f4ec28c494fb1b

2023-11-23 07:01 UTC, dooohun commented on src/store/modalStore.ts
> +  categoryState: [string, number];
카테고리의 `id`와 `카테고리명`이 필요해서 string과 number라고 타입 지정을 했습니다!

2023-11-23 07:10 UTC, dooohun commented on src/page/StoreRegistration/view/PC/index.tsx
> +  const [operateTimeState, setOperateTimeState] = useState<OperateTimeProps>({});
`Record<>` 타입은 처음 써보네요... 😢 자주 사용하도록 하겠습니다! 1fe134b891d58a5602e29c753d022943e007655b

2023-11-23 07:13 UTC, dooohun commented on src/store/modalStore.ts
> +  setCloseTimeState: (state: { [key in typeof WEEK[number]]: string | null }) => void,
지금 보니 중복되는 부분도 많고 복잡해보이네요! 따로 `OperatingTime`으로 정의했습니다! 073da355e660a61633e609647e9defeccb940f82

2023-11-24 11:23 UTC, dooohun commented on src/page/StoreRegistration/component/InputBox/index.tsx
>  interface InputProps {
통일성 있게 `InputBoxProps`로 수정했습니다! 7aebeeef2c8d169fd628b2d739ad75524225150c

2023-11-24 11:24 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/Category/index.tsx
> +          }}
오 전자로 하는 게 더 깔끔해보이네요👍 dc8531f3d9f516817fbbee6ae639015c88f6b789

2023-11-24 11:24 UTC, dooohun commented on src/page/StoreRegistration/component/Modal/OperateTimePC/index.tsx
> +  };
이전 상태를 고려하도록 코드를 수정했습니다! bdcfdc8584f2334b970c6eca3112ea2227c954a5

2023-11-24 11:29 UTC, dooohun commented on src/page/ShopRegistration/view/PC/index.tsx
> +              <CustomModal
오버레이 스크롤 제어에 대해서는 생각하지 못한 것 같네요... 해당 내용 새로 추가했습니다!! 4018363a1b9d83749798a14fdc9414b9fca1cfb8

2023-11-24 12:04 UTC, dooohun commented on src/component/common/CustomModal/index.tsx
> +        style={{ height }}
특별한 이유는 없습니다. UI를 만드는 것에 집중하다보니 말씀하신 부분을 고민하지 않고 코딩한 것 같네요...
`height`를 `modalSize`로 수정해서 `small` `medium` `large` 세 단계로 나누도록 수정했습니다! 8e9ce227d7fc10e4d7ae154903bba22efeb852c8

2023-11-24 12:05 UTC, dooohun commented
@hoooooony 리뷰 남겨주신 전화번호 입력 부분은 값을 입력하면 하이픈이 추가되도록 기능을 추가했습니다! bbdff9335f3e4cc4db3d01c1826530aa851a6534

2023-11-27 04:31 UTC, hoooooony approved these changes

2023-11-28 10:42 UTC, junghaesung79 approved these changes

2023-11-28 13:40 UTC, dooohun commented
@HAEROOL 상점 전체 목록을 불러오는 `getShopList`를 토큰 없이 요청 가능하게 수정했습니다! ad2fc39f523bf893e7470406668de1d74ed0b11a

2023-11-29 07:58 UTC, MinGu-Jeong approved these changes

2023-11-29 13:57 UTC, hanagertrudekim approved these changes

2023-11-29 15:13 UTC, merged