[공통] 로그인 된 상태에서 새로고침 시 로그인 화면 리다이렉트되는 문제
BCSDLab/KOIN_OWNER_WEB pull request #306
Opened 2024-05-01 03:19 UTC by junghaesung79

- Close #251 
  
## What is this PR? 🔍

- 기능 : 로그인 된 상태에서 새로고침 시 로그인 화면 리다이렉트되는 문제
- issue : #251 

## Changes 📝

기존 js코드에서만 userType을 관리했었는데, 이로 인해 발생하던 새로고침 시 로그인창을 갔다오는 문제를 해결했습니다.
userType을 access token과 같이 세션스토리지에 넣고 새로고침 시 이것을 가져와서 로그인 된 상태를 바로 적용하였습니다.

## ScreenShot 📷

## Test CheckList ✅

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] Did you merge recent `develop` branch?

2024-05-01 09:00 UTC, KimKyungYun reviewed
고생하셨습니다~ 세션스토리지에서 zustand를 이용해서 상태를 관리하는 방법에 대해 추가적인 의견하나 작성하였습니다!

2024-05-01 09:00 UTC, KimKyungYun commented on src/store/useUserTypeStore.ts
>  const useUserTypeStore = create<UserTypeStore>((set) => ({
세션스토어에 따로 저장하는 동작을 추가하지 않아도 Zustand의 persist를 이용해서 storage를 sessionStorage로 저장하는 방법이 더 핸들링하기 간단할 것 같습니다ㅎ 
해당 방법도 한번 찾아보고 적용해보시면 더 좋을 것 같습니다!

2024-05-01 12:40 UTC, chaeseungyun requested changes

2024-05-01 12:40 UTC, chaeseungyun commented on src/store/useUserTypeStore.ts
> +        }
기존에 자동로그인되어 있어서 user_type이 세션스토리지에 저장 되어있지 않은 유저의 경우 어떻게 되나요??

2024-05-02 02:05 UTC, hoooooony approved these changes

2024-05-02 06:25 UTC, junghaesung79 commented on src/store/useUserTypeStore.ts
> +        }
해당 경우는 15번째 줄 if에 걸려서 서버에서 유저타입을 받은 후 세션에 유저타입을 저장하게 됩니다.

2024-05-02 08:06 UTC, junghaesung79 commented on src/store/useUserTypeStore.ts
>  const useUserTypeStore = create<UserTypeStore>((set) => ({
네! 확실히 persist를 이용하니 빠르게 유저 타입을 불러와서 불편한 깜빡임도 안 생기네요! 감사합니다^^

2024-05-02 09:51 UTC, chaeseungyun approved these changes

2024-05-02 11:15 UTC, merged