[회원가입] 회원가입 페이지 API 연동
BCSDLab/KOIN_OWNER_WEB pull request #34
Opened 2023-12-13 17:09 UTC by HAEROOL

## [#2 ] request

회원가입 페이지의 회원가입 기능을 완료했습니다.
가게 검색의 경우 모바일 뷰가 구현되지 않아 구현 완료되면 추가로 적용하겠습니다. 
가게 검색에서 선택된 가게는 가게 이름과 전화번호 외에도 `shop_id`를 추가적으로 저장하도록 변경했습니다.

- 사장님 데이터(가게 이름, 대표자 이름, 가게 등록 번호, 대표자 전화번호, 관련 파일 업로드 ) 회원가입 데이터에 추가
- 입력한 데이터 기반으로 회원가입 기능

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img width="1470" alt="스크린샷 2023-12-14 오전 1 50 54" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/63447bf8-790e-492c-b4d3-3862e8b26561">

<img width="1470" alt="스크린샷 2023-12-14 오전 1 52 14" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/333a253f-b09f-479a-8cbd-9491cc9b9c11">

<img width="1470" alt="스크린샷 2023-12-14 오전 1 51 26" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/48c21b7d-c0dd-468d-a515-245668dbbf22">

### Precautions (main files for this PR ...)

2023-12-18 19:21 UTC, MinGu-Jeong reviewed
수고하셨습니다!
`store` 변수명으로 쓰인 곳이 너무 많아 `shop`변수명으로 통일하는 것이 쉽지 않을것 같단 생각이 듭니다...🥲
관련하여 추후 회의때 다시 한 번 얘기해보는 것도 괜찮을 것 같기도 합니다.

2023-12-18 19:21 UTC, MinGu-Jeong commented on src/page/Auth/Signup/hooks/useOwnerData.ts
> +  owerName: '대표자명을 입력해주세요',
오타있어요!!
```suggestion
  ownerName: '대표자명을 입력해주세요',
```

2023-12-18 19:21 UTC, MinGu-Jeong commented on src/page/Auth/Signup/view/OwnerDataPage/index.tsx
> +  const onSumbmit = () => {
오타입니다!!
```suggestion
  const onSubmit = () => {
```

2023-12-19 11:15 UTC, daepan requested changes
수고하셨습니다. 코멘트 한번 확인해주시고 수정해주시면 될 것 같네요

2023-12-19 11:15 UTC, daepan commented on src/page/Auth/Signup/component/CustomButton/index.tsx
> +  buttonSize: 'small' | 'mobile' | 'large' | 'mobile-small',
mobile-small을 추가하셨는데 각 사이즈 별로 px 기준이 있을까요? 따로 px 기준을 주석으로 남겨주면 좋을 것 같아요

2023-12-19 14:08 UTC, dooohun reviewed
수고하셨습니다!

2024-01-02 06:09 UTC, HAEROOL commented on src/page/Auth/Signup/component/StoreSearch/index.tsx
> +  const [selectedStore, setStore] = useState<null | number>(null);
`shop` 대신 `store`로 통일하는 것으로 헷갈렸네요....수정 완료 했으며 수정 도중 해당 컴포넌트와 `Toast`컴포넌트를 사용하지 않아 삭제했습니다!

2024-01-02 06:40 UTC, HAEROOL commented on src/page/Auth/Signup/component/CustomButton/index.tsx
> +  buttonSize: 'small' | 'mobile' | 'large' | 'mobile-small',
확인했습니다! 지금 생각해보니 이렇게 계속해서 버튼 스타일이 늘어난다면 size를 props 받는 방법도 생각해 봐야 할 것 같네요...

2024-01-02 06:56 UTC, HAEROOL commented on src/page/Auth/Signup/component/UserEmail/UserEmail.module.scss
> +      height: calc(48px - 30px);
height의 값이 저렇게 나온 이유를 명시적으로 표현해 보려 했는데, 오히려 헷갈릴 수도 있겠네요...수정완료했습니다!

2024-01-02 06:58 UTC, HAEROOL commented on src/page/Auth/Signup/component/UserEmail/index.tsx
> +                : <span className={styles['email-check__alert']}>* 제한시간 5 : 00</span>}
제한시간의 경우 피그마에 명시 되어 있지 않아서 따로 구현하지 않았는데, 구현하는 것이 좋겠네요. 차후에 이슈 생성해서 구현해 보겠습니다.

2024-01-02 07:06 UTC, HAEROOL commented on src/page/Auth/Signup/hooks/useFileController.ts
> +  const { ownerInfo, setOwnerInfo: setUploadedFiles } = useRegisterInfo();
해당 훅에서 업로드할 파일만을 변경하기 때문에 이름을 바꿔 사용했지만, 지금 생각해보니 혼동이 올 수도 있을 것 같네요. 변경했습니다!

2024-01-02 16:04 UTC, hanagertrudekim requested changes
수고많으셧습니다~ 리뷰가 늦었네요 
코드량이 전체적으로 많아서 리뷰하는데 조금 시간이 걸렸습니다ㅎㅎ
구조적으로 리팩토링할게 있어보이지만, 우선 빠르게 리뷰들 확인해주세요!

2024-01-02 16:04 UTC, hanagertrudekim commented on src/api/register/index.ts
> +  });
이건 api/index.ts 쪽으로 빼줘도 될것같아요! 다른곳도 공통으로 들어갈 부분이라서 `multipartClient` 정도의 느낌으로 분리해줘도 좋을것같아요.

2024-01-04 07:07 UTC, HAEROOL commented on src/query/register.ts
> +};
확인했습니다. 차후에 비슷한 에러형식들 찾아서 구현을 해야 될 것 같네요.

2024-01-04 12:56 UTC, HAEROOL commented on src/api/register/index.ts
> +  });
완료했습니다!

2024-01-04 13:48 UTC, hanagertrudekim commented on src/page/Auth/Signup/component/UserEmail/index.tsx
> +            { formErrors.email && <ErrorMessage message={formErrors.email.message} />}
네 좋은것같아요ㅎㅎ

2024-01-04 13:50 UTC, hanagertrudekim approved these changes
수고하셨습니다!

2024-01-05 03:41 UTC, hoooooony commented
수고하셨습니다!!

2024-01-06 11:00 UTC, merged