[비즈니스] 비밀번호 찾기 문자인증 도입
BCSDLab/KOIN_OWNER_WEB pull request #349
Opened 2024-06-07 11:26 UTC by chaeseungyun

- Close #ISSUE_NUMBER
  
## What is this PR? 🔍

- 기능 : 비밀번호 찾기 문자인증 도입
- issue : #

## Changes 📝

이제 비밀번호 찾기를 문자 인증을 통해 진행합니다.
아직 전화번호를 통한 회원가입 페이지가 완성되지 않아서 전화번호 회원가입은 스웨거를 통해 해야한다는 불편함이 있습니다.

@hoooooony 님은 제 pr 머지된 후 SMS 브랜치 머지 받고 작업 마무리하시면 될 것 같습니다.
회원가입을 위한 api를 호출하기 위해 완료 버튼이 있는 CommonLayout 컴포넌트에 함수를 호출하고 사용하시면 됩니다.

## ScreenShot 📷
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101871802/0a2ffd9f-26ef-42e6-87b6-b01cbba1f623)
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101871802/f0aa007f-f0a0-485c-a233-b6724572f166)
![image](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/101871802/09e6a8f5-a6bc-4af5-b645-0cc2f6f6cbca)

## Test CheckList ✅

- [ ] test 1
- [ ] test 2
- [ ] test 3

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `yarn lint`

2024-06-08 05:34 UTC, daepan requested changes
한번 확인해주세요!

2024-06-08 05:34 UTC, daepan commented on src/page/Auth/FindPassword/ChangePassword/index.tsx
> +  } = method;
```suggestion
const {
    register, formState: { errors, isValid }, getValues, clearErrors,
  } = useFormContext<ChangePasswordForm>();
```
요렇게 해도 좋을 것 같은데 따로 분리하신 이유가 있을까요?

2024-06-08 05:34 UTC, daepan commented on src/page/Auth/FindPassword/ChangePassword/index.tsx
> +
정리한번 부탁드립니다.

2024-06-08 05:34 UTC, daepan commented on src/page/Auth/FindPassword/ChangePassword/index.tsx
> +          )}
여기도!

2024-06-08 05:34 UTC, daepan commented on src/page/Auth/FindPassword/Verify/index.tsx
> +  } = method;
이것도 위와 동일하겠네요

2024-06-08 08:37 UTC, chaeseungyun commented on src/page/Auth/FindPassword/ChangePassword/index.tsx
> +  } = method;
꺼내쓰는 방식에 익숙해져서 습관처럼 이렇게 작성한 것 같습니다..
수정하겠습니다

2024-06-08 08:44 UTC, chaeseungyun commented on src/page/Auth/FindPassword/ChangePassword/index.tsx
> +
ad8b69a0eadf43912ef20980cc4ffd76896c155b 이렇게 해봤습니다. 맞나용??

2024-06-09 07:07 UTC, daepan approved these changes
수고하셨습니다.

2024-06-10 02:18 UTC, merged