[비밀번호 찾기] 새로운 비밀번호로 변경하기 로직 구현
BCSDLab/KOIN_OWNER_WEB pull request #35
Opened 2023-12-18 12:10 UTC by MinGu-Jeong

## [#26 ] request

- 새로운 비밀번호로 변경하는 기능을 구현했습니다.
    - 테스트 계정
        - id: mingu830@gmail.com
        - pw: test123!
        
- 비밀번호 찾기 기능이 로직적으로는 구현이 완료되어 정상적으로 사용하는데 문제는 없으나, 추후 리팩토링이 필요합니다.
- 다음 PR에 반영되어 리팩토링되거나 추가 될 내용은 다음과 같습니다.
    - 이메일 입력 후 인증번호 발송 시 잘못된 이메일 입력 했을 때 렌더링되는 적절한 UI
    - 새로운 비밀번호 입력 시 비밀번호 작성 규칙 검증 로직 추가
    - 비밀번호 작성 규칙에 어긋난 비밀번호 작성 시 렌더링되는 적절한 UI
    - 다른 로직에서도 사용할 수 있도록 추상화 된 useRouteCheck Hook

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `develop` branch?

### Screenshot
<img width="49%" alt="스크린샷 2023-12-18 오후 6 45 10" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/96a3dde1-5160-487d-90d2-869327cc5391">
<img width="49%" alt="스크린샷 2023-12-18 오후 6 45 47" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/1f3185b1-bdec-49fe-9c17-9499e8d9fdea">
<img width="50%" alt="스크린샷 2023-12-18 오후 6 46 11" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/14ea1743-62d9-4fa6-95af-aadcccc39ac6">

### Precautions (main files for this PR ...)

2023-12-19 12:10 UTC, daepan approved these changes
고생하셨습니다. Lint에러 수정해주세요

2023-12-19 12:10 UTC, daepan commented on src/page/Auth/FindPassword/hooks/useRouteCheck.ts
>    }, [location.state, navigate, entryRoute, prevRoute]);
👍

2023-12-21 10:22 UTC, dooohun reviewed
수고하셨습니다!

2023-12-21 10:22 UTC, dooohun commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +              autoComplete="off"
`autoComplete`는 처음봐서 찾아봤는데, 굉장히 좋은 기능인 것 같아요!
비밀번호를 작성하기 때문에 `autoComplete`를 `off`하는 디테일..!👍

2023-12-21 10:22 UTC, dooohun commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
인증번호를 잘못 입력했을 때, 잘못 입력했다고 알려주는 기능이 필요할 것 같아요
에러 문구를 새로 만들거나, 혹은 인증번호 입력하는 칸에 빨간색으로 표현을 해주는 방법이 있을 것 같아요!

2023-12-21 10:22 UTC, dooohun commented on src/page/Auth/FindPassword/NewPassword/index.tsx
비밀번호 입력에 경우 잘못된 입력을 나누어서 표현 가능 할 것 같아요
1. 새 비밀번호 입력을 조건(`특수문자 포함 영어와 숫자 조합 6~18자리`)에 맞추지 않은 경우
2. 새 비밀번호 입력과 비밀번호 확인이 맞지 않는 경우
이 두가지 경우를 나누어서 표현하는 것도 괜찮은 것 같아요!

예를 들어 1번의 경우 `특수문자 포함 영어와 숫자 조합 6~18자리` 문구에 빨강색으로 표현한다던가,
2번의 경우 비밀번호 확인 `input 테두리`를 빨강색으로 표현하는 방법이 떠오르네요!

2023-12-21 10:59 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/SendAuthNumber/index.tsx
다음 PR에 반영해서 구현하겠습니다!

2023-12-28 05:53 UTC, hanagertrudekim requested changes
리뷰가 늦어 죄송합니다..ㅎㅎ 수정되는대로 빠르게 어프로브할게요!

2023-12-28 05:53 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +  useRouteCheck('nextStep', '/new-password');
아니면 prevRoute라는 key 값을 정해진 문자나 상수로 두는건 어떨까요? 
useRouteCheck 쪽에서 key 형식을 좀 정해서, 클라이언트 쪽에서 맞춰서 넘겨주는것도 좋을것같아요.

2023-12-28 05:53 UTC, hanagertrudekim commented on src/store/useAuth.ts
> +export default useAuthStore;
인증 store인데 묘하게 email에만 관심사가 집중된것같아요. 나중에 인증 관련해서 확장될 여지가 있을까요?
+ Input이라는 말이 store에서 쓰여도되는지 궁금하네요

2023-12-28 12:08 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +          className={styles.submit}
`form__button`으로 수정했습니다! 2f78e71b7ed64773940c7bda4c3129c82c01be92

2023-12-28 13:18 UTC, MinGu-Jeong commented on src/store/useAuth.ts
> +export default useAuthStore;
일단 이메일 **인증**기능이여서 `인증store`로 네이밍 짓기는 했으나, 추후 확장할 부분이 있을지는 당장은 모르겠네요🥲
`이메일인증store`로 네이밍을 수정하고 추후 기능이 확장된다면 그때 다시 `인증store`로 변경하도록 하겠습니다! e6e81bf753d55890e20853ebb8d018652fad0097

추가적으로 Input이라는 용어자체로는 현재 사용하는데 문제는 없습니다. 혹시 네이밍컨벤션쪽으로 문제가 있을까요??

2023-12-29 06:50 UTC, junghaesung79 reviewed
고생하셨습니다! 몇 가지 궁금한 부분 적어 둘게요!

2023-12-29 06:50 UTC, junghaesung79 commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +        <button type="button" className={styles.content__button} onClick={() => navigate('/login')}>로그인 화면 바로가기</button>
3개가 넘는 프로퍼티를 가지는 태그는 개행을 사용해서 표현하는 것도 좋을 것 같아요!😀

그리고 navigate 함수는 handleSubmit 같은 함수 안에서 이벤트 처리 등의 로직 후에 페이지 이동이 필요할 경우 사용하는 것이 좋다고 생각합니다! SEO를 고려하면 button 태그보다 Link 컴포넌트를 사용하는 게 좋을 것 같다고 생각하는데 이에 대해 어떻게 생각하시나요?🤔

2023-12-29 06:50 UTC, junghaesung79 commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        >
handleSubmit으로 빼는 것도 좋을 것 같아요!

2023-12-29 06:50 UTC, junghaesung79 commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +        <button type="button" className={styles.content__button} onClick={() => navigate('/login')}>로그인 화면 바로가기</button>
그리고 return문 앞에 개행이 있으면 좋겠어요.😉

2023-12-29 09:25 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +        <button type="button" className={styles.content__button} onClick={() => navigate('/login')}>로그인 화면 바로가기</button>
개행을 추가했습니다 d6924c62804977dfe0456bc30461e869dcbc02c7
<img width="403" alt="image" src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/51395707/c9d9dded-045a-497a-8ed2-da2b3432beaa">
Link 컴포넌트를 사용하니깐 원하는대로 디자인이 안되네요🥲
로그인 화면 바로가기 버튼은 SEO를 크게 고려할 내용이 아닐 것 같아 괜찮을것 같다는 생각이 드네요

2023-12-29 09:38 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        >
이미 `submit`함수가 분리 된 함수라서 더 분리하기가 쉽지 않을 것 같네요😅

2023-12-29 10:58 UTC, hanagertrudekim commented on src/store/useAuth.ts
> +export default useAuthStore;
input은 입력필드나 입력요소 등으로 이해할수있는데, zustand 의 관심사는 input을 핸들링하기보다는 input의 정보를 관리하는것이라고 생각해요. 따라서 `email`, `setEmail`등이 더 적합하지 않을까요??

2023-12-29 13:16 UTC, junghaesung79 commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +        <button type="button" className={styles.content__button} onClick={() => navigate('/login')}>로그인 화면 바로가기</button>
스타일을 적용하는 것에서 어려움을 겪고 있는 것이라면 태그 별 기본 스타일을 검색해보시는 것을 추천드려요😀
Link 컴포넌트는 내부적으로 a 태그를 렌더링하는데 a 태그의 기본 스타일과 div의 기본 스타일을 보고 적절히 적용하면 원하는 스타일을 만들어낼 수 있을 거에요!

2023-12-29 13:27 UTC, junghaesung79 commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        >
저는 개인적으로 onClick 인라인 방식을 함수가 한 개일 때만 사용해요. 만약 두 줄이 넘어가면 따로 handle~~로 빼내서 정리하는 게 보기 편할 것이라고 생각했어요.

2023-12-31 06:23 UTC, dooohun approved these changes

2023-12-31 13:37 UTC, ChoiWonBeen commented on src/store/useEmailAuth.ts
> +}));
zustand는 [persist]
(https://docs.pmnd.rs/zustand/integrations/persisting-store-data#name) 라는 기능을 지원하는데, 이거도 같이 사용해보면 좋을 것 같아용

2024-01-02 09:01 UTC, MinGu-Jeong commented on src/store/useAuth.ts
> +export default useAuthStore;
적절한 변수명으로 수정했습니다! 526c7b4df981f86d35e3ae10ce76a8cd90fd3149

2024-01-02 11:30 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/NewPassword/index.tsx
> +        >
함수로 분리했습니다! 2dd26a80589f9fbe980a68adbd0c9fc17128ea7e

2024-01-02 19:58 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +  useRouteCheck('nextStep', '/new-password');
`Route`이름을 가진 enum형 타입을 정의하였습니다.
`prevRoute`는 `Route`타입을 가지며 `Route` 타입은 `NEXT_STEP`값 만 가지고 있기 때문에 `NEXT_STEP` 이외의 값을 입력하면 에러를 발생시키도록 하였습니다.

요렇게 수정하면 괜찮을까요?? e4d884f531b6cfff7123c8b8f33faab474d98909

2024-01-02 20:09 UTC, MinGu-Jeong commented on src/store/useEmailAuth.ts
> +}));
zustand persist기능을 사용하여 이메일값이 세션스토리지에 저장되도록 하여 비밀번호 변경 중 새로고침을 하더라도 이메일값이 보존되도록 하였습니다. c326527b4fc5531118ba3f4de27dbcc636119c26

2024-01-03 08:20 UTC, hanagertrudekim commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +  useRouteCheck('nextStep', '/new-password');
저도 관련해서 더 찾아보니, enum은 불변하는 상수 열거형에 더 효과적인것같아요. 또한 enum type을 사용하고 나중에 확장한다고 했을때,  [tree shaking](https://velog.io/@ahsy92/TypeScript-Enum%EC%9D%B4%EB%9E%80#enum%EC%9D%98-%EB%AC%B8%EC%A0%9C%EC%A0%90) 이 어렵다는 이야기도 있네요...😅
 
 차라리 prevRoute 를 literal type으로 선언해버리는건 어떨까요? 그럼 쓰이는 쪽에서는 간단히 타입 에러만 뱉어내니까, 체크해줄수있을것같아요. 

+minor comment
1. prevRoute 도 추상적인 `nextStep`보다는 entryRoute의 도메인을 이용해 `new-password`로 아예 지정해버리는것도 좋을것같은... 하나의 의견을 내봅니다ㅎㅎ 
2. 그치만 추상화 관점에서는 안좋을것같아서, 둘중에 적당한 방식을 선택해주세요ㅎㅎ
 
```tsx
ex)
type Route = 'nextStep';
or 
type Route =  'new-password' | 'find-password';

export const useRouteCheck = (prevRoute: Route, entryRoute: string) => {
```

그러면 usage는 예전과 동일해질것같아요!
```tsx
useRouteCheck('new-password' '/new-password');
useRouteCheck('new-id' '/new-password'); // Type Error!
```

2024-01-03 16:09 UTC, MinGu-Jeong commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +  useRouteCheck('nextStep', '/new-password');
``` typescript
type Route = 'nextStep';
```
```typescript
type Route =  'new-password' | 'find-password';
```
중 고민하다 후자를 선택했습니다. 93334f07eacfc87ffab784a64c7c7c7d60de87e0
현재는 라우트 체크할 부분이 2개밖에 없어 후자를 사용해도 크게 문제가 안되지만 추후 라우트체크를 할 부분이 많아진다면 모든 페이지를 리터럴 선언하기엔 쉽지 않을 것 같단 생각이 드네요😀

나중에 라우트체크할 부분이 많아져 리터럴 관리가 어렵다면 그때 전자처럼 `nextStep`으로 사용하면 될 것 같습니다!

2024-01-04 06:05 UTC, hanagertrudekim approved these changes
수고하셨습니다~

2024-01-04 06:10 UTC, HAEROOL reviewed
수고하셨습니다!

2024-01-04 08:58 UTC, merged

2024-01-04 15:06 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +  useRouteCheck('nextStep', '/new-password');
조금 늦은거같지만 그냥 상수 전역변수로 배열로 둠은 어땠을까 싶기도 하네여
가져다쓰기쉬움, 순서적용가능, treeShaking문제해결 등등.. 다만 이 값을 관리하는게 누구의 역할이 될지가 애매해지긴 하네요
```ts
export const NEW_PASSWORD_FUNNEL = ['new-password', 'find-password', 'complete'] as const;
```

2024-01-04 15:07 UTC, ChoiWonBeen commented on src/page/Auth/FindPassword/CompleteChangePassword/index.tsx
> +        <button type="button" className={styles.content__button} onClick={() => navigate('/login')}>로그인 화면 바로가기</button>
> 3개가 넘는 프로퍼티를 가지는 태그는 개행을 사용해서 표현하는 것도 좋을 것 같아요!😀

요것도 린트 룰로 추가하면 좋겠네여