[가게 등록] 모바일 가게 등록 페이지 로직 및 API 구현
BCSDLab/KOIN_OWNER_WEB pull request #37
Opened 2023-12-31 07:56 UTC by dooohun

## [#32] request
- 모바일 가게 등록 기능 구현 했습니다.
- 기존에 PC 버전에서 작성했던 로직과 API를 그대로 사용했습니다.
- PC 버전과 모바일 버전에서 `대표자명`을 제외한 모든 입력값들은 공유 가능하게 기능을 추가했습니다.

## Please check if the PR fulfills these requirements

- [ ] It's submitted to `develop` branch, __not__ the `main` branch
- [ ] The commit message follows our guidelines
- [ ] Did you merge recent `deveop` branch?

### Screenshot
<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/10a2a08c-31da-4657-b0cb-0d9ad57f80ad" width="40%" height="40%" />

<img src="https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/74540646/c6acd579-4141-4893-ba36-b3b17b618e32" width="40%" height="40%" />

### Precautions (main files for this PR ...)

2024-01-02 08:04 UTC, HAEROOL requested changes
![스크린샷 2024-01-02 오후 5 02 25](https://github.com/BCSDLab/KOIN_OWNER_WEB/assets/71335694/49b27dc7-09fb-478e-b65b-d459a7e4fa1c)

현재 아무 정보도 입력하지 않고 다음 버튼 클릭을 해도 step이 진행되는 경우가 생기네요. 이 경우의 에러 처리를 해두면 좋을 것 같습니다!

2024-01-03 08:32 UTC, hanagertrudekim requested changes
수고하셨습니다! 간단한 코멘트들 확인해주세요🙂

2024-01-03 08:32 UTC, hanagertrudekim commented on src/page/ShopRegistration/view/PC/index.tsx
> +                    ? <img src={imageUrl} className={styles['form__main-menu']} alt="" />
alt를 비워두기보다는 간단히 설명추가해줘도 좋을것같아요.
```suggestion
                  {imageUrl
                    ? <img src={imageUrl} className={styles['form__main-menu']} alt="메인 메뉴" />
```

2024-01-03 08:32 UTC, hanagertrudekim commented on src/utils/hooks/useImageUpload.ts
> +  const { imageUrl, setImageUrl } = useShopRegistrationStore();
해당 로직에 useShopRegistrationStore hook 이 쓰인 이유가 있나요??
이렇게되면 공통으로 빼놓은 이미지 업로드 hook이 shopRegistrationStore data에 종속되는 현상이 일어날것같아요.

2024-01-04 08:46 UTC, dooohun commented
@HAEROOL 
입력할 때 필수적으로 들어가야 되는 값이 들어가지 않으면 다음 페이지로 넘어가지 않도록 수정했습니다! be6b14721b2050559086e46ce3ffc84d6dac09e7

2024-01-04 08:47 UTC, dooohun commented on src/page/ShopRegistration/view/PC/index.tsx
> +                    ? <img src={imageUrl} className={styles['form__main-menu']} alt="" />
alt에 `메인 메뉴` 설명 추가했습니다. 03f24d50c8546ad09b53f28417bcb2d9c6395094

2024-01-04 08:51 UTC, dooohun commented on src/utils/hooks/useImageUpload.ts
> +  const { imageUrl, setImageUrl } = useShopRegistrationStore();
공통으로 빼놓은 훅이라고 생각하지 못하고 코드를 작성한 거 같습니다...
기존에 작성했던대로  `useState`로 수정하고, PC와 Mobile에 각각 shopRegistrationStore를 통해 상태를 관리하도록 수정했습니다! 06e25fbf5e01a76f978f7b5d11f691bd52bc7b7b 9a45abfad75a5899c0fd3b912b90fcd49dc5982f

2024-01-04 10:29 UTC, hanagertrudekim commented on src/page/ShopRegistration/component/Modal/Category/index.tsx
> +          <img className={styles.category__image} src={categoryInfo.image_url} alt="" />
여기도 alt 한번씩 확인해주세요
```suggestion
          <img className={styles.category__image} src={categoryInfo.image_url} alt="카테고리 이미지" />
```

2024-01-04 10:31 UTC, hanagertrudekim commented on src/page/ShopRegistration/view/Mobile/Main/index.tsx
> +          ? <img src={imageUrl} className={styles['form__main-menu']} alt="" />
여기도 필요할것같네요
```suggestion
          ? <img src={imageUrl} className={styles['form__main-menu']} alt="메인 메뉴" />
```

2024-01-04 10:38 UTC, hanagertrudekim commented on src/page/ShopRegistration/view/Mobile/Sub/index.tsx
> +    } else increaseStep();
여기 alert 부분은 린트에 걸리니까, 빼두는게 좋을것같아요.
지금 해루님 Pr에 같은 코멘트가있어서 나중에 알림 컴포넌트를 따로 생성할것같은데, 추후에 확인하기 편하도록 주석처리 해두는게 좋을것같네요ㅎㅎ

2024-01-04 10:39 UTC, hanagertrudekim approved these changes
위의 추가 코멘트들만 확인해주세요~!

2024-01-04 13:43 UTC, dooohun commented on src/page/ShopRegistration/component/Modal/Category/index.tsx
> +          <img className={styles.category__image} src={categoryInfo.image_url} alt="" />
수정했습니다! bca13ecdf5355922a4fdb420e4bcb01bcf3e6a59

2024-01-04 13:44 UTC, dooohun commented on src/page/ShopRegistration/view/Mobile/Main/index.tsx
> +          ? <img src={imageUrl} className={styles['form__main-menu']} alt="" />
수정했습니다! bca13ecdf5355922a4fdb420e4bcb01bcf3e6a59

2024-01-04 13:45 UTC, dooohun commented on src/page/ShopRegistration/view/Mobile/Sub/index.tsx
> +    } else increaseStep();
alert 삭제하고 따로 주석처리 해놓았습니다! 39da30a1ea97f42a4bd4e5c555f1e5711c3367f8

2024-01-06 06:22 UTC, MinGu-Jeong approved these changes
수고하셨습니다!

2024-01-07 14:01 UTC, HAEROOL reviewed
수고하셨습니다!

2024-01-07 14:02 UTC, HAEROOL approved these changes

2024-01-07 14:08 UTC, merged