[로그인] 로그인 페이지 추가
BCSDLab/KOIN_OWNER_WEB pull request #6
Opened 2023-04-24 07:23 UTC by hanagertrudekim

## [#1] request

### 로그인 페이지 UI 추가
- 로그인 pc, 모바일 UI 완료
- `AuthLayout` 기본 레이아웃 설정
- font 모듈 `scss` 추가
- 글꼴 `woff` 파일 추가

### 로그인 api 연결

- login 관련 zod 스키마 정의, API response 검증 적용
- ErrorBoundary 에러 처리를 위임
-> react-query 내부 요청 에러는 `isError`를 통해 핸들링, zod에러는 에러 바운더리로 `throw`
-> `getMe()` api에는 `useQuery`를 적용하는것이 맞지 않아, zod에러를 `throw` 하기 위해 Mutation에서 한 분기에 처리해주었습니다.
**`Error` 컴포넌트는 아직 대체 ui 시안이 없어, 추후 수정예정 
- `sessionStorage` 토큰 핸들링
- 전역 `store`에 유저 정보 저장

### Test account 
- id : `rlagksk8428@gmail.com`
- password: `gjffhdn121!` 
 
### Precautions (main files for this PR ...)
- `query/auth.ts`
- `store/auth.ts`
- `page/Login/index.ts`
- `component/common/Error.tsx`, `component/common/ErrorBoundary.tsx`
- `layout/AuthLayout/index.tsx`

### Screenshot
<img width="500" alt="image" src="https://user-images.githubusercontent.com/101982606/233922159-01d1bb2e-79bf-4fa1-983d-61ebd5546fb2.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/101982606/233922237-8d27fa4c-15bf-4c35-aae7-77544b9877b5.png">

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

2023-04-25 02:08 UTC, hanagertrudekim commented on src/page/Auth/Login/static/option.ts
> +    path: '',
아이디찾기는 아직 따로 링크가 없어서 설정해주지 않았습니다

2023-04-25 02:15 UTC, hanagertrudekim commented on src/query/auth.ts
> +      sessionStorage.setItem('token', token);
아직 자동로그인 구현을 안해서 이부분은 다음 작업에서 생각해야할것같아요😅

2023-04-25 02:17 UTC, hanagertrudekim commented on src/query/auth.ts
> +      }
이건 토근 get에는 성공했는데, `getme()` 에서 실패했을경우를 생각해서 해줬습니다. 그런부분에서는 토큰이 남아있으면 안되니까 필요하지않을까요? (물론 session을 아예 이용하지않을거면 필요없는 작업이긴하네요)

2023-04-25 02:18 UTC, hanagertrudekim commented on src/query/auth.ts
> +      if (sessionToken) {
token을 다른 요청쪽에서 꺼내서 쓰는 경우가 있을것같아 일부로 넣었는데, 그부분에 대한 고려는 안해도되는걸까요?

2023-04-25 05:57 UTC, ChoiWonBeen commented on src/query/auth.ts
> +      if (sessionToken) {
로그인 요청에서 발생하는 로직인데다가 바로 윗줄에서 `setItem`을 진행한 결과를 그대로 가져올테니 불필요하게 `getItem`을 할 필요가 없겠다는 말이었어요.

2023-04-25 06:04 UTC, kimeodml requested changes
고생하셨습니다. 컴포넌트 분리 부분에서 궁금한 점이 있어 그 부분 위주로 올렸습니다!

2023-04-25 06:04 UTC, kimeodml commented on src/model/auth.ts
> +export interface LoginParam {
타입 지정을 model이라는 폴더에 넣은 이유를 알 수 있을까요? 항상 api폴더에서 지정만 해서 이전과 다른 차이점이 있는지 궁금합니다.  그리고 `model>auth`폴더로 묶는 게 나을 것 같아요.

2023-04-25 06:06 UTC, ChoiWonBeen commented on src/query/auth.ts
> +      }
로그인의 결과로 가져온 토큰은 너무 당연하게도 갓 만들어진 토큰이니 만료될 가능성은 없을 것 같지만..
getMe에서 실패한 경우라면, getMe에서 다루는건 어떨까요? 추후 자동로그인을 고려해 해당 함수가 만료된 토큰으로 getMe() 요청을 하는 경우까지 고려를 하는거죠
```ts
export const getMe = async (token: string) => authApi.get<UserResponse>(
  '/owner',
  { headers: { Authorization: `Bearer ${token}` } },
)
  .then(({ data }) => UserResponse.parse(data))
  .catch(() => {
    sessionStorage.removeItem('token');
    return null;
  });
};

```

2023-04-25 06:17 UTC, ChoiWonBeen commented on src/query/auth.ts
> +  const { setUser } = useAuthStore();
아래처럼 작성하면 [해당 값의 변경만 재렌더링을 발생시켜 성능을 향샹시킬 수 있다](https://docs.pmnd.rs/zustand/recipes/recipes#fetching-everything)고 하네요.
store에 `user`도 있으니, user의 변경이 setUser가 포함된 해당 훅까지 재렌더링을 발생시킬 수 있는 것이죠.

```suggestion
  const setUser = useAuthStore((state) => state.setUser);
```

2023-04-26 11:55 UTC, hanagertrudekim commented on src/api/auth/authApiClient.ts
> +});
생각해보니 대부분 요청에 토큰인증이 요구되어, 토큰을 담는걸 기본 세팅으로 지정해도 좋을것같아요! 
최상단 파일로 baseURL을 옮겨 인증 요구가 필요하지않다면 기본 `client`를 제공하고, 
인증 요구가 필요하면 헤더에 정보를 담아 보내주는 `accessClient` 제공해주었습니다.
이런식으로 재사용하는건 어떨까요? 5eb8c7cf932c76c543ae87c41bfaa0877c3c86d4

2023-04-26 12:06 UTC, hanagertrudekim commented on src/component/common/ErrorBoundary.tsx
> +    }
사실 저는 이부분이 가장 애매했는데,, fallback을 이용해서 Error 컴포넌트를 내려줬던건, 에러 바운더리가 쓰이는 곳에 따라 에러의 형태가 달라질수있다고 생각해서였습니다. (경우에 따라 에러 text, 이미지, 버튼 등등의 형태가 달라질수있는 상황을 가정했습니다..)
아직 구체적인 error 디자인이 안나와서 어떻게 에러를 표시할지는 정해지지 않았지만, 통일된 형태라면 그냥 Error를 반환하는것도 좋을것같네요!

2023-04-26 12:39 UTC, hanagertrudekim commented on src/index.scss
> +  font-family: NotoSansKR, sans-serif;
로딩할때 시스템폰트와 가까운 기본 font를 설정해주면 속도가 빨라진다는 장점이 있어서 같은 generic 계열의 font들을 추가해주었습니다. 
`NotoSansKR` 는 generic으로 묶이는게 `sans-serif` 밖에 없어서 일단은 저렇게 설정해두었지만,
이외의 글꼴들이 추가되면 같이 설정해주는것도 좋아보입니다!

2023-04-26 12:42 UTC, hanagertrudekim commented on src/component/common/Error.tsx
> +export default function Error(error: Props) {
다른 props들이 추가될것같지는않아 아래처럼 message를 꺼내주는방식으로 수정했습니다ㅎㅎ 53c076326e4e78e2a6c32889a41150f68ad482ef

2023-04-26 12:48 UTC, hanagertrudekim commented on src/index.tsx
> +});
오 좋은 캐치 감사합니다ㅎㅎ 전역으로 설정하는방법이 있는줄 몰랐네요! mutation의 기본 설정은 추후에 필요하면 추가하겠습니다6f049aab639c36dc580b9386ec99d9598ef0a167

2023-04-26 12:52 UTC, hanagertrudekim commented on src/model/auth.ts
> +}
값이 아예 안들어올 경우를 생각해서 모두 옵셔널로 처리해주었습니다. 근데 또 스웨거를 살펴보니 두개 모두 `required`가 요구되니 타입을 바꿔주는것이 맞을것같네요! 수정하겠습니다 2ffc03c76008f148162cc6c9a0ff751123635652

2023-04-26 13:03 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +            <div className={styles['auto-login__text']}>자동로그인</div>
ESLint의 label-has-associated-control이라는 룰에서 에러가 사라지지않는데, 접근성을 위해서 label과 input이 연관됨을 강요하는 규칙이라고 하네요..`htmlFor`을 설정해줘도 사라지지않아서 원인을 못찾고있는데 이 룰을 끄고 lable을 지정하는게 나을까요...??

2023-04-26 13:04 UTC, hanagertrudekim commented on src/query/auth.ts
> +      if (sessionToken) {
baseURL에다가 토큰을 넣는 방식으로 바꾸면서 같이 변경했습니다

2023-04-26 13:06 UTC, hanagertrudekim commented on src/store/auth.ts
> +  },
좋은 캐치 감사합니다! 9a9cd00236dceb4830246908621d70b1468ebadf

2023-04-26 13:06 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +                </Link>
ㅋㅋㅋ주석 추가해주었습니다.. 반복문을 돌려보니 뭔가 더 지저분해 보이더라구요ㅜㅜ 9a9cd00236dceb4830246908621d70b1468ebadf

2023-04-26 13:20 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +            <input className={styles['auto-login__checkbox']} type="checkbox" />
좋은 의견인것같습니다! 수정할게요ㅎㅎ 0693768afb3a3c67a1eeafdf6cf3d4e409bea5dc

2023-04-26 13:20 UTC, hanagertrudekim commented on src/page/Auth/Login/Login.module.scss
> +  margin: 8px 0 16px;
수정했습니다! 0693768afb3a3c67a1eeafdf6cf3d4e409bea5dc

2023-04-26 13:26 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +  });
`react-hook-form` 을 적용할지 안할지는 다시 상의해봐야할것같네요..ㅎㅎ

2023-04-26 13:28 UTC, hanagertrudekim commented on src/page/Auth/Login/Login.module.scss
> +    }
😊 👍

2023-04-26 13:33 UTC, hanagertrudekim commented on src/query/auth.ts
> +const useLogin = () => {
`react-query` 이용해서 호출한 api들은 query에 따로 모아두는것이 좋을것같아 그렇게 분리해두었습니다! query 에 대한 처리들을 모아두려했는데, 형태를 보니 그냥 hook으로 분류하는것이 더 깔끔해질수도있을것같네요..

2023-04-26 13:42 UTC, hanagertrudekim commented on src/model/auth.ts
> +export interface LoginParam {
`zod`를 적용하면서 model 이라는 폴더에 모든 스키마를 정의하는것이 좋다고 생각해서 분리하긴했는데, 어차피 api response에 관련한것이니 api 폴더 안에서 분리해도 괜찮을것같아요! 사용하기에도 그게 더 편리할것같네요 ㅎㅎ 수정했습니다 1597c6c6bbc648a43a08074c31b8fc51380a03ac

2023-04-26 13:44 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +            />
적절하게 padding 넣어주어 수정했습니다 2c5038b63451c57315dfb24480879269f6c304ed

2023-04-26 13:46 UTC, ChoiWonBeen commented on src/api/auth/authApiClient.ts
> +});
오호라 `api/index.ts`에 두고 관리하는게 좋은 아이디어네요!
전부 `accessClient`를 써도 괜찮겠지만 불필요한 헤더를 꼭 포함할 필요는 없겠죠, 분리한게 보기좋네요 👍

2023-04-26 13:50 UTC, ChoiWonBeen commented on src/component/common/ErrorBoundary.tsx
> +    }
기능 단위로 ErrorBoundary를 둘 수 있고, 에러가 발생했을 시, 그 기능을 전부 막는게 맞다고 생각하기에,
텍스트나 버튼같이 너무 작은 단위로 바운더리를 둘 일이 없을 것 같아 크기만 동적으로 처리하고 통일시키는게 바운더리를 만들때 너무 많은 리소스가 들어가지 않을 것 같아요.
사실 바운더리가 동작하지 않는 상황이 정상이고, 나올일이 흔하지도 않기에 일일히 챙겨주기엔 시간이 아까워보이기도 해요 ㅋㅋ

2023-04-26 14:14 UTC, ChoiWonBeen commented on src/model/auth.ts
> +export interface LoginParam {
전 model을 보고 싶은 경우와, api를 보고 싶은 경우는 다르다고 생각해서 (response가 아닌 request나, Props등도 관리할 수 있으니..) `model/auth/index.ts`가 좋아보인다에 한 표 올립니당

2023-04-27 17:46 UTC, hanagertrudekim commented on src/component/common/ErrorBoundary.tsx
> +    }
아하... 그러면 일단은 통일하고 만약에 나중에 작은 단위로 에러가 필요하다면 그때 분리하는거도 방법이겠네요 ㅎㅎ
에러 컴포넌트를 따로 만들지 않는 방향으로 수정해보겠습니다~

2023-04-28 03:46 UTC, hanagertrudekim commented on src/component/common/ErrorBoundary.tsx
> +    }
수정했습니다 76ec3f30ea1f7de1094e6f7eb6f38f6455b36887

2023-04-28 03:51 UTC, hanagertrudekim commented on src/page/Auth/Login/index.tsx
> +            <div className={styles['auto-login__text']}>자동로그인</div>
수정했습니다~ https://github.com/BCSDLab/KOIN_OWNER_WEB/pull/6/commits

2023-04-28 04:08 UTC, hanagertrudekim commented on src/query/auth.ts
> +      }
음...`api/auth/index` 안에는 사실 api 요청과 응답의 스키마 검사까지 관심사를 분리하고 
그렇게 통일하려해서,  고민이 되긴합니다😅
자동로그인 구현할때는 어쩔수없이 구조가 달라질수도있겠지만, 우선은 기존과 같이 통일하는것은 어떨까요??
getMe에서 성공, 실패에 따른 토큰 핸들링을 어디서해야할지는 더 고민해봐야하는건 맞는것같으니, 
자동로그인 구현때 한번 더 구조를 짜봐야겠네요...!

2023-04-28 04:12 UTC, hanagertrudekim commented on src/query/auth.ts
> +  const { setUser } = useAuthStore();
오 그렇네요 수정하겠습니다ㅎㅎ ff8ab25abcffb21084bc4ccc79cdaedfb4c08265

2023-04-28 08:43 UTC, ChoiWonBeen approved these changes
고생하셨어요~ 마무리 코멘트 남긴 부분 확인해보시고 이상없다면 머지해도 괜찮을 것 같아요!
그리고 에러 화면 추가됐는데, 이번꺼에 추가하거나, 다음 간단한 이슈로 두고 만들어도 될거같아요.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/50780281/235110244-8f19b7de-e47d-4af5-8231-1c5e2c9502d2.png">

2023-04-28 08:43 UTC, ChoiWonBeen commented on src/query/auth.ts
> +const useLogin = () => {
특정 훅들, 쿼리들은 여러 페이지에 걸쳐서 사용될 가능성이 있다는 걸 감안하면 지금 방식도 괜찮은 것 같아요.
내 상점 메뉴의 목록을 가져오는 쿼리가 있다면 메인페이지에서도, 이벤트 등 페이지에서도 쓰일 수 있으니, 페이지 단위의 훅은 부적절할 수도 있을 것 같다는 생각이..?

2023-04-28 08:43 UTC, ChoiWonBeen commented on src/query/auth.ts
> +      }
자동로그인 로직을 구현할 때 고민해도 괜찮아보여요 😄 
생각해보니 아직은 auth 값으로 관리하는게 없으니 자동로그인과 AuthRoute를 같이 다음 기능으로 생각해도 좋겠네요.

위 로직(error시 User타입에 할당된 null을 반환)은 나름 신경써본 로직이니 기억해주세요 ㅋㅋㅋ

2023-04-28 08:43 UTC, ChoiWonBeen commented on src/store/auth.ts
> +  setUser: (auth: UserResponse) => void;
User라는 타입을 따로 만들어 사용하는건 어떨까요?
다른 쪽에서 해당 타입을 사용하다면 신경써야하니.. 같은 점을 생각해봤어요
자동로그인에서 에러가 난다면 `setUser`에 `null`이 들어갈 수 있으니 해당 타입도 짧게 쓸 수 있을 것 같네요!
```ts
export const User = z.nullable(UserResponse);
```
```suggestion
  user: User;
  setUser: (auth: User) => void;
```

2023-04-29 06:17 UTC, hanagertrudekim commented on src/query/auth.ts
> +      }
네 알겠습니다 감사합니다😊

2023-04-29 06:32 UTC, hanagertrudekim commented on src/query/auth.ts
> +const useLogin = () => {
아하... 여러 곳에서 호출될것을 감안하면 그렇게 될수도 있겠네요!
query 의 목적이 데이터 캐싱인데  종속되어있지않고 전역으로 쓴다는 부분을 감안하지 못했네요.. ㅎㅎ
저도 이 부분에서는 query 로 빼는게 맞다고 생각되기에, 기존의 방식을 유지해보겠습니다😊

2023-04-29 06:41 UTC, hanagertrudekim commented on src/store/auth.ts
> +  setUser: (auth: UserResponse) => void;
오... 확실히 더 편하게 사용할수있을것같네요..! 
타입 이름이 애매하긴한데, 개인적으로 그냥 `User`이라는 말이 모호한것같아 `NotNullUser` 이런식으로 지정해도되려나.. 

뭔가 null 이 허용되지않는 타입이라는 느낌을 주고싶은데, `RequiredUser`이런식으로 하는건 어떨까요? 좀 어색한 감이 있을까요.. ㅋㅋㅋ

2023-04-29 14:57 UTC, hanagertrudekim commented on src/store/auth.ts
> +  setUser: (auth: UserResponse) => void;
아예 null값 예외처리를 스키마를 이용해서 처리하는것도 좋은 방법이네요
위와같이 User라는 스키마를 정의하면 타입으로 또 따로 정의해야해서,
이름도 바꿔서  `NullableUser` 타입으로 수정했습니다

2023-04-29 16:59 UTC, ChoiWonBeen commented on src/store/auth.ts
> +  setUser: (auth: UserResponse) => void;
ㅋㅋㅋㅋㅋ 가독성 측면에서 "유저" 라는 타입을 정의해야 한다고 생각하기에, (재사용할일이 많을거예요) `type User`를 정의할 필요가 있다고 생각했어요.

User는 스토어의 관점에서는 null이거나, UserResponse를 담은 객체일테고,
사용하는 입장에서는 `initialState`가 null 인 UserResponse를 담을 객체이니,
그냥 UserResponse 자체를 담거나, nullable을 추가해서 써도 괜찮겠다 정도의 의도였어요.

아마 NullableUser라고 이름지으면 추후에 유저 타입을 활용할 필요가 생겨 IDE에서 검색하게 된다면 `Use...` 이런식으로 찾게 될텐데 활용하지 못할 것 같아요 ㅋㅋㅋ

그리고 수정된 부분이 PascalCase에서 벗어났어요!

2023-04-30 07:37 UTC, hanagertrudekim commented on src/model/auth.ts
> +export interface LoginParam {
보면 모델이 쓰이는곳이 꼭 api에만 한정하면 안될것같아서 추가 코멘트를 달아봅니다... ㅎㅎ
api에 정의할 타입은 온전히 param, response만 정의하고
, 객체 정의, 스토어 등등..에 필요한 타입은 model로 분리한다면 조금 더 확실하게 분리가 가능할것아요! 두개 다 필요하다는 의견이 있기에 그런 방향으로 한번 수정해보겠습니다~

2023-04-30 07:43 UTC, hanagertrudekim commented on src/store/auth.ts
> +  setUser: (auth: UserResponse) => void;
위에 model에 관한 파일 구조를 한번 더 수정하면서, 애매하던 부분이 해결된것같습니다... ㅎㅎ
store의 관점에서는 nullable하니 그냥 `User`로 정의해될것같고, 활용도 더 좋을것같네요!

2023-05-01 12:10 UTC, kimeodml approved these changes

2023-05-01 12:25 UTC, merged