[내상점] 내상점 페이지 추가
BCSDLab/KOIN_OWNER_WEB pull request #7
Opened 2023-04-24 15:39 UTC by haejinyun

## [#3] request

## 내 상점 페이지 UI 구현
* 현재 UI구성만 완료 로직적인 부분 차후 진행 예정입니다.

## 메뉴 추가 모달 창 UI 구현
* 모달 창 제어를 위한 커스텀 훅 제작하였습니다.

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86779590/234044760-f2d9b97b-23b9-4cf9-8c95-bddb2a4f69cc.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86779590/234044827-da320ce9-8264-4815-925b-1f9e11b5f5f0.png">

### Precautions (main files for this PR ...)

* 기초적인 UI 디자인으로 차후 페이지의 로직 부분이 추가되면 그에 따른 UI 추가가 있을 예정입니다.

2023-04-25 05:51 UTC, ChoiWonBeen requested changes
고생하셨어요~ "UI를 만들 때는 이러한 점들도 고려해야 한다"를 최대한 느낄 수 있게끔 리뷰해봤어요.
기본적으로 `padding-margin` 구분과, `input, button`등에는 적절한 마크업을 사용해야 한다는 점,
class명의 네이밍 컨벤션을 다른 사람들과 맞추는 것을 고려하며 만들어보세요!

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/component/common/Header/index.tsx
> +import { ReactComponent as LogoMobileIcon } from 'assets/svg/common/coin-logo-mobile.svg';
coin이 아니라 koin(**ko**reatech.**in**)...

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/component/common/Header/Header.module.scss
> +  }
`header--main`은 다른애들과는 좀 다르게 들어간 것 같은데 왜 이렇게 들어갔나요?

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/Menus.tsx
> +      </div>
<img width="341" alt="image" src="https://user-images.githubusercontent.com/50780281/234179890-b659ebd1-9c51-4e3e-940f-e772fc72542c.png">

`defaultImage` 가 만들어져있으니 이걸 써서 만들어두는건 어땠을까요?
response가 들어왔다는 가정 하에 임시 객체를 만들어두고, 해당 객체로 반복문을 돌리는게 UI를 만드는게 연습에는 적절하니 그렇게 만들어보는것도 좋을거같아요!

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/App.tsx
> +        <Route path="/store-info" element={<MystorePage />} />
아직까지의 기획상으로는 메인페이지에 더 적합하니 index로 두는건 어떨까요?

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/index.scss
> +@use 'src/utils/styles/mediaQuery' as media;
그냥 큰따옴표로 쓰면 되는거 아닌가요?
이게 필수라면 설정을 전역으로 두는것도 생각해볼 수 있을것같구요?

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +              <input className={styles['modalContainer__menu-name-input']} placeholder="   예) 불족발 + 막국수 저녁 SET" />
placeholder를 띄어쓰기보단, input에 `padding-left`를 주는게 더 적절했겠죠? ㅋㅋ
입력이 어색해지는 문제가 발생해요
<img width="210" alt="image" src="https://user-images.githubusercontent.com/50780281/234182388-65726760-ee36-40c3-8201-6e8f23f44e9a.png">

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +                메뉴명
이게 각 칸마다 margin-left를 담지 않고 
container에 padding-left를 주면 코드의 중복을 많이 줄일 수 있겠죠?

<img width="278" alt="image" src="https://user-images.githubusercontent.com/50780281/234182534-c07a7a92-3ad9-484e-908c-dc27d634b0bd.png">

각 헤더 사이의 간격도 32px이던데, 
`flex`, `flex-direction: row`, `gap: 32px`을 주면 더 간단히 작성할 수 있었지 않았을까~ 개인적으로 생각해요.

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +                <input className={styles['modalContainer__price-input']} placeholder="원   " />
"원"이 placeholder로 들어가있는것보다는, 고정 텍스트로 들어가있는것도 좋아보여요.
`<input />` 밖으로 빠져있는?
그리고 가격에 문자가 들어가니 `type="number"`가 필요하지 않을까 싶어여

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +                  </div>
각각이 버튼이어야 할 것 같고, 눌렸을 때 색깔이 바뀌는 `--selected`를 추가해주면 좋을 것 같아요.
`--unit`은 블록의 상태가 아니죠!

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +      <div className={styles.modalContainer}>
전부 `modalContainer`라는 block 안에 들어가있는 구조인데, 사실 다른 모든 컴포넌트의 단어 단위는 `-`으로 구분돼있으니 `modal-container`가 적절하죠.

근데 그냥 `modal` 정도만 써도 문제없을 것 같구요? 일일히 modal-container로 쓸 필요까진 없어보여요

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +          <div className={styles.modalContainer__Title}>
뜬금없이 PascalCase로 작성돼있어요

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +};
닫기 기능을 하는 배경이 컴포넌트 내에 포함돼있기때문에 closeModal 함수가 옵셔널일 필요는 없을것같아요!

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/index.tsx
> +const storeInfos = ['전화번호', '운영 시간', '휴무일', '주소정보', '배달 금액', '가게 정보'];
다른 상수들처럼 UPPER_CASE로 적어두는건 어땠을까요?

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/utils/hooks/useModalOpen.ts
> +  const [isOpenModal, setIsOpenModal] = useState(false);
진~~~짜 사소한데 `isModalOpen`이 더 끌리지 않나요? 전 개인적으로 "모달이 열렸는가" 를 표현한다면 이게 더 어울리는 것처럼 보여요.
물론 개인 차이일수도

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/utils/hooks/useModalOpen.ts
> +  };
제 개인적인 경험, 당연하다고 생각하는 UX중에는 모달창을 `ESC`키를 눌러서 닫을 수 있어야 한다고 생각해요.
이벤트리스너를 추가하는건 어떨까요?

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/static/menuCategory.ts
> +  },
사실 얘낸 나중에 API로 불러올 값이랍니다.
수정할수도 있어질거예요

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/index.tsx
> +              <div className={styles.store__title}>가장 맛있는 족발</div>
조금은 의미론적인 태그들을 사용해주세요 ~~ 
```suggestion
              <h1 className={styles.store__title}>가장 맛있는 족발</h1>
```

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +                  <CheckCircleIcon className={styles['modalContainer__single-menu--icon']} />
`<input type="checkbox" />` 와 `label` 로 이루어졌어야 했겠죠? ㅋㅋㅋ

2023-04-25 05:51 UTC, ChoiWonBeen commented on src/page/Mypage/MystorePage/index.tsx
> +              <div className={styles.store__updateBtn}>가게 정보 수정</div>
얘도 버튼이죠. 클래스명도 `-`로 단어를 구분해주세요~

2023-04-25 05:52 UTC, ChoiWonBeen commented on src/component/common/Header/index.tsx
> +import { ReactComponent as LogoMobileIcon } from 'assets/svg/common/coin-logo-mobile.svg';
아 이거 대의누나꺼 PR에 올라온거구나.. @kimeodml

2023-04-25 14:26 UTC, kimeodml requested changes
고생하셨습니다. 몇몇 클래스명이 camelCase로 되어 있는데 수정해야할것 같아요.

2023-04-25 14:26 UTC, kimeodml commented on src/utils/hooks/useModalOpen.ts
> +  const [isOpenModal, setIsOpenModal] = useState(false);
useBooleanState 훅으로 사용할 수 있을 것 같은데 변경해주세요~

2023-04-25 14:26 UTC, kimeodml commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +              <textarea className={styles['modalContainer__menu-combo-input']} placeholder=" 예) 불족발(소,중,대) + 막국수 + 랜덤 서비스 음료(500ml)" />
`padding-top: 8px` 추가로 들어가야 할것 같아요.

2023-04-26 12:22 UTC, haejinyun commented on src/App.tsx
> +        <Route path="/store-info" element={<MystorePage />} />
네 해당부분 수정했습니다!

2023-04-28 14:14 UTC, haejinyun commented on src/page/Mypage/MystorePage/Menus.tsx
> +      </div>
조언해주신 방향으로 수정 해보았습니다!

2023-04-28 14:18 UTC, haejinyun commented on src/static/menuCategory.ts
> +  },
네! 임시로 만들어 둔 부분입니다!

2023-04-28 14:20 UTC, haejinyun commented on src/page/Mypage/MystorePage/index.tsx
> +              <div className={styles.store__title}>가장 맛있는 족발</div>
네! 해당 부분과 관련 부분 수정 했습니다.
앞으로 진행 할 부분에서 참고하겠습니다!

2023-04-28 14:32 UTC, haejinyun commented on src/page/Mypage/MystorePage/index.tsx
> +              <div className={styles.store__detailData}>
네 수정했습니다! 조금 더 신경쓰겠습니다..!

2023-04-28 14:34 UTC, haejinyun commented on src/page/Mypage/MystorePage/AddMenuModal.tsx
> +              <input className={styles['modalContainer__menu-name-input']} placeholder="   예) 불족발 + 막국수 저녁 SET" />
피그마를 확인해보니 모달창이 가게 정보 수정으로 바뀌어서 말씀해주신 모달창 관련 피드백은 다시 작업하면서 반영하겠습니다!

2023-04-29 18:00 UTC, ChoiWonBeen approved these changes
모달이 페이지로 바뀐다하니 모달쪽 리뷰들이 애매해졌네요 ㅋㅋㅋ
아직 UPPERCASE나 bem 관련해서 리뷰들이 몇개 남아있으니 마저 수정되면 병합해도 될 것 같아요.

2023-05-01 15:38 UTC, haejinyun commented on src/page/Mypage/MystorePage/index.tsx
> +                ))}
해당 부분 예시 데이터 넣고 컴포넌트 분류 진행하였습니다!

2023-05-02 06:55 UTC, HAEROOL approved these changes
고생하셨습니다:)

2023-05-02 06:55 UTC, HAEROOL commented on src/model/storeInfo/myStoreInfo.ts
> +  deliveryPrice: 0,
`deliveryPrice`만 다른 네이밍 케이스를 사용한 이유가 있나요??

2023-05-02 09:01 UTC, haejinyun commented on src/model/storeInfo/myStoreInfo.ts
> +  deliveryPrice: 0,
해당 부분 확인 후 수정하였습니다! 감사합니다!

2023-05-02 16:46 UTC, kimeodml approved these changes

2023-05-02 16:46 UTC, merged