[회원가입] 회원가입 페이지 추가
BCSDLab/KOIN_OWNER_WEB pull request #8
Opened 2023-04-25 05:58 UTC by HAEROOL

## [#2] request

## 회원가입 페이지 UI 구형
 - 회원가입 페이지 UI 구성완료했습니다.
 

## Please check if the PR fulfills these requirements

- [x] It's submitted to `develop` branch, __not__ the `main` branch
- [x] The commit message follows our guidelines
- [x] Did you merge recent `deveop` branch?

### Screenshot
<img width="1470" alt="스크린샷 2023-04-25 오후 2 46 53" src="https://user-images.githubusercontent.com/71335694/234186468-1890711e-bb70-4fce-8bc9-754b0ec3f162.png">
<img width="1470" alt="스크린샷 2023-04-25 오후 2 47 03" src="https://user-images.githubusercontent.com/71335694/234186476-8a860b9e-8484-4130-b26c-0b8a6aa78311.png">
<img width="334" alt="스크린샷 2023-04-25 오후 2 47 24" src="https://user-images.githubusercontent.com/71335694/234186485-410a35f5-07d2-4b28-a58f-02bccbdaebbb.png">
<img width="334" alt="스크린샷 2023-04-25 오후 2 47 37" src="https://user-images.githubusercontent.com/71335694/234186496-3e29d447-1a99-41e6-aab7-28c8ae89b9a4.png">

### Precautions (main files for this PR ...)
 - 개발 시 로직 추가되면 그에따라 UI 추가작업 가능성 있습니다.
 - 이용약관내용은 차후 수정예정입니다.

2023-04-25 12:34 UTC, ChoiWonBeen requested changes
직접 만나서 언급했던것들 수정되면 Re-Request 해주세요!

2023-04-25 14:40 UTC, haejinyun approved these changes

2023-04-25 14:58 UTC, haejinyun submitted a review, later dismissed
수고하셨습니다! 코드를 보면서 제가 신경쓰지 못했거나 className을 정하는 부분에서 많이 참고 할 수 있을 것 같습니다!

추가적으로 약관 동의 부분에서 동의 체크할 때, 마우스 커서가 pointer로 되어도 좋을 것 같습니다.
다른 사이트들을 참고했는데 대부분 pointer로 되는 것을 확인 할 수 있었습니다!

2023-04-27 17:40 UTC, hanagertrudekim submitted a review, later dismissed
수고하셨습니다! 고려할 부분이 많으셨을것같은데 모두 잘 동작하는것같아요
코멘트 확인 부탁드립니다 🙂

2023-04-27 17:40 UTC, hanagertrudekim commented on src/page/Auth/Signup/index.tsx
> +                  <>
```suggestion
                  {step !== 0 ? <ProgressBar step={step} /> : 
                  (
                  <>
```
삼항연산자를 이용하는건 어떨까요?

2023-04-27 17:40 UTC, hanagertrudekim commented on src/page/Auth/Signup/view/OwnerDataPage/index.tsx
> +              <input className={`${styles['form__input__registration-number--first']}`} type="text" maxLength={3} />
```suggestion
            <div className={styles['form__input__registration-number']}>
              <input className={styles['form__input__registration-number--first']} type="text" maxLength={3} />
```
classname을 변수로 넣으신 이유가 있을까요?

2023-04-27 17:40 UTC, hanagertrudekim commented on src/page/Auth/Signup/component/CustomCheckBox/index.tsx
> +}
`CustomCheckBox` 컴포넌트를 따로 만드신 이유가 있을까요? 재사용성을 고려하기엔 그냥 input과는 별 차이가 없는것처럼 느껴져서요.. 그리고 제가 못찾는건지 따로 쓰이는 곳이 없는것같기도하네요!

2023-05-01 14:42 UTC, kimeodml reviewed
고생하셨습니다. 상대경로들 절대경로로 수정하면 될것 같아요!

2023-05-08 00:03 UTC, ChoiWonBeen commented
최신 dev를 머지해주시면 변경사항을 확인하기 더 편할 것 같아요~

2023-05-10 06:32 UTC, HAEROOL commented on src/page/Auth/Signup/component/CustomButton/index.tsx
> +    >
완료했습니다. df44fa2c6bf9722c1a4cb0616fbda1cb7d6855f5

2023-05-10 06:34 UTC, HAEROOL commented on src/page/Auth/Signup/component/Term/index.tsx
> +export default function Term({ id }: any) {
Term 컴포넌트 불필요하다 판단하여 삭제했습니다. ac80217e480117793ffcbcf3be1d428b341d197c

2023-05-10 06:35 UTC, HAEROOL commented on src/page/Auth/Signup/component/Term/index.tsx
> +        <br />
완료했습니다. ac80217e480117793ffcbcf3be1d428b341d197c

2023-05-10 06:36 UTC, HAEROOL commented on src/page/Auth/Signup/component/UserPassword/index.tsx
> +        <input className={styles.form__input} placeholder={`비밀번호${!isMobile ? ' 입력 (필수)' : ''}`} type="password" />
적용완료했습니다. ff3ed05a15a5af16de3cf1ac325f675e24aa9a05

2023-05-10 06:44 UTC, HAEROOL commented on src/page/Auth/Signup/index.tsx
> +                  <>
해당 부분은 `step`이 0이 아닌 경우에만 `ProgressBar`가 렌더링 되지 않도록 해야하여 3항 연산자를 쓸 경우엔 더 복잡해질 것 같다고 생각합니다. 좀 더 가독성 있게 코드를 변경했습니다. a1d27d0da6b804dfde86556b7c0f5ac57b6fa4ff

2023-05-10 06:47 UTC, HAEROOL commented on src/page/Auth/Signup/view/OwnerDataPage/index.tsx
> +              <input className={`${styles['form__input__registration-number--first']}`} type="text" maxLength={3} />
잘못 사용한 부분인 것 같습니다. 수정 완료했습니다. b27a4d3e56b167aeb6db17576faf03c644329f19

2023-05-10 06:48 UTC, HAEROOL commented on src/page/Auth/Signup/component/CustomCheckBox/index.tsx
> +}
`CustomCheckBox` 불필요하다 판단하여 삭제했습니다. 8483461bda2c54234e6406f0b067c29b5b684086

2023-05-10 06:53 UTC, HAEROOL commented on src/page/Auth/Signup/view/TermsOfServicePage/index.tsx
> +          <span className={styles['agree--all__pc--phrase']}>아래 이용약관에&nbsp;</span>
figma 기준 padding-left 추가 안되어있는 것 같아 문구만 수정하였습니다. ac80217e480117793ffcbcf3be1d428b341d197c

2023-05-10 06:54 UTC, HAEROOL commented on src/page/Auth/Signup/index.tsx
> +              <Link to="/login" className={styles['back-button']}><Back /></Link>
적용 완료했습니다. b68e00a2ad5d70b873f5c0b835a6797ddbd10be4

2023-05-10 10:46 UTC, ChoiWonBeen approved these changes
고생하셨어요~~

2023-05-10 10:46 UTC, ChoiWonBeen approved these changes
고생하셨어요~~

2023-05-10 10:54 UTC, merged